### ISSUE TITLE
Split ParallelBest into "client groups" and "parallel"

### ISSUE THREAD

**Issue by ThinkChaos** [0xERR0R/blocky#1001]
The `ParallelBestResolver` fulfills two purposes:
1. choosing upstreams based on the client
2. querying those in parallel

I think we should split it.

The way I'd try to implement it is by having each group's list of resolvers actually be a single "parallel" resolver.  
From an architecture point of view, blocky would be less "list of resolvers" and more tree-like. This change was already somewhat started with #449.

Going towards a tree-like architecture would also be a good step towards #476.

I have no plans of actually working on this at the moment, just want to track this and get feedback.

**Comment by 0xERR0R** [comment]
relevant issue: https://github.com/0xERR0R/blocky/issues/355

**Comment by 0xERR0R** [comment]
@ThinkChaos: is there some open points after #1093 was merged?
