### ISSUE TITLE
Feature Request: Block TLD

### ISSUE THREAD

**Issue by padey** [0xERR0R/blocky#1036]
Hi all,

I would like to block a complete TLD: *.zip
Background:  https://medium.com/@bobbyrsec/the-dangers-of-googles-zip-tld-5e1e675e59a5

I have tried via a custom block list 
- *.zip
- .zip
- ||.zip^
- /.zip

.. to block, unfortunately without success.

Since I would like to log users who click on a .zip domain and of course the link, I would have to do it via a blocklist....
If there is no way to block such stupid TLD yet, I think this would be a good feature. 

Best regards!

**Comment by kwitsch** [comment]
This should work: `/.*\.zip/`

**Comment by padey** [comment]
Works, not ideal, but works. :)

```
nslookup update.zip

Name:    update.zip.INTERNAL-DOMAIN.com
Addresses:  ::
          0.0.0.0
```

**Comment by 0xERR0R** [comment]
You can try this one:
`/.*\zip$`

**Comment by padey** [comment]
That one works perfect! 

```
nslookup update.zip

Name:    update.zip
Addresses:  ::
          0.0.0.0
```
