### ISSUE TITLE
Windows build permission prevents running as service

### ISSUE THREAD

**Issue by http403** [0xERR0R/blocky#1053]
# Version
0.21

# Goal
Running Blocky as a Windows Service via NSSM

# Expected Bahavior
Run and serving DNS requests

# Actucal Bahavior
Windows Service reported "Access Denied"

# Step to reproduce
1. Download the release
2. Extract to `C:\blocky\`
3. Run `nssm.exe install "BlockyDns" "C:\blocky\blocky.exe"`
4. Start the service `nssm.exe start "BlockyDns"
5. Fail to start

# Suspected problem
Wrong permission order prevents SYSTEM, hence LOCAL SERVICE to run the executable
<details>
<summary>Images</summary>

![image](https://github.com/0xERR0R/blocky/assets/8369976/adcea461-8656-47c1-86f5-fa0a807517ab)
![image](https://github.com/0xERR0R/blocky/assets/8369976/4ff1d87e-77ca-46d8-999e-3e4487597901)

</details>

# Workarounds
1. Remove Deny permission entries in **Properties > Security > Advanced**; or
2. Run the service as the user who extracted it

**Comment by 0xERR0R** [comment]
Is there something we should do with binary (exe)?

**Comment by http403** [comment]
Let me try the new version first and see if the problem persists. However I don't know how long it would take as my laptop is broken and waiting for parts to repair.

**Comment by adamsewell** [comment]
I too am having an issue getting blocky installed as a service on Windows. I don't believe it's a permissions issue per say but something funky is going on. I've successfully created the service, and running it as "Network Service", verified the permissions and I'm still getting a timeout error, saying "The Service did not respond to the start or control request in a timely fashion". Running blocky via the command line works just fine. I'm not sure if there's something that needs to change in the startup of blocky to notify services of it staring up or what. 

Just for clarity, here is the powershell command I'm using to create the service:
```
$blocky_dir = $env:SystemDrive + "\mygeeknc\blocky"
New-Service -Name 'blocky' -BinaryPathName "$blocky_dir\blocky.exe -c ""$blocky_dir\config.yaml""" -DisplayName "blocky" -StartupType "Automatic" | Out-Null
```

**Comment by kwitsch** [comment]
Blocky is simply a console application and not a service binary.
If I remember correctly service binaries have to implement some interfaces to function without problems.
There are wrappers for that part as described here: https://www.wintips.org/how-to-run-an-application-as-service/

**Comment by adamsewell** [comment]
Fair point, I had assumed it was written in. I was able to get nssm working with blocky. Thanks.
