### ISSUE TITLE
Some mertics may need to be cached, otherwise the restart will reset to 0

### ISSUE THREAD

**Issue by bboysoulcn** [0xERR0R/blocky#1087]
Some mertics may need to be cached, otherwise the restart will reset to 0

Such as blocky_query_total

**Comment by 0xERR0R** [comment]
"blocky_query_total" is defined as counter. Counter can only be increased or reset (on blockys restart). This should be handled by prometheus (prometheus counts only increases and if counter receives 0 value, this will be ignored). See https://prometheus.io/docs/concepts/metric_types/

**Comment by bboysoulcn** [comment]
ok thanks
