### ISSUE TITLE
Wildcard list support

### ISSUE THREAD

**Issue by t-e-s-tweb** [0xERR0R/blocky#1090]
Hey guys! long time. Can someone let me know if blocky supports these kind of blocklists? These are very well made and has comments for the type of site and its name but blocky throws a lot of errors. Can you guys please test? 

https://github.com/ShadowWhisperer/BlockLists/blob/master/Whitelists/Whitelist

**Comment by kwitsch** [comment]
As these appear to be simple domain lists they should work .

**Comment by ThinkChaos** [comment]
I think the best thing for wildcards would be to use a trie.  
I got something working locally using [dghubble/trie](https://github.com/dghubble/trie) that uses 33 MB with the OISD big list. Seems reasonable when compared to regex (303 MB) and plain domain list (16 MB).

I'll try to get a PR open soon.
