### ISSUE TITLE
TTL of A record not respected when resolved indirectly via CNAME

### ISSUE THREAD

**Issue by tom-mi** [0xERR0R/blocky#1091]
Hello,
I have the following DNS setup for a server running at my home (DNS names redacted):
`server.example.com` -> A Record  updated via DynDNS, TTL 60
`foo.example.com` -> CNAME pointing to `server.example.com`, TTL 86400

When resolving `foo.example.com` via a "regular" DNS server, I get an answer like this:
```
$ dig foo.example.com @8.8.8.8

; <<>> DiG 9.18.14 <<>> foo.example.com@8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 15606
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;foo.example.com.		IN	A

;; ANSWER SECTION:
foo.example.com.	21600	IN	CNAME	server.example.com.
server.example.com.    600	IN	A	X.X.X.X

;; Query time: 23 msec
;; SERVER: 8.8.8.8#53(8.8.8.8) (UDP)
;; WHEN: Wed Aug 02 21:41:12 CEST 2023
;; MSG SIZE  rcvd: 88
```

However, when querying blocky, the TTL of the A record is the same as for the CNAME entry:
```
$ dig foo.example.com @192.168.0.3

; <<>> DiG 9.18.14 <<>> foo.example.com @192.168.0.3
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40860
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;foo.example.com.		IN	A

;; ANSWER SECTION:
foo.example.com.	22936	IN	CNAME	server.example.com.
server.example.com.   22936     IN	A	Y.Y.Y.Y

;; Query time: 0 msec
;; SERVER: 192.168.0.3#53(192.168.0.3) (UDP)
;; WHEN: Wed Aug 02 21:43:50 CEST 2023
;; MSG SIZE  rcvd: 77
```
This means that for this kind of setup **the TTL of the A record is not respected**, which can lead to surprising results.
(In my case this causes issues as the IP of the server is changing every couple of days)

**Comment by 0xERR0R** [comment]
Blocky caches the entire response and uses the max TTL from response entries. It would be difficult to have different TTLs in cache for the same response. One solution could be to use the min TTL instead of max, so in your case 600 second for both RRs in the answer section.
