### ISSUE TITLE
Wrong blockType in documentation

### ISSUE THREAD

**Issue by dynek** [0xERR0R/blocky#1114]
Hello,

Looks like this is wrong: https://github.com/0xERR0R/blocky/commit/9d33bcd3a123694438adc6aaaeae56500caed52e#diff-17ed18489a956f326ec0fe4040850c5bc9261d4631fb42da4c52891d74a59180R280

Mentioning IP addresses instead of `nxDomain` or `zeroIP`.

Will gladly raise a PR if confirmed + which type should be used as example :-)

Cheers

**Comment by 0xERR0R** [comment]
If you think the current description is misleading, please feel free to improve it, every pull request is welcome

**Comment by dynek** [comment]
My mistake, I missed this part of the documentation, staging IP addresses can mentioned.

Sorry for this!
