### ISSUE TITLE
doh dns authentication support

### ISSUE THREAD

**Issue by bboysoulcn** [0xERR0R/blocky#1128]
I don't want others to use my dns service

Can an authentication function be added to the dns server

**Comment by 0xERR0R** [comment]
AFAIK, DoH clients don't support authentication. Theoretically, you can put a reverse proxy and use basic auth (use user/password in the url), but I didn't try it.

**Comment by bboysoulcn** [comment]
blocky  | [2023-09-08 10:47:27] FATAL unable to load configuration: wrong file structure: can't convert upstream 'https://user:pass@dns.xxxxxx.cn/dns-query': can't convert port to number (1 - 65535) strconv.ParseUint: parsing "pass@dns.xxxxxx.cn": invalid syntax

**Comment by bboysoulcn** [comment]
> AFAIK，DoH客户端不支持身份验证。理论上，您可以放置​​反向代理并使用基本身份验证（在网址中使用用户/密码），但我没有尝试。



> AFAIK, DoH clients don't support authentication. Theoretically, you can put a reverse proxy and use basic auth (use user/password in the url), but I didn't try it.



> AFAIK, DoH clients don't support authentication. Theoretically, you can put a reverse proxy and use basic auth (use user/password in the url), but I didn't try it.

I try

**Comment by 0xERR0R** [comment]
related to #1109

**Comment by leath-dub** [comment]
I would set up a vpn if you want to restrict your DNS. Really that is the only way in this case.
