### ISSUE TITLE
Documentation site ignores version if accesed through a linkt to the Installation chapter

### ISSUE THREAD

**Issue by JenswBE** [0xERR0R/blocky#1133]
While updating deprecated keys in my config, I noticed the documentation site is not aligned with the latest release:
![image](https://github.com/0xERR0R/blocky/assets/6514515/33f36e08-20f9-4b08-8729-c93c38c8a80c)

I specifically noticed following doc is missing: https://github.com/0xERR0R/blocky/pull/1086/files. But more might be.
I ensured I didn't use a locally cached version of the site. But seems be the case even without cache.

Can you please have a look?

**Comment by kwitsch** [comment]
Configuration example for `v0.22` and `main`  are looking correct on my mobile phone.

![IMG_20230910_224750.jpg](https://github.com/0xERR0R/blocky/assets/10324063/3dc47d22-1bb1-46f8-a887-3d59235867e9)

Or am I missing something?

**Comment by JenswBE** [comment]
After some further digging, it seems the `installation` link at https://github.com/0xERR0R/blocky/#quick-start is not redirecting to the latest docs. Other links work correctly as they redirect.

**Comment by kwitsch** [comment]
I can reproduce it.
Thanks for digging into it.

**Comment by 0xERR0R** [comment]
The link should point to "https://0xerr0r.github.io/blocky/latest/installation/" instead of "https://0xerr0r.github.io/blocky/installation/"
