### ISSUE TITLE
RFE: Specify blocky to bind to a particular interface/ip address

### ISSUE THREAD

**Issue by gfa** [0xERR0R/blocky#116]
Hello

first thanks for blocky, it is a useful piece of software :) 

I'd like to ask to be able to configure the interface or ip address (better) on which blocky listens to, either way with a parameter or a config stanza.

right now I workaround the missing feature making blocky to listen on another port than 53 and doing a redirect using iptables but it doesn't feel clean.

thanks!

**Comment by 0xERR0R** [comment]
Hey, just for my understanding: you have multiple network interfaces and you want to bind blocky only to one of them? It would be possible, if you use docker. For blocky standalone, a code change is necessary.

**Comment by gfa** [comment]
Hello


i'm interested to blocky standalone because i'm not using docker. There
are workarounds and i'm using them, so this is not a blocker for me,
just a nice to have :)


On Tue, Dec 15, 2020 at 01:10:39AM -0800, Dimitri Herzog wrote:
>Hey, just for my understanding: you have multiple network interfaces and you want to bind blocky only to one of them? It would be possible, if you use docker. For blocky standalone, a code change is necessary.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/0xERR0R/blocky/issues/116#issuecomment-745155877

-- 
IRC: gfa
GPG: 0x27263FA42553615F904A7EBE2A40A2ECB8DAD8D5
OLD GPG: 0x44BB1BA79F6C6333

**Comment by 0xERR0R** [comment]
Port can now be specified as "port" or "ip:port"

Examples:

- 53
- :53
- 127.0.0.1:53
