### ISSUE TITLE
Split horizon DNS

### ISSUE THREAD

**Issue by woutwoot** [0xERR0R/blocky#1163]
With custom DNS, Is it possible to return a different IP for a hostname based on the client IP (more specifically, the subnet)?

Reason is that I'd like to use this DNS server for both my local network and Tailscale. In this case I would be able to return a different IP for my NAS depending on where I'm making the request from. 

For example:

Requester IP: 192.168.1.100
Request: example.com
Response: 192.168.1.125

Requester IP: 100.65.88.14
Request: example.com
Response: 100.80.221.15

**Comment by 0xERR0R** [comment]
No, it is not possible. Maybe you can do it with 2 instances of blocky with different configuration, one for your local network and one for tailscale

**Comment by woutwoot** [comment]
That sounds a bit cumbersome to be honest (I want to manage the config in one place) but thank you for your answer. Consider this a feature request if you want.

**Comment by kwitsch** [comment]
You could split the blocky config into multiple files in one folder and mount them into docker containers.
That way all configurations would be in one place and common options can be shared among multiple instances.
