### ISSUE TITLE
Error for upstream ipv6 address

### ISSUE THREAD

**Issue by NoctivagusObitus** [0xERR0R/blocky#119]
Hi

I have recently come across blocky and i like it a lot!

So far i have build my whole infrastructure based on ipv6 but setting an ipv6 upstream resolver fails for me with:
`ERROR server: error on processing request: dial udp: address [[2001:4860:4860::8888]]:53: missing port in address`
Here is the config i am using for that:
```
upstream:
    externalResolvers:
        - "udp://[2001:4860:4860::8888]:53"
```

That should be syntactically correct since there is a test using `"udp:[fd00::6cd4:d7e0:d99d:2952]:53"` as an example? (https://github.com/0xERR0R/blocky/commit/1e276599f9af5133b7fb1f5cee7a33e0da705326)

Obviously the double `[]` shown by the error message is incorrect if it is used to contact the upstream server address in the end.

**Comment by 0xERR0R** [comment]
The address seems to be valid, it is probably a bug in the validation. I'll take a look and test it. Can you use the notation with zeros as workaround?

**Comment by NoctivagusObitus** [comment]
Thanks!
I tried:
```
upstream:
    externalResolvers:
        - "udp://[2001:4860:4860:0000:0000:0000:0000:8888]:53"
```
and got: `ERROR server: error on processing request: dial udp: address [[2001:4860:4860:0000:0000:0000:0000:8888]]:53: missing port in address`

**Comment by 0xERR0R** [comment]
Hm.. strange, just tried with
```
upstream:
  externalResolvers:
    - "udp://[2001:4860:4860::8888]:53"
```

And it works...

Log output:
```
[2020-12-22 11:22:46]  INFO server: -> resolver: 'ParallelBestResolver'
[2020-12-22 11:22:46]  INFO server:      upstream resolvers:
[2020-12-22 11:22:46]  INFO server:      - upstream 'tcp+udp:[[2001:4860:4860::8888]]:53'
```

**Comment by NoctivagusObitus** [comment]
strange indeed
i am using this docker image:
```
docker image inspect --format='{{.Id}}' c6164de65147
sha256:c6164de651474d9459de51e72d88acc2e376fc312f01265c9beabc327a78b7b3
```

config was looking similar to yours:
```
INFO server: -> resolver: 'ParallelBestResolver'
INFO server:      upstream resolvers:
INFO server:      - upstream 'tcp+udp:[[2001:4860:4860::8888]]:53'
```

**Comment by 0xERR0R** [comment]
The validation was ok, but "[" and "]" must be removed from the url, UDP client can't process it. If you use docker, you can test the "development" tag, this ist the latest master build.

**Comment by NoctivagusObitus** [comment]
I went ahead and pulled 
```
docker image inspect --format='{{.Id}}' d9d173d0996b
sha256:d9d173d0996b7ee9526393b6d2b235d8d75a8e98eb7c9384d5d885305924e50b
```

with this one i can either configure upstream as `udp://[2001:4860:4860::8888]:53` and getting the following error:
`ERROR server: error on processing request: read udp [fdff::d]:36482->[2001:4860:4860::8888]:53: i/o timeout`

or i go without the `[]` -> `udp://2001:4860:4860::8888:53` and getting the following:
`ERROR server: error on processing request: dial udp: lookup 2001: no such host`

**Comment by 0xERR0R** [comment]
I have only ip4 network and can't test with ipv6 dns upstream. Tried with dig, but I get "connection timed out; no servers could be reached"... I'll try to find the possibility to test with ipv6 dns...

**Comment by NoctivagusObitus** [comment]
Thanks a lot for putting in the effort. Let me know if i can test something for you.

**Comment by 0xERR0R** [comment]
After some "challenges" with my router and my network configuration, I could establish the ipv6 connection. My test setup:

Calling cloudflare ipv6 DNS directly with dig:
```
dig -6 @2606:4700:4700::1111 google.de                                                                                                                                                                 

; <<>> DiG 9.16.8 <<>> -6 @2606:4700:4700::1111 google.de
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12054
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;google.de.                     IN      A

;; ANSWER SECTION:
google.de.              300     IN      A       172.217.18.99

;; Query time: 46 msec
;; SERVER: 2606:4700:4700::1111#53(2606:4700:4700::1111)
;; WHEN: Tue Dec 22 20:40:15 CET 2020
;; MSG SIZE  rcvd: 54

```

Now configuring cloudflare ipv6 DNS in Blocky:

```
upstream:
  externalResolvers:
    - udp://[2606:4700:4700::1111]:53
```

Blocky runs on port 55555

```
dig @127.0.0.1 -p 55555 google.de    

; <<>> DiG 9.16.8 <<>> @127.0.0.1 -p 55555 google.de
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 2256
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;google.de.                     IN      A

;; ANSWER SECTION:
google.de.              300     IN      A       172.217.23.99

;; Query time: 40 msec
;; SERVER: 127.0.0.1#55555(127.0.0.1)
;; WHEN: Tue Dec 22 20:42:10 CET 2020
;; MSG SIZE  rcvd: 63
```

Log entry in blocky's log: `[2020-12-22 20:42:10] DEBUG upstream_resolver: received response from upstream answer=A (172.217.23.99) client_ip=127.0.0.1 client_names=127.0.0.1 net=tcp+udp protocol=UDP question=A (google.de.) response_time_ms=40 return_code=NOERROR upstream=[2606:4700:4700::1111]:53`

I would say, it works. I tested it locally, without docker, maybe there is a docker network issue?

**Comment by 0xERR0R** [comment]
tried with docker, I get ` ERROR server: error on processing request: dial udp [2606:4700:4700::1111]:53: connect: cannot assign requested address`

**Comment by NoctivagusObitus** [comment]
All right. I think there is at least some miss configuration on my side and maybe the real issue is fixed in the development version.

explanation:
first of all i need to distinguish between upstream and conditional forwarding.
the easy one is the conditional forwarding. i had issues with this one as well but now i can enter an ipv6 address and it seems to work as intended (forwarding to my on link local ip through a vpn from within docker container).

for the general upstream of course my attempt to just use public google resolver from within docker was  stupid because it obviously uses a ipv6 GUA address which my docker container does not have configured and also docker is not doing any NAT64 so there was just no route... @0xERR0R  your statement that starting blocky on host is different from within the container helped here - thx
but then is the broken link local upstream resolver.
that one seems to come from another miss configuration by me. i had blockys upstream point at an dns server which itself had blocky set as upstream (i know, stupid - i was trying around). that seemed to generate the errors which is still better then a infinite loop of the same request but sadly the error was not that helpful. probably the dnsmasq just responded with an error at some point.

anyway that greatly helped my understanding and it seems to work now as intended (no errors). thanks a lot!
closing this one.
