### ISSUE TITLE
Unresolved color codes in windows console - binary 0.22

### ISSUE THREAD

**Issue by adamsewell** [0xERR0R/blocky#1204]
Version: 0.22
I'm seeing some odd output with version 0.22, and I believe it was present in 0.21 as well. See the example below. The command I'm using is just "blocky.exe -c blocky.yaml", if you need the config I can add that. Is there any way to resolve this? I'm also wondering if this is affecting my other issue with #1053 getting odd output than it was expecting.

```
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m      blacklist cache entries:
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m        babydomains: 137687 entries
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m        phishing: 48337 entries
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m        malware: 127327 entries
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m        blacklist: 22 entries
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m        ads: 190943 entries
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m        TOTAL: 504316 entries
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m      whitelist cache entries:
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m        ads: 392 entries
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m        TOTAL: 392 entries
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m -> caching:
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m      minTime = 10 minutes
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m      maxTime = 1 hour
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m      cacheTimeNegative = 30 minutes
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m      cache entries = 0
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m -> special_use_domains:
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m -> strict:
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m      timeout: 0 seconds
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m      strategy: parallel_best
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m      groups:
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m        default:
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m          - tcp+udp:192.168.64.1
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m listeners:
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m   DNS   = [53]
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m   TLS   = []
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m   HTTP  = []
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m   HTTPS = []
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m runtime information:
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m   numCPU =       2
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m   numGoroutine = 25
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m   memory:
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m     alloc =                10 MB
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m     heapAlloc =            10 MB
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m     sys =                  71 MB
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m     numGC =               413
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m Starting server
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m UDP server is up and running on address :53
←[0;97m[2023-10-15 22:41:31]←[0m ←[0;32m INFO←[0m←[0;1;34m server:←[0m TCP server is up and running on address :53
```

**Comment by kwitsch** [comment]
Output looks normal except for unresolved color codes.

Parts like `[0;97m[` are usual bash color codes.

How did you gather these Outputs (CMD, PowerShell, Bash, Logfile,...)?

**Comment by 0xERR0R** [comment]
Maybe "https://github.com/0xERR0R/blocky/blob/9f4929117720fa8a725fd2d84f54760beec83a3f/log/logger.go#L101C9-L101C9" doesn't work on windows? On linux it has some kind of TTY detection

**Comment by kwitsch** [comment]
> Maybe "https://github.com/0xERR0R/blocky/blob/9f4929117720fa8a725fd2d84f54760beec83a3f/log/logger.go#L101C9-L101C9" doesn't work on windows? On linux it has some kind of TTY detection

Should we add a config option to override the detection and enforce colorless output?

**Comment by 0xERR0R** [comment]
we should check if the autodetection on linux works. I'll try it out

**Comment by 0xERR0R** [comment]
If I set 'ForceFormatting' to false, I still get colors on linux if TTY is attached, so there is no difference.

Without TTY (for example docker): with "ForceFormatting = true", I get log output as Text. With "ForceFormatting = false", it is JSON.

**Comment by adamsewell** [comment]
> Output looks normal except for unresolved color codes.
> 
> Parts like `[0;97m[` are usual bash color codes.
> 
> How did you gather these Outputs (CMD, PowerShell, Bash, Logfile,...)?

Just ran blocky from an elevated PowerShell prompt, the copy and paste.

**Comment by kwitsch** [comment]
> Just ran blocky from an elevated PowerShell prompt, the copy and paste.

Could you test if setting an environment variable called `CLICOLOR` to the value `0` in the environment where you run blocky fixes the problem?

Since the underlaying logging library checks this variable it should disable the color codes in theory.

**Comment by kwitsch** [comment]
I cant reproduce the color problem under Windows 11.
Running blocky.exe in Cmd and PowerShell both produce the same output as the linux binary.

Only thing I could think of that maybe WSL translate the color codes on the fly(?) 🤔

@adamsewell do you have WSL enabled?

**Comment by adamsewell** [comment]
@kwitsch I do not have WSL enabled.

**Comment by kwitsch** [comment]
> @kwitsch I do not have WSL enabled. 

I've got an idea how to fix it but no idea how to test it.
Would you be willing to test it if I provide a binary for you?

**Comment by adamsewell** [comment]
Sure, I would be happy to.

**Comment by kwitsch** [comment]
> @kwitsch Sure, I would be happy to. 

@adamsewell great, I'll provide a binary in a few days and send it to you, when I'm back on my machine 🙂

**Comment by kwitsch** [comment]
@adamsewell current development version with added windows color fix inside [blocky.zip](https://github.com/0xERR0R/blocky/files/13259580/blocky.zip)  
Please report back if this fixes your problem.

**Comment by adamsewell** [comment]
@kwitsch That looks much better! Thanks.
