### ISSUE TITLE
Windows Server 2019, Docker Compose Setup: can't read config file

### ISSUE THREAD

**Issue by ZJohnAsZ** [0xERR0R/blocky#1210]
Hi, I am new to Docker, but read some of their documentation and on blocky's website doc to grasp the basics. Some CLI commands are a bit different since I am using docker on Windows Server and not Linux. I know the paths representation is also different, hence why I am a bit confused on what path I should use to define the volumes in the docker-compose.yml file. I tried all possibility to no avail. 

I am logged in as Administrator and it is added to the docker-users Group. I also tried to give full access to the blocky folder and its files to the docker-users Group to no avail either. 

Files Setup
![25 10 2023_15 08 08_REC](https://github.com/0xERR0R/blocky/assets/112823296/23a1ee37-e5b4-42ba-a2c6-cc36cfc3c04e)

config.yml (I put more than less to test lists 1 by 1 when I can finally start the container...)
*I don't think the problem is from the config file itself
Also using the command:
docker run --name blocky -v C:\blocky\config.yml:/app/config.yml -p 4000:4000 -p 53:53/udp spx01/blocky starts the container, but with an empty config.yml loaded.
![25 10 2023_15 36 47_REC](https://github.com/0xERR0R/blocky/assets/112823296/93879ebf-5059-4d5b-bb67-fd6b0529ff3d)

docker-compose.yml
![25 10 2023_15 11 43_REC](https://github.com/0xERR0R/blocky/assets/112823296/c470cdec-f948-4f99-b294-0dbf5ddb192b)
For the config.yml volume I tried:
  - C:\blocky\config.yml:/app/config.yml
  - $(pwd)/config.yml:/app/config.yml
  - ${pwd}/config.yml:/app/config.yml
  - %cd%/config.yml:/app/config.yml
  - $(pwd)\config.yml:/app/config.yml
  - ${pwd}\config.yml:/app/config.yml
  - %cd%\config.yml:/app/config.yml
  - ./config.yml:/app/config.yml
  - .\config.yml:/app/config.yml
  
When I "docker-compose up -d", I share it.
![25 10 2023_15 05 33_REC](https://github.com/0xERR0R/blocky/assets/112823296/fa83a3c5-0ebc-4105-b465-7f7428324779)

I am a bit lost, I don't know if the problem is a security/access rights, path or docker-compose.yml setup issue. Could someone help me or point me to some docs that I might've missed in my researches?

Anyone tried running Blocky in a Docker container on Windows/Windows Server?

My preferred method of setup would be through Docker Compose. Ultimately I try to fix this issue:
`FATAL unable to load configuration: can't read config file: open /app/config.yml: operation not permitted`
when I run the docker-compose.yml file I share.

Thank you.

**Comment by kwitsch** [comment]
`./config.yml:/app/config.yml`
Should be correct and work on my Windows 11.

It seems like some kind of security issue on the windows side.

Is it possible for you to test if the same command run through WSL result in the same behavior?

**Comment by ZJohnAsZ** [comment]
Thank you for the reply, I will try the WSL route of setting it up. On Windows Server 2019, I can only install WSL1 manually and I don't think I can use Docker Desktop since its implementation on WinServer can either be done with WSL2 (Server 2022) or with the Hyper-V/Container (Server 2019) features. So I would basically end up with using Docker and containers on Ubuntu Linux through Windows.

**Comment by kwitsch** [comment]
I'm absolutely not familiar with Windows servers to be honest.😅

If you need the OS for something windows related it would probably be easier to either use the windows binary or run a hyper-v Linux instance on top of it.
Docker under Windows got it's power through WSL2.
If you can't utilize that it won't be a good idea performance wise to use docker containers.


Last time I tried running docker containers on a windows server I ended up using a second server with Ubuntu(nested virtualization was disabled in this setup so using an hyper-v instanz on top of it wasn't an option). 🫣

**Comment by kwitsch** [comment]
@ZJohnAsZ just came across something while  researching a different problem: Do you have a windows user group `docker-users` and if yes has this group read permission on your config file?

**Comment by ZJohnAsZ** [comment]
@kwitsch 
Sorry for the delay, I had some problems with an Adaptec RAID to solve before continuing the blocky venture. XD

Yes, there is a docker-users group and I gave it read and write permissions on the blocky folder. 
I virtualized an eval version of windows server 2022 to test blocky with WSL2 and Docker Desktop. This is where I am at right now.
