### ISSUE TITLE
Blocky not returning SOA for domain with custom dns entries

### ISSUE THREAD

**Issue by Ulrar** [0xERR0R/blocky#1236]
Hi,

I've just lost quite a while figuring out why my cert-manager broke, and I finally tracked it (I think) to blocky not returning an SOA record for one of my domains that has custom dns entries.
All other domains do seem to work as expected, so I wonder if that's expected and if there's anything I can do to fix the SOA record ?

In the meantime I manually pointed the cert-manager pod to cloudflare's dns directly, to get certificates back which I guess is fine.
Thanks !

**Comment by kwitsch** [comment]
Am I getting your issue correct that you're using [Custom DNS](https://0xerr0r.github.io/blocky/v0.22/configuration/#custom-dns)  entries but like to keep SOA records from upstream?

Have you disabled the unmapped type filtering?  
By default these records are filtered and not forwarded upstream but you can configure the behavior.
```YAML
customDNS:
  filterUnmappedTypes: false
```

**Comment by Ulrar** [comment]
That's exactly it, figured I was missing something.

Thank you very much ! And thanks for the project, running this in a local k8s cluster and I was trying to figure out if I could get away with pihole or adguard or something else without needing a PVC, and this works great with a simple config map, love it
