### ISSUE TITLE
error importing "developer dan's host" (used in pihole)

### ISSUE THREAD

**Issue by ramarro123** [0xERR0R/blocky#1243]
hi, i am switching from pihole to blocky and i would like to use a list that i was using before that give me decent results.

the list is hosted here
https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt

linked from 
https://www.github.developerdan.com/hosts/

opening the list i can't see any "macroscopic" issue
the error in log say

 ERROR list_cache: parse error: line 335688: non resumable parse error: context deadline exceeded (Client.Timeout or context cancellation while reading body) count=335665 source=https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt

could be that the list is "too big"? any settings that i have to enable to use it?

**Comment by kwitsch** [comment]
Looks like a connection timeout.

Does this list work if you download it and use the local path in the blocky config?

**Comment by ramarro123** [comment]
[2023-11-14 17:35:37]  INFO list_cache: import succeeded count=429430 source=file:///app/docker_cfg/ads-and-tracking-extended.txt

it actually worked in that way

any config to change the timeout?

**Comment by kwitsch** [comment]
At least in the current development version it is:
```YAML
blocking:
  loading:
    downloads:
      timeout: 5s
```
