### ISSUE TITLE
docker user

### ISSUE THREAD

**Issue by ramarro123** [0xERR0R/blocky#1247]
hi,

if i start docker using hte provided image, it seems that i am not able to start service because of grant of opening low port. (<1024)

again, not an expert, but if we use user = 100 this user is allowed to open priviledged port on the docker container?

thanks!

**Comment by kwitsch** [comment]
No the user id has no effect on this.  
You need `cap_net_bind_service=+ep`.  
There is an [official docker documentation](https://docs.docker.com/engine/security/rootless/#exposing-privileged-ports).  

Hope this helps. 🙂

**Comment by ThinkChaos** [comment]
If you can, I'd recommend making blocky listen on a higher port and using port mapping to get it to be accessible via the actual low ports on the host: `-p 53:<high-port>`
