### ISSUE TITLE
Rename Go symbols w/ abbreviations to use upper case

### ISSUE THREAD

**Issue by ThinkChaos** [0xERR0R/blocky#1260]
To follow the Go convention.

Example: `EcsResolver` -> `ECSResolver`

Inventory of known offenders:
- `EcsResolver` (and `New` func)
- `EdeResolver (and `New` func)`
- `FqdnOnlyConfig` (and `Config.FqdnOnly`)

See https://github.com/0xERR0R/blocky/pull/1007#discussion_r1398494486

**Comment by ThinkChaos** [comment]
Maybe also rename all `config.SomethingConfig` to just `config.Something` since that's similar to the repeat guideline of `config.ConfigSomething` -> `config.Something`.

**Comment by kwitsch** [comment]
> Maybe also rename all `config.SomethingConfig` to just `config.Something` since that's similar to the repeat guideline of `config.ConfigSomething` -> `config.Something`.

We literally have `config.Config` 😅. 
I'm a bit lost finding a name for it. 
Since it almost has no config values on it's own but holds all other config structs `Main` seems a bit of.  
Maybe `Base` ? 🤔


What about the `resolver` package?  
Almost everything later on looks like `resolver.SomethingResolver`.  
Isn't that exactly the same as in `config`?

**Comment by 0xERR0R** [comment]
> We literally have `config.Config` 😅. I'm a bit lost finding a name for it. Since it almost has no config values on it's own but holds all other config structs `Main` seems a bit of. Maybe `Base` ? 🤔
> 

Found some examples in go std lib:  list.List, ring.Ring and image.Image :)

I think config.Something is better than config.SomethingConfig. Regarding the resolver package: I was thinking to introduce sub packages for each resolver type, something like:

resolver/conditional/conditional.go with constructor function "New" instead of "NewConditionalResolver". In this case, we can put all files which belong to one resolver implementation and tests together. Any thoughts about it?

**Comment by kwitsch** [comment]
> Found some examples in go std lib:  list.List, ring.Ring and image.Image :)

Ok `config.Config` stays 👍

> I think config.Something is better than config.SomethingConfig. Regarding the resolver package: I was thinking to introduce sub packages for each resolver type, something like:
> 
> resolver/conditional/conditional.go with constructor function "New" instead of "NewConditionalResolver". In this case, we can put all files which belong to one resolver implementation and tests together. Any thoughts about it?

That sound great to me. 👍
There may be some challenges since some resolvers currently use unexposed functions of other resolver(files) if I remember correctly. 🤔

**Comment by 0xERR0R** [comment]
> That sound great to me. 👍 There may be some challenges since some resolvers currently use unexposed functions of other resolver(files) if I remember correctly. 🤔

IMHO, this is a problem. We should identify common functions and extract them. One resolver should not use "private" functions of another one.

**Comment by kwitsch** [comment]
> IMHO, this is a problem. We should identify common functions and extract them. One resolver should not use "private" functions of another one.

I could be wrong, need to verify it. 😅
Currently alle reside in the same package so technically private for all. 😉

I'm all in for it especially even splitting the resolver test suite up.
It currently contains nearly 400 tests which take long(even when run in parallel).

**Comment by ThinkChaos** [comment]
Agreed for `config.Config`!

I also like the idea of multiple packages in `resolvers/`. But please wait a bit before working on that cause I have a lot of big changes locally ATM so we'd get a lot of conflicts.

> IMHO, this is a problem. We should identify common functions and extract them. One resolver should not use "private" functions of another one.

One issue that comes to mind is `Bootstrap` currently has a tight dependency on `UpstreamResolver`, but from a quick look at the code I'm sure we can find other ways to make it work.

**Comment by kwitsch** [comment]
`config.RedisConfig` to `config.Redis` is part of #1271

**Comment by kwitsch** [comment]
@ThinkChaos is this issue completed since #1315 is merged?

**Comment by ThinkChaos** [comment]
Yeah I think most of the work is done, if we find any leftovers we can do it as we go.

Thanks for handling it!
