### ISSUE TITLE
Question: Possible to change domain on conditional-forwarding?

### ISSUE THREAD

**Issue by dmkif** [0xERR0R/blocky#128]
Hello all,

I am in the process of setting up an RPI cluster for my home network.  
In the process, I stumbled across this project. So far it makes a very good impression. In my network, the devices are supplied with IP addresses via DHCP from the FritzBox. This has turned out to be the most stable solution.  
That's why I also use conditional forwarding. 

I also have my own domain and would like to use it within the network for my devices, e.g. `laptop1.location.example.de`. Unfortunately, I cannot change the DNS suffix within the FritzBox (my router), which is why I am currently running a script that reads the device names from the FritzBox and then appends them with my domain (e.g. `location.example.de`) and then provides it to the currently used DNS server (Pihole) as a file. 

Now my question is: Is it possible to send all requests to` *.location.example.de` to the FritzBox and exchange the domain name? As an example, a request sent to Blocky `laptop1.location.example.de` is forwarded to the FritzBox as `laptop1.fritz.box`.

Many thanks for the help!

**Comment by 0xERR0R** [comment]
Hey,

hm, this is an interesting approach. Basically, this would be a "rewrite" of the domain -> "location.example.de" should be replaced with "fritz.box" and then routed via conditional forwarding to the FritzBox. It is not possible out-of-the-box, but I'll keep this issue for future releases.

I'm also using AVM FritzBox as a router and a custom domain for my raspberry pi, but I configured it as a "customDNS" configuration entry with pinned IP address.

Btw: DHCP in the FritzBox provides usually always the same IP address for one device, you can also "fix" the IP address for a particular device in the FritzBox web interface, in this case, FritzBox will always provide the same IP for the MAC address of the device.
