### ISSUE TITLE
[Doc] config `maxErrorsPerFile` is missing from documents

### ISSUE THREAD

**Issue by shizunge** [0xERR0R/blocky#1289]
In the [0.22 Release](https://github.com/0xERR0R/blocky/releases/tag/v0.22), https://github.com/0xERR0R/blocky/pull/986 added `maxErrorsPerFile`.

This config is missing from document https://0xerr0r.github.io/blocky/v0.22/configuration/
and the example config file https://0xerr0r.github.io/blocky/v0.22/config.yml

**Comment by ThinkChaos** [comment]
Yes `maxErrorsPerSource` is the newer version that means the same.  
Where did you find the `maxErrorsPerFile` mention so I can update it?

**Comment by ThinkChaos** [comment]
It was renamed in #998 so it could be re-used by the hosts file resolver.

I'll go ahead and close this since the docs are up to date and using the old option should still work (with a warning) thanks to [the migration](https://github.com/0xERR0R/blocky/blob/v0.22/config/blocking.go#L27).
