### ISSUE TITLE
Custom Page Display for Blocked Domains

### ISSUE THREAD

**Issue by kapilsingh421** [0xERR0R/blocky#1293]
I would like to raise an issue regarding domain blocking. Instead of displaying the default page when a domain is blocked, I want a custom page to be shown

**Comment by kwitsch** [comment]
You already could define a [custom IP](https://0xerr0r.github.io/blocky/v0.22/configuration/#block-type) as block type.

Therefore this can be achieved by hosting your custom page as a separate service and setting it's IP as block type.

**Comment by ThinkChaos** [comment]
Also note that this won't work with HTTPS (unless you have a root cert on each device), so in most cases, if the user visited the site in the past they'll just see a "bad cert" error.

**Comment by kwitsch** [comment]
What if we add a block type ` cname`  which forwards the request to another domain?


Wouldn't that fix the SSL issue? 🤔

**Comment by ThinkChaos** [comment]
CNAME won't do a HTTP redirect, so the hostname used for TLS is still the original one :slightly_frowning_face:

**Comment by 0xERR0R** [comment]
No, it won't work with cname record. Browser will still use https

**Comment by kwitsch** [comment]
Was thinking about something like: if the CNAME url has a valid certificate for itself and provides the same content on http and https it should work ... 🤔

But was just a quick idea... 😅

**Comment by ThinkChaos** [comment]
The browser will still do TLS cert verification with the blocked domain, not the one from CNAME. So it's just impossible to fix without a cert for the blocked domain.

**Comment by 0xERR0R** [comment]
Maybe we should drop this feature since over 90 percent of sites use https?

**Comment by ThinkChaos** [comment]
Didn't know about that, but looks like a non standard hack supported by only a couple DNS providers. So it's actually not a solution for us because it still uses a normal A record + web server, so needs a cert for the A record/blocked domain. For those DNS providers that's easy to get since they are the NS for the real domain, but that's not our case.

See https://support.constellix.com/support/solutions/articles/47000860091-http-redirection-record:
> When you create an HTTP redirection record, you’re actually making an A record that points to that web server

**Comment by kwitsch** [comment]
@ThinkChaos  Ah sorry didn't read it through. 😅
