### ISSUE TITLE
Netflix on firetv is blocked by default

### ISSUE THREAD

**Issue by runningman84** [0xERR0R/blocky#13]
I just discovered that Netflix on my firetv gets blocked. It is working on my Panasonic smart TV.

Obviously this is not a real big but in a pihole setup that would work just fine.

I would advise to have a default config which does not block popular services.

**Comment by 0xERR0R** [comment]
Hi Philipp,
blocky does not have "default config". There is an example config file in readme, but this only an example, each user should configure blacklists at own discretion. Example config contains the same list as pihole (as of end of 2019).
Which domain is being blocking and makes netflix unusable? Is this domain on a blacklist?

You could also try optional list from [anudeepND](https://github.com/anudeepND/whitelist) as whitelist, maybe this will help.
