### ISSUE TITLE
Improve per request log metadata

### ISSUE THREAD

**Issue by ThinkChaos** [0xERR0R/blocky#1307]
It would be nice to have something like a request ID being logged with each log that relates to a specific request to make tracing a request's path easier, and possible to discern logs from different requests.

Should pretty straightforward after logs automatically pickup the request's log via a context (see #1264).

Also in the server we should log how we received the request (TCP/UDP/..., the port, etc.).

**Comment by 0xERR0R** [comment]
👍 that sounds good. We could either generate a unique id (maybe not so long as uuid) or take a message ID from the DNS request.

**Comment by ThinkChaos** [comment]
Done in #1356
