### ISSUE TITLE
Question/Feature request: Conditional forwarding of all local queries 

### ISSUE THREAD

**Issue by schlamar** [0xERR0R/blocky#133]
Is it possible that all local queries are forwarded to the local DHCP server (Fritz Box in my case)?

So that it works like that

    nslookup printer -> via 192.168.178.1
    nslookup printer.fritz.box -> via 192.168.178.1
    nslookup printer.de  -> via Upstream DNS

With Pi-Hole I could query local devices without a local domain name.

**Comment by 0xERR0R** [comment]
I'm not sure, how it should work: you can configure different DNS servers for special domains: for example 192.168.178.1 for "fritz.box" and xx.yy.zz. for "local.lan". In this case a simple query for "printer" would ask the first one? Or all defined DNS and return first positive result?

**Comment by schlamar** [comment]
Maybe a default entry above mappings?

Am Di., 16. Feb. 2021 um 17:08 Uhr schrieb Dimitri Herzog <
notifications@github.com>:

**Comment by 0xERR0R** [comment]
This could be an option. Another problem is: dot character is allowed in the host name. What is about the query "printer.de"? It could be also a local network name (Full-qualified: printer.de.fritz.box), so in this case it is ambiguous.

The simplified logic could be: if query name does not contain a dot -> use default conditional resolver (e.g. router), else use upstream DNS. This would work for the most cases, but not for special edge cases.

I'm not sure, if this is a good way to achieve the desired result... My personal opinion: it is always better to use full qualified names, but I understand the use case.

**Comment by schlamar** [comment]
Weird, after a process restart it works as expected.

nslookup printer returns correct IP address + printer.fritz.box as name.

I'll observe this for a while and close this if it keeps working as
expected.

Am Di., 16. Feb. 2021 um 17:28 Uhr schrieb Dimitri Herzog <
notifications@github.com>:

**Comment by 0xERR0R** [comment]
Are you sure, you are receiving a response from blocky? Which OS? It shouldn't work. Just tried under linux to lookup my nas with only the hostname - doesn't work (as expected)

**Comment by schlamar** [comment]
Ah, Linux and Windows automatically get the DNS suffix search from my Fritz Box (probably via DHCP?!) and append this to my DNS queries. In Linux this is in /etc/resolv.conf. On Windows you can see it with `ipconfig /all`.

Not sure why this wasn't working before. 

So this can be closed I guess :-)

**Comment by 0xERR0R** [comment]
I use DHCP (from Fritzbox) on linux and it doesn't work for me. I guess, this is some "windows magic" ;)

**Comment by schlamar** [comment]
Nope, this did work on Linux, too. Tried Debian 10 on Raspberry.

Dimitri Herzog <notifications@github.com> schrieb am Di., 16. Feb. 2021,
21:47:
