### ISSUE TITLE
v0.23 broke `blocky blocking disable` 

### ISSUE THREAD

**Issue by rahilarious** [0xERR0R/blocky#1336]
when I ran `blocky blocking disable`

blocky 0.22 responded:
> [2024-02-10 02:55:02]  INFO OK

blocky 0.23 responds:
> Error: response NOK, 400 Bad Request group '' is unknown

works totally fine in 0.23 when I run `curl localhost:4000/api/blocking/disable`

CC: @ThinkChaos  @0xERR0R @BenMcH

**Comment by BenMcH** [comment]
I found the issue buried in quite a large PR from September :smile: PR is up and should be able to be reviewed by a maintainer when they have the time :rocket:

**Comment by rahilarious** [comment]
> I found the issue buried in quite a large PR from September 😄 PR is up and should be able to be reviewed by a maintainer when they have the time 🚀

whoa, that was quick! Thank you. Hopefully will be merged soon
