### ISSUE TITLE
Fetch configuration YAML from URL

### ISSUE THREAD

**Issue by nikolicjakov** [0xERR0R/blocky#1342]
It would be nice if we could centralize dns configuration by exposing configuration via web server.

Once blocky continer is started (or-restarted) it would pull configuration file from web URL defined in environment variable.

This would enable us to manage all of our DNS server in single place there is no need to create configuration file on each host machine. And updates in configuration could be delivered faster.

**Comment by ThinkChaos** [comment]
This should be relatively easy to do with a custom container image.

**Comment by nikolicjakov** [comment]
@ThinkChaos true it is easy but that requires me to do re-build each time new release has been published. Would it not be beneficial to the community if something like this would came out of the box with official docker release..

**Comment by ThinkChaos** [comment]
I think this kind of feature is better done by your infra management. Anyways if you have a bunch of blocky instances you'll need to restart them, so need tooling in place for management and should use that for configs.  
And if it were done in blocky, my initial reaction is something in the API would be a better fit.

**Comment by adamshand** [comment]
Came looking to see if this was supported.  I'd love to see this supported natively by blocky.
