### ISSUE TITLE
mDNS / AirPlay not working

### ISSUE THREAD

**Issue by lucasteligioridis** [0xERR0R/blocky#1343]
Hi,

I've just switched to Blocky from Adguard and noticed that my AirPlay (Youtube atm I've been testing) doesn't work via Blocky. 
I did have this issue with my Adguard instance and needed to do something like this to fix it in Adguard (setting "in-addr.arpa" to my router DNS):

<img width="334" alt="Screenshot 2024-01-20 at 10 36 09 am" src="https://github.com/0xERR0R/blocky/assets/20388321/9455eca8-8d49-436b-b3d3-79ae0a97b089">

<img width="1158" alt="Screenshot 2024-01-20 at 10 36 28 am" src="https://github.com/0xERR0R/blocky/assets/20388321/b61f9942-87dc-4627-88e5-0f43d3b997f3">

Keeping in mind I have Adguard/Blocky running on a Kubernetes cluster in a pod/container, which is where I think half the issue likes and why I needed to do such a thing.

I tried to replicate this config by following the docs but not sure if I have it all correct or whether its fully possible? I've tried so many different permutations and have no idea how to get this working properly. Any guidance on this would be fantastic!

**Comment by kwitsch** [comment]
Could you post your configuration file?

It seems that you are missing a conditional config entry but it's hard to say without the underlying config.

**Comment by lucasteligioridis** [comment]
Sorry to even make this! I was being plagued with this issue with Adguard and worked around it with the above config... the root issue was some config in my unifi network relating to IDS/IPS and just how DNS was configured. 

Blocky working as intended now with AirPlay mDNS all good! Thank you and my bad about raising this! (I had my head stumped on this issue for weeks, classic that I resolve it the day I raise an issue)
