### ISSUE TITLE
Various issues with custom DNS entries

### ISSUE THREAD

**Issue by schlamar** [0xERR0R/blocky#139]
- You cannot specify IPv4 and IPv6 address for one host.
- ~~Host without suffix doesn't work: e.g. when configuring test: 192.168.181.2 you don't get a result for nslookup test (only for queries with suffix, e.g. my.test).~~
- Reverse DNS doesn't work, nslookup 192.168.181.2 should return test for the configuration `test: 192.168.181.2`

**Comment by 0xERR0R** [comment]
I tested with following config:
```yaml
customDNS:
  mapping:
    test: 122.122.122.122
```

If I execute `dig @127.and the third point: Y0.0.1 test`, I get `test.                   3600    IN      A       122.122.122.122` as response

Regarding the first point: yes, you can only specify only one address. Typically, this is not a problem in a local network. But it is a valid point.
Regarding rDNS for custom entries -> This is a good idea

**Comment by schlamar** [comment]
> If I execute dig @127.0.0.1 test, I get test. 3600 IN A 122.122.122.122 as response

You are right. There is some unexpected behavior of nslookup on Windows. It always appends the DNS search suffix, so it did a test.fritz.box lookup instead of plain test. On Linux, it tries both versions if a domain is configured in /etc/resolve.conf. So in this case you get a result **and** NXDOMAIN. I guess always registering custom entries with suffix would be the best solution here, providing expected results on both platforms.

BTW, you can query on Windows without suffix by appending a dot (e.g. `nslookup test.`).
