### ISSUE TITLE
Blocky does not reverse host file entries for client name resolution

### ISSUE THREAD

**Issue by gspannu** [0xERR0R/blocky#1391]
Blocky does not seem to resolve requesting field: clientName (from IP address) even if the **entry exists in the etc/hosts** file.

e.g.
```
Blocky running on Debian 12 machine at IP address: 192.168.1.110 Port:53
The Debian machine /etc/hosts contains a few entries like
192.168.1.20 abc
192.168.1.21 xyz
192.168.1.22 def

```
From another machine on the network (say from 192.168.21), I request
`nslookup -debug bbc.com 192.168.1.110` or `dig @192.168.1.110 bbc.com`
the query log generated does not show the Client Name as xyz, it just shows the IP address in both 
`clientIP clientName` field names.

---
Shouldn't the `clientName` _field be resolved_ from `clientIP` **using the hosts entry records as priority**, 
and then use the config.yml definition of clientLookup (_if at all defined_)?

```
hostsFile:
  sources:
    - /etc/hosts

#clientLookup:
  #upstream: 192.168.1.1:53535  #dnsmasq running on Router

```

_Or have I got my wires crossed totally ?_

**Comment by kwitsch** [comment]
The host file maps IP to names. 
So a lookup for the name resolves to the IP. 

The client names are resolved IP to name with `in-addr.arpa`  requests. 

You could define custom client names directly in your [blocky config](https://0xerr0r.github.io/blocky/v0.23/configuration/#custom-client-name-mapping) if defining it through host files isn't explicitly required.
