### ISSUE TITLE
Black/White -> Allow/Deny

### ISSUE THREAD

**Issue by ewoks** [0xERR0R/blocky#1435]
It would be highly appreciated if we could replace `black` or `white` references with `deny` or `allow`, simply to disassociate black with always negative and white with always positive as many other software adapted.

I understand this might not be important for everyone, but there are definitely people who would appreciate it, so I hope this is possible.

**Comment by sci-phi** [comment]
Literally my first impression was shock that a new project could still be launched in this era with this regressive language.

**Comment by ThinkChaos** [comment]
There's an existing issue #307.
TL;DR most people agree it's just a matter of taking the time to update everything! See my latest comment there.

**Comment by 0xERR0R** [comment]
We had already a PR (https://github.com/0xERR0R/blocky/pull/349) and https://github.com/0xERR0R/blocky/issues/907 for reference

**Comment by ewoks** [comment]
Thanks a lot to everyone <3
