### ISSUE TITLE
Error : field denylists not found in type config.Blocking

### ISSUE THREAD

**Issue by developer-scogo** [0xERR0R/blocky#1449]
Hey Guys
I am a new blocky user, was trying documentation but could not get blocky running , getting this error.

Looks like i am missing a stupid thing. Can any one suggest, what needs to be changed ?

- Docker version
```
# docker run -v /root/blocky/config.yml:/app/config.yml -p 4000:4000 -p 53:53/udp spx01/blocky
[2024-04-16 04:43:32] FATAL unable to load configuration: wrong file structure: yaml: unmarshal errors:
  line 8: field denylists not found in type config.Blocking
#
```
- Binary Version
```
# ./blocky --config config.yml
[2024-04-16 04:42:59] FATAL unable to load configuration: wrong file structure: yaml: unmarshal errors:
  line 8: field denylists not found in type config.Blocking
#
```
- Config.yml (v1)
```
upstream:
  default:
    - 46.182.19.48
    - 80.241.218.68
    - tcp-tls:fdns1.dismail.de:853
    - https://dns.digitale-gesellschaft.ch/dns-query
blocking:
  denylists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  clientGroupsBlock:
    default:
      - ads
ports:
  dns: 53
  http: 4000
```

- Config.yaml (v2) 
  [Default Config file without any changes ](https://github.com/0xERR0R/blocky/blob/main/docs/config.yml)

**Comment by kwitsch** [comment]
If you are using a v0.23 binary of blocky the example config is here: https://github.com/0xERR0R/blocky/blob/v0.23/docs/config.yml

The header of the documentation also includes a version selection: https://0xerr0r.github.io/blocky/v0.23/

**Comment by ThinkChaos** [comment]
Maybe we should rename "main" to "dev" or something  in the docs. Try to make it clearer if you don't have the context about branch names.  
Also I didn't look at how it's ordered or if we can configure that but "main" is the first entry in the versions dropdown, so maybe we can get it last so the easy path of "hover + click" gets you to the latest release.

**Comment by kwitsch** [comment]
Since "main" is technically "pre-release" it could indeed be a bit confusing. 

Besides changing its name we should add an option "latest" to the drop-down. 
Even if it's technically the same as choosing the latest version It may make the selection for inexperienced users a bit easier.

**Comment by developer-scogo** [comment]
Thank you guys , your suggestion works
