### ISSUE TITLE
Log file location on mac/brew

### ISSUE THREAD

**Issue by dabeeeenster** [0xERR0R/blocky#1451]
First up thanks for an amazing tool! I know brew is a third party thing but I'm trying to find the log file location when running blocky on arm MacOS via brew and coming up empty. Does it log anywhere?! If so where?

**Comment by kwitsch** [comment]
If I'm not mistaken we only log to the console (except query logs) so it should be easy to pipe it to any other program or file. 

I'm only running it in containers where the engine takes care of logs so please correct me if I'm wrong.

**Comment by ThinkChaos** [comment]
Based on [the formula](https://github.com/Homebrew/homebrew-core/blob/965866d5b52f610d03037dc3ec5033889b537e4c/Formula/b/blocky.rb#L32-L36), it seems a launchd service is defined. I know launchd can write stdout/err to files, so you could use that. Though IDK how that would be achieved with the homebrew service.

And maybe the "Console" app already has the logs in there but I think that might require the app/blocky to use a special os_log system which IDK if Go does but blocky definitely doesn't.

Haven't used macOS in a while so take all of this with a grain of salt :)
