### ISSUE TITLE
question: *multiple* blocky *same* promethus *multiple* grafana dashboards

### ISSUE THREAD

**Issue by bcookatpcsd** [0xERR0R/blocky#1470]
This may be a me problem.. 

(I'm good with anything being incomplete or incorrect..) 

https://grafana.com/grafana/dashboards/13768-blocky/ - I think this is the blocky dashboard.. 

![image](https://github.com/0xERR0R/blocky/assets/55087301/3579da2a-0ba8-4b2f-ad0d-750e53769cfd)

Where do I tell the dashboard what prometheus job_name to use.. 

(or is that not how it works?) 

I got one dashboard working.. but I don't see where I told it to use which blocky target.. and I don't seem to be able to.. 

If I wanted to have a single prometheus and grafana work with multiple blocky.. is that not possible? 

First dashboard worked, but second dashboard is the same as the first.. 

Thank you in advance.

**Comment by bcookatpcsd** [comment]
Looking through the json of the 13768.. 

"expr": "sum(up{job=\"blocky\"})",

I tried making one blocky0245 and the other blocky48247

didn't seem to do anything..

**Comment by bcookatpcsd** [comment]
grafana config:
```
[panels]
disable_sanitize_html = true
```

docker env:
```
GF_PANELS_DISABLE_SANITIZE_HTML=TRUE
```

if I put a prometheus exporter on each blocky.. then I just have to add the exporter as a datasource, then I can have multiple dashboards 

![image](https://github.com/0xERR0R/blocky/assets/55087301/32f0a1d0-2f7b-4e14-add7-e8de2009bd56)

**Comment by mschirrmeister** [comment]
What do you expect to get by doing `sum(up{job="blocky01"})`? You will get a straight line with the value of `1`.

Why do you want for each blocky instance an own dashboard? All in one might be more helpful, which works out of the box.

The blocky provided dashboard is using the variable `$job` which has the query `label_values(blocky_blocking_enabled,job)`. You can see that in the setting of the dashboard. That means you should by default see data from all your instances. If you don't see all, do you maybe have modified the dashboard?

If you do not use the variable in the query in your panel, you will also get **everything**. For example, if you use a query like this `sum(rate(blocky_query_total[5m])) * 60`, you will get the data for this metric, no matter what server it comes from.

If you really want to filter, you can either define your own variables and use those, or you filter in the queries directly.

For example, 

create a variable `myjob` like this
```
label_values(blocky_blocking_enabled{job=~"blocky01|blocky02"},job)
```
and then create the following query
```
sum(rate(blocky_query_total{job=~"$myquery"}[5m])) * 60
```

Or if you want to create a panel with a custom filter, create a query like this.
```
sum(rate(blocky_query_total{job=~"blocky01|blocky02"}[5m])) * 60
```

**Comment by bcookatpcsd** [comment]
![image](https://github.com/0xERR0R/blocky/assets/55087301/28945e93-d301-4a2c-88de-793f76e79ec5)

Nothing looks glaringly wrong.. I did want to ask questions about the 'request duration' (upstream)

Is that the time from the various conditional and the upstream combined? or just the upstream and nothing to do with the conditionals?

**Comment by niouniou49** [comment]
sorry but i dont see what change i should do for the buttons to appear properly.
I have modified the grafana config file 'grafana.ini' with adding ;disable_sanitize_html = true
<img width="982" alt="Screenshot 2024-05-16 at 13 54 23" src="https://github.com/0xERR0R/blocky/assets/72173152/e1d66503-5f04-4be6-9152-2c17f9644944">
but not effect, i still have the same issue with no buttons but text... all the rest works well
some more help required please
