### ISSUE TITLE
Feature Request : Allow to set database table name in config file

### ISSUE THREAD

**Issue by ksingh-scogo** [0xERR0R/blocky#1474]
Hi Blocky Maintainers

Love blocky as its sleek, lightweight,  ultra simple to use and written in GO. Thanks for building this project.

Would like to explore a new use case where i want to run multiple instances of blocky and store the query logs for each instance in Postgresql database. Currently each blocky instance requires its own separate database, that contains just one table `log_entries`. So for 10 instances of blocky, one will end up having 10 databases each with 1 table.

I was wondering if there could be a smarter way to do this, which is allowing to set table name in config file , so that multiple instances of blocky could use a single database, separated by the table name.

If this make sense, we would like to submit a PR for your review and merge in main 

@0xERR0R @kwitsch

**Comment by 0xERR0R** [comment]
The table `log_entries` has a column "hostname" which basically contains the hostname of the machine/container which runs blocky. This field is missing in the documentation. You can use the same database for all 10 installations, just use the column to distinguish the records

**Comment by ksingh-scogo** [comment]
Thanks @0xERR0R this was useful and make sense to use the way you described.

**Comment by kwitsch** [comment]
@ksingh-scogo if you run your setup in a cluster environment and want your blocky containers to keep the same name after restart/rebuild, you could mount `/etc/hostname` into the container to act as hostname source.
