### ISSUE TITLE
sslbump option for TLS 1.3 encrypted SNI scenarios

### ISSUE THREAD

**Issue by mrbluecoat** [0xERR0R/blocky#1485]
Does blocky support native SSL decryption or is a separate SSL termination tool like SSLsplit needed?

**Comment by ThinkChaos** [comment]
For anyone finding this in the future, the answer is yes.
See [SSL certificate configuration (DoH / TLS listener) docs](https://0xerr0r.github.io/blocky/latest/configuration/#ssl-certificate-configuration-doh-tls-listener)
