### ISSUE TITLE
Feature Request: DNS cloaking rules 

### ISSUE THREAD

**Issue by bcookatpcsd** [0xERR0R/blocky#1486]
Any thoughts if it is currently possible to implement this:

DNSCrypt/dnscrypt-proxy/blob/master/dnscrypt-proxy/example-cloaking-rules.txt

www.google.*             forcesafesearch.google.com

www.google.com/supported_domains

Possibly customDNS.. 

Thank you in advance.

**Comment by ThinkChaos** [comment]
Relevant discussion: #1596
