### ISSUE TITLE
Improve API to allow for external-dns (DDNS) integration

### ISSUE THREAD

**Issue by onedr0p** [0xERR0R/blocky#1487]
Hi 👋🏼 

I came across an interesting use-case for blocky. I would love to have [external-dns](https://github.com/kubernetes-sigs/external-dns) push records to blocky using DDNS.

external-dns currently supports writing a [webhook](https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/webhook-provider.md) to integrate services that are not included by default. Outside the original ask of supporting DDNS, the webhook is something I could look at implementing since it doesn't look that hard to create a webhook. Someone [wrote one for adguard home](https://github.com/muhlba91/external-dns-provider-adguard) and it looks pretty easy to implement given Blocky's API was improved.

I'll try to post a follow-up with what is needed from the API.

Thanks!

**Comment by DerRockWolf** [comment]
If I got it correctly, you essentially want blocky as a target for external-dns.

With the current architecture of blocky this is AFAIK impossible. Blocky's configuration is declarative and blocky is entirely stateless.

However, you could probably achieve this, without needing to extend or change blocky, by utilizing the [`hosts-file`](https://0xerr0r.github.io/blocky/latest/configuration/#hosts-file) feature. The webhook could then create a hosts file and save it at a persistent location where blocky can then read & refresh it from.

**Comment by onedr0p** [comment]
It would just be dynamically inserting DNS records, there wouldn't need to be any state on blocky side since external-dns runs at a given interval (I have it set to run every minute with their other providers) 

However I don't have a use-case for this right now so I'll go ahead and close the issue.
