### ISSUE TITLE
since V0.24 - error of connection to dns (unbound) every 15 min

### ISSUE THREAD

**Issue by niouflex49** [0xERR0R/blocky#1501]
since the upgrade in version 0.24, I have errors every 15min (like 16 errors). Its like networks connectivity down 3sec every 15 min
when downgrade to version 0.23 , errors disapeared.

**Comment by kwitsch** [comment]
Could you set the log level to debug and provide a log snippet around the errors.

**Comment by niouflex49** [comment]
for the moment I downgraded as logs show no errors ... but still few in the grafana dashboard..
do you have a method for upgrading properly from 0.23 to 0.24 in a Debian linux . I just dowloaded the 0.24 and replace the 0.23, other stuff to do? or another method.

**Comment by niouniou49** [comment]
[log error.txt](https://github.com/0xERR0R/blocky/files/15503390/log.error.txt)

here are logs around when 16 errors appeared in grafana
<img width="540" alt="Screenshot 2023-08-30 at 15 51 46" src="https://github.com/0xERR0R/blocky/assets/72173152/9b95cd6b-4759-4a5b-9056-aef822f57224">

**Comment by niouniou49** [comment]
> Could you set the log level to debug and provide a log snippet around the errors?
log error
[log error.txt](https://github.com/0xERR0R/blocky/files/15503427/log.error.txt)
