### ISSUE TITLE
make build deletes local changes

### ISSUE THREAD

**Issue by moenodedev** [0xERR0R/blocky#1557]
I made local changes to config/config_enum.go to remove clientIP and clientName from the CSV log. make build deleted the changes.

**Comment by moenodedev** [comment]
go generate ./... caused the files to be reset.

**Comment by kwitsch** [comment]
As [the first line](https://github.com/0xERR0R/blocky/blob/main/config%2Fconfig_enum.go#L1) states that this behavior is intentional.

Your changes have to be done in another file.
