### ISSUE TITLE
Support for additional record types in `customDNS.zone`

### ISSUE THREAD

**Issue by Terrance** [0xERR0R/blocky#1587]
I'm running an internal CalDAV server and exposing its DNS records via Blocky, but ideally this would include a pair of `SRV` and `TXT` records and Blocky doesn't support either.

For reference, the records would look like this:

```
$ORIGIN example.com.
_caldavs._tcp	IN	SRV	0 5 443 cal.example.com.
_caldavs._tcp	IN	TXT	"path=/"
_carddavs._tcp	IN	SRV	0 5 443 cal.example.com.
_carddavs._tcp	IN	TXT	"path=/"
```

**Comment by kwitsch** [comment]
Blocky supports those records through zone file syntax as described in [Custom DNS](https://0xerr0r.github.io/blocky/latest/configuration/#custom-dns) section.

**Comment by Terrance** [comment]
The relevant config looks like this:

```yaml
customDNS:
  zone: |
    $ORIGIN example.com.
    ; ...other names...
    cal			IN	CNAME	box
    box			IN	A	192.168.1.1
    _caldavs._tcp	IN	SRV	0 5 443 cal.example.com.
    _caldavs._tcp	IN	TXT	"path=/"
    _carddavs._tcp	IN	SRV	0 5 443 cal.example.com.
    _carddavs._tcp	IN	TXT	"path=/"
```

When queried, no records are returned:

```
$ dig _caldavs._tcp.example.com srv +noall +answer
(nothing)
```

And on blocky's stderr:

> [2024-08-26 16:26:25] ERROR error on processing request:unsupported customDNS RR type *dns.SRV client_ip=127.0.0.1 question=*** (_*******._***.*******.***.) req_id=90478e4f-a5d3-49b5-a9a4-07e742619856

This is using [blocky 0.24 on Arch Linux](https://aur.archlinux.org/packages/blocky-bin).

**Comment by Terrance** [comment]
This looked easy enough to add support for, so I've opened PR #1588 which seems to work for me.
