### ISSUE TITLE
Segmentation fault on TCP request with UDP fallback

### ISSUE THREAD

**Issue by schlamar** [0xERR0R/blocky#162]
Blocky is crashing occasionally since update to v0.13:

    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x69d45b]
    goroutine 23183 [running]:
    github.com/miekg/dns.(*Client).Dial(0x0, 0xc000694210, 0x11, 0xaed7a0, 0xb675c0, 0xc0008215e0)
            /home/runner/go/pkg/mod/github.com/miekg/dns@v1.1.40/client.go:87 +0x5b
    github.com/miekg/dns.(*Client).Exchange(0x0, 0xc000212120, 0xc000694210, 0x11, 0x0, 0x0, 0x0, 0x0)
            /home/runner/go/pkg/mod/github.com/miekg/dns@v1.1.40/client.go:130 +0x73
    blocky/resolver.(*dnsUpstreamClient).callExternal(0xc00174c480, 0xc000212120, 0xc000694210, 0x11, 0xc0000a1e00, 0xc000694960, 0x16, 0x0, 0x0)
            /home/runner/work/blocky/blocky/resolver/upstream_resolver.go:130 +0x26b
    blocky/resolver.(*UpstreamResolver).Resolve(0xc000484400, 0xc0005271a0, 0xc47008, 0xc0001baaa4, 0xc47008)
            /home/runner/work/blocky/blocky/resolver/upstream_resolver.go:175 +0x236
    blocky/resolver.resolve(0xc0005271a0, 0xc000033c80, 0xc0005272c0)
            /home/runner/work/blocky/blocky/resolver/parallel_best_resolver.go:140 +0x42
    created by blocky/resolver.(*ParallelBestResolver).Resolve
            /home/runner/work/blocky/blocky/resolver/parallel_best_resolver.go:81 +0x3ca

Maybe related to (though this happened 30 minutes earlier).

    ERROR server: error on processing request: resolution was not successful, errors: [dial tcp: i/o timeout dial tcp: i/o timeout]

**Comment by 0xERR0R** [comment]
Could you please share your configuration (upstream resolver part)?

**Comment by schlamar** [comment]
upstream:
    # these external DNS resolvers will be used. Blocky picks 2 random resolvers from the list for each query
    # format for resolver: [net:]host:[port][/path]. net could be empty (default, shortcut for tcp+udp), tcp+udp, tcp, udp, tcp-tls or https (DoH). If port is empty, default port will be used (53 for udp and tcp, 853 for tcp-tls, 443 for https (Doh))
    externalResolvers:
        - tcp-tls:1.1.1.1  # Cloudflare
        - tcp-tls:dot.ffmuc.net
        - tcp-tls:8.8.8.8  # dns.google
        - tcp-tls:dns.digitale-gesellschaft.ch

**Comment by 0xERR0R** [comment]
I could reproduce it: this error occurs on TCP requests if configured TCP-TLS resolver has a network error. In this case blocky tries to repeat the query with UDP, which is of course not available for TCP-TLS resolver
