### ISSUE TITLE
DoH server support

### ISSUE THREAD

**Issue by runningman84** [0xERR0R/blocky#17]
It would be cool if blocky would be able to serve as a DoH server using a k8s ingress.

This could be configured in firefox as a custom resolver:
https://blog.mozilla.org/blog/2020/02/25/firefox-continues-push-to-bring-dns-over-https-by-default-for-us-users/

**Comment by 0xERR0R** [comment]
The main purpose of blocky is to provide a DNS server in a local network with ad-blocking and caching of DNS queries. This should improve speed and therefore, blocky can serve DNS on UDP port. In a local network this should be no problem -> nobody can read your DNS traffic.
But I see a use case to use blocky as private DNS server in a cloud. In this case it would be really nice to have a secure channel to the DNS resolver.
Blocky has already a HTTP server running, currently only for Prometheus and pprof. In future, I would like to create a simple web interface for example to disable and enable blocking. I think, it would be not a big effort to provide a DNS endpoint over HTTP. I would externalize SSL Handling and certificate renewal to external applications (Nginx, Traefik etc), so the basic idea is only to implement DNS over HTTP and use blocky behind reverse proxy with SSL certificate
