### ISSUE TITLE
Use correct Base64 decoding to make DoH really work

### ISSUE THREAD

**Issue by tjay** [0xERR0R/blocky#176]
Hi,

in https://github.com/0xERR0R/blocky/blob/30bde1614c15fe95cf28c3cb269045f63d3a2c8f/server/server_endpoints.go#L45

**_base64.StdEncoding_** is used but **_base64.RawURLEncoding_** should be used.

https://tools.ietf.org/html/rfc8484#section-4.1 ( base64url: https://tools.ietf.org/html/rfc4648#section-5 )

sample query:

`AAABAAABAAAAAAABA3d3dwVhcHBsZQNjb20AABwAAQAAKQIAAAAAAABWAAwAUgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA`

**Comment by 0xERR0R** [comment]
Hi, good catch, thanks!
