### ISSUE TITLE
no means to set what IP to listen on

### ISSUE THREAD

**Issue by VVelox** [0xERR0R/blocky#196]
There appears to be no means to specify what IPs to listen on.

This is especially important if using BIND or the like to serve up local addresses on a network. It prevents running them both on the same VM, machine, etc.

**Comment by 0xERR0R** [comment]
You can define the listening address with the "port" parameter.

Example:

port: 192.168.178.29:53

**Comment by VVelox** [comment]
Okay. Awesome. Just tested and that does work. Thanks!

I'll get a PR submitted later for updating the config md as that is really not apparent from the doc as it just mentions port number and nothing about IP. :)

**Comment by 0xERR0R** [comment]
Yes, you're right, it was only documented in the config file (YAML): https://github.com/0xERR0R/blocky/blob/development/docs/config.yml#L116.

Thanks for your PR!
