### ISSUE TITLE
Disable Caching

### ISSUE THREAD

**Issue by cpressland** [0xERR0R/blocky#2]
This project looks like a perfect replacement for Stubby on my network. However, as I’d have dnsmasq forward requests to Blocky this would result in caching the response in two locations which is less than ideal.

Can a config option be added to disable caching within Blocky?

**Comment by JordanRushing** [comment]
Took a swing at this issue just for fun after coming across this package: https://github.com/JordanRushing/blocky/commit/aa859e63bff69e7cdac97d4bd8130878a401c91d

Definitely not settled on the implementation but I think this is the essence of what you're asking for.

**Comment by JordanRushing** [comment]
Had some fun and took a swing at this: https://github.com/JordanRushing/blocky/commit/aa859e63bff69e7cdac97d4bd8130878a401c91d

I'm not experienced with Golang but this was a good exercise. I don't consider this a final implementation at all but I think this is what you're asking for!

**Comment by 0xERR0R** [comment]
New configuration parameter (caching.maxTime) allows to override caching time from response (TTL). Set to -1 will disable caching for all queries
