### ISSUE TITLE
make config path/name configurable

### ISSUE THREAD

**Issue by billimek** [0xERR0R/blocky#20]
As a user of blocky,
I want to specify the path & name of the config file instead of expecting it to be hardcoded to `/app/config.yml`
So that I can use my own path design for config files

The reason behind this ask is that within kubernetes, leveraging a configMap to define the config file will result in the `/app` directory being clobbered when mounting the `config.yml` in that directory meaning that there won't be a blocky binary to run.  If we can define the config file to be in a non-shared path, that would be great!

**Comment by 0xERR0R** [comment]
config.yml must be in a working directory. Configurable path would be indeed really useful

**Comment by 0xERR0R** [comment]
Path to config can be specified with optional argument "--config <path_to_config_yml>"
