### ISSUE TITLE
Make the number of cached domains configurable

### ISSUE THREAD

**Issue by gregf** [0xERR0R/blocky#200]
I would like to be able to set the number of domains I want to keep in the cache. This would be useful for those of us with more memory to spare, or people with lower end systems as well.

**Comment by 0xERR0R** [comment]
It would make sense to have a "hard" limit in the cache. Technically, it means that oldest, but still valid entries will be removed. Currently, you can override the cache time by setting the `caching.maxTime` parameter (if not set, TTL from DNS answer will be used). Setting this parameter to a smaller amount of seconds will remove cached entries earlier, but the size of the cache is still dependent on the query count.
