### ISSUE TITLE
helm chart

### ISSUE THREAD

**Issue by billimek** [0xERR0R/blocky#21]
Hi, I made this into a [helm chart](https://github.com/billimek/billimek-charts/tree/master/charts/blocky) which is also hosted on [helm hub](https://hub.helm.sh/charts/billimek/blocky) for consumption in kubernetes workloads.

If you're interested in hosting it here, I'm happy to PR the necessary changes to have the chart hosted with associated github actions for linting, testing, and publishing the chart.

**Comment by 0xERR0R** [comment]
Hi Jeff, thanks for this work! I'm not sure, if this repo is the right place for helm chart configuration. Since I have no experience with k8s and helm, it would be nice, if you remain the maintainer and I link your repo in main readme of blocky. Is it OK for you?

**Comment by billimek** [comment]
Sure no problem!  I’ll PR an update to include a link and use that to close this issue.
