### ISSUE TITLE
Standalone stops working

### ISSUE THREAD

**Issue by asterriya** [0xERR0R/blocky#222]
Using standalone version and installed it on root folder with custom folder named blocky. Made setup using template on JSON example. And it's working fine but when I close SSH session console blocking ads stops working as Blocky too. How to make it work all the time? I even try to use my IP as main nameserver in hosts, but it didn't help. Any idea? Also, I don't understand how to use whitelist feature, and what format mus to be in whitelist.txt placed in folder?

**Comment by 0xERR0R** [comment]
How did you start blocky? It looks for me, like you just started `./blocky` from the shell and closed the shell. In this case, shell will kill all started child processes, this is correct. Try to start blocky with `nohup ./blocky` or use tmux. SystemD service would be a more preferable alternative (startup on restart etc)

**Comment by asterriya** [comment]
> How did you start blocky? It looks for me, like you just started `./blocky` from the shell and closed the shell. In this case, shell will kill all started child processes, this is correct. Try to start blocky with `nohup ./blocky` or use tmux. SystemD service would be a more preferable alternative (startup on restart etc)

Ok, I will try. Is it ok to install it in custom folder or must be installed on root only?  

And what about this question: Also, I don't understand how to use whitelist feature, and what format mus to be in whitelist.txt placed in folder? How to make it right?

**Comment by asterriya** [comment]
> SystemD service would be a more preferable alternative (startup on restart etc)

How to make that? I'm using Debian 9

**Comment by asterriya** [comment]
When I'm trying to use this cmd nohup ./blocky --config config.yml it's shows me next error: nohup: ignoring input and appending output to 'nohup.out'

**Comment by 0xERR0R** [comment]
> When I'm trying to use this nohup ./blocky --config config.yml it's shows me next error: nohup: ignoring input and appending output to 'nohup.out'
> 
> Same error when I'm trying to use nohup ./blocky

It is not an error, nohup creates a file "nohup.out", you can find blocky's output there (since you can now close you session and the process will run in the background)

**Comment by asterriya** [comment]
Here is my config

upstream:
  default:
    - 1.1.1.1
    - 1.0.0.1
	- 8.8.8.8
	- 8.8.4.4
blocking:
  # definition of blacklist groups. Can be external link (http/https) or local file
  blackLists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hosts
	  - https://badmojr.github.io/1Hosts/Xtra/hosts.txt
	  - https://hosts.oisd.nl/
  whiteLists:
    ads:
      - whitelist.txt
  # definition: which groups should be applied for which client
  clientGroupsBlock:
    # default will be used, if no special definition for a client name exists
    default:
      - ads
  blockType: zeroIp
  refreshPeriod: 240
  minTime: 5
  maxTime: 10
  prefetching: true
  port: 53
  disableIPv6: true

Showing next error
FATAL wrong file structure: yaml: line 5: found a tab character that violates indentation
FATAL wrong file structure: yaml: line 10: found a tab character that violates indentation
FATAL wrong file structure: yaml: line 11: found a tab character that violates indentation
  line 20: field minTime not found in type config.BlockingConfig
  line 21: field maxTime not found in type config.BlockingConfig
  line 22: field prefetching not found in type config.BlockingConfig
  line 23: field port not found in type config.BlockingConfig
  line 24: field disableIPv6 not found in type config.BlockingConfig

**Comment by asterriya** [comment]
And what about this question: Also, I don't understand how to use whitelist feature, and what format mus to be in whitelist.txt placed in folder? How to make it right?

**Comment by 0xERR0R** [comment]
> Ok, I will try. Is it ok to install it in custom folder or must be installed on root only? And I started it with this cmd ./blocky --config config.yml

You can copy blocky to a random folder (/opt/blocky) for example.

> 
> And what about this question: Also, I don't understand how to use whitelist feature, and what format mus to be in whitelist.txt placed in folder? How to make it right?

Just create a text file with a domain per line

**Comment by 0xERR0R** [comment]
> Here is my config
> 
> upstream:
> default:
> - 1.1.1.1
> - 1.0.0.1
> - 8.8.8.8
> - 8.8.4.4
> blocking:
> blackLists:
> ads:
> - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hosts
> - https://badmojr.github.io/1Hosts/Xtra/hosts.txt
> - https://hosts.oisd.nl/
> whiteLists:
> ads:
> - whitelist.txt
> clientGroupsBlock:
> default:
> - ads
> blockType: zeroIp
> refreshPeriod: 240
> minTime: 5
> maxTime: 10
> prefetching: true
> port: 53
> disableIPv6: true
> 
> Showing next error
> FATAL wrong file structure: yaml: line 5: found a tab character that violates indentation
> FATAL wrong file structure: yaml: line 10: found a tab character that violates indentation
> FATAL wrong file structure: yaml: line 11: found a tab character that violates indentation
> line 20: field minTime not found in type config.BlockingConfig
> line 21: field maxTime not found in type config.BlockingConfig
> line 22: field prefetching not found in type config.BlockingConfig
> line 23: field port not found in type config.BlockingConfig
> line 24: field disableIPv6 not found in type config.BlockingConfig

Config is in YAML format, indentation is very important. You can use this working example as template: https://raw.githubusercontent.com/0xERR0R/blocky/development/docs/config.yml

**Comment by asterriya** [comment]
Yes, I know, and I used it as an example. So I showed you my config, but it's shows error all the time. What's wrong? Can you fix and provide right template based on my, please?

And I need to place whitelist.txt in the same folder where is placed blocky bin, right?

**Comment by asterriya** [comment]
Here is my new template

upstream:
  # these external DNS resolvers will be used. Blocky picks 2 random resolvers from the list for each query
  # format for resolver: [net:]host:[port][/path]. net could be empty (default, shortcut for tcp+udp), tcp+udp, tcp, udp, tcp-tls or https (DoH). If port is empty, default port will be used (53 for udp and tcp, 853 for tcp-tls, 443 for https (Doh))
  # this configuration is mandatory, please define at least one external DNS resolver
  default:
    - 1.1.1.1
    - 1.0.0.1

# optional: use black and white lists to block queries (for example ads, trackers, adult pages etc.)
blocking:
  # definition of blacklist groups. Can be external link (http/https) or local file
  blackLists:
    ads:
      - https://dbl.oisd.nl/
      - https://badmojr.github.io/1Hosts/Xtra/hosts.txt

  # definition of whitelist groups. Attention: if the same group has black and whitelists, whitelists will be used to disable particular blacklist entries. If a group has only whitelist entries -> this means only domains from this list are allowed, all other domains will be blocked
  whiteLists:
    ads:
      - whitelist.txt
  # definition: which groups should be applied for which client
  clientGroupsBlock:
    # default will be used, if no special definition for a client name exists
    default:
      - ads

  # which response will be sent, if query is blocked:
  # zeroIp: 0.0.0.0 will be returned (default)
  # nxDomain: return NXDOMAIN as return code
  # comma separated list of destination IP adresses (for example: 192.100.100.15, 2001:0db8:85a3:08d3:1319:8a2e:0370:7344). Should contain ipv4 and ipv6 to cover all query types. Useful with running web server on this address to display the "blocked" page.
  blockType: zeroIp
  # optional: automatically list refresh period in minutes. Default: 4h.
  # Negative value -> deactivate automatically refresh.
  # 0 value -> use default
  refreshPeriod: 60

# optional: configuration for caching of DNS responses
caching:
  # amount in minutes, how long a response must be cached (min value).
  # If <=0, use response's TTL, if >0 use this value, if TTL is smaller
  # Default: 0
  minTime: 5
  # amount in minutes, how long a response must be cached (max value).
  # If <0, do not cache responses
  # If 0, use TTL
  # If > 0, use this value, if TTL is greater
  # Default: 0
  maxTime: -1
  # Max number of cache entries (responses) to be kept in cache (soft limit). Useful on systems with limited amount of RAM.
  # Default (0): unlimited
  maxItemsCount: 1000000
  # if true, will preload DNS results for often used queries (default: names queried more than 5 times in a 2 hour time window)
  # this improves the response time for often used queries, but significantly increases external traffic
  # default: false
  prefetching: true
  # amount in minutes, prefetch track time window
  # default: 120
  prefetchExpires: 120
  # name queries threshold for prefetch
  # default: 5
  prefetchThreshold: 5
  # Max number of domains to be kept in cache for prefetching (soft limit). Useful on systems with limited amount of RAM.
  # Default (0): unlimited
  prefetchMaxItemsCount: 0

# optional: configuration of client name resolution
clientLookup:
  # optional: this DNS resolver will be used to perform reverse DNS lookup (typically local router)
  upstream: udp:74.119.192.13
  # optional: some routers return multiple names for client (host name and user defined name). Define which single name should be used.
  # Example: take second name if present, if not take first name
  singleNameOrder:
    - 2
    - 1

# optional: write query information (question, answer, client, duration etc) to daily csv file
queryLog:
  # directory (should be mounted as volume in docker)
  dir: /logs
  # if true, write one file per client. Writes all queries to single file otherwise
  perClient: true
  # if > 0, deletes log files which are older than ... days
  logRetentionDays: 7

# optional: DNS listener port and bind ip address, default 53 (UDP and TCP). Example: 53, :53, 127.0.0.1:53
port: 53
# optional: use this DNS server to resolve blacklist urls and upstream DNS servers (DOH). Useful if no DNS resolver is configured and blocky needs to resolve a host name. Format net:IP:port, net must be udp or tcp
bootstrapDns: tcp:1.1.1.1
# optional: Drop all AAAA query if set to true. Default: false
disableIPv6: false
# optional: Log level (one from debug, info, warn, error). Default: info
logLevel: info
# optional: Log format (text or json). Default: text
logFormat: text
# optional: log timestamps. Default: true
logTimestamp: true

But blocky still showing me next error:
[2021-06-23 22:57:54]  WARN net prefix udp is deprecated, using tcp+udp as default fallback
[2021-06-23 22:57:54]  WARN net prefix tcp is deprecated, using tcp+udp as default fallback
[2021-06-23 22:57:54] FATAL wrong file structure: yaml: unmarshal errors:
  line 51: field maxItemsCount not found in type config.CachingConfig
  line 58: field prefetchExpires not found in type config.CachingConfig
  line 61: field prefetchThreshold not found in type config.CachingConfig
  line 64: field prefetchMaxItemsCount not found in type config.CachingConfig

**Comment by asterriya** [comment]
Please help me and provide fixed config based on my template that I sent recent.
Also, if you can please provide how must be looked template for custom blocklist.txt and whitelist.txt
