### ISSUE TITLE
make log to disk optional

### ISSUE THREAD

**Issue by onedr0p** [0xERR0R/blocky#23]
I use Loki and Promtail to gather logs in my Kubernetes cluster which gather logs from the containers stdout.

For me I don't need to logs being stored on disk unless there is a certain need Blocky uses it for.

**Comment by 0xERR0R** [comment]
You can just omit "queryLog" configuration part. In this case blocky will only log each request on info log level to stdout

**Comment by onedr0p** [comment]
Ok thanks @0xERR0R sorry for not RTFM :)
