### ISSUE TITLE
port: listen multiple ips?

### ISSUE THREAD

**Issue by bcookatpcsd** [0xERR0R/blocky#231]
Great little app.. 

It looked like in the docs that the port would accept multiple listeners.. 

ex

port: 10.20.30.40:53, 11.22.33.44:53

(docs)
# optional: DNS listener port and bind ip address, default 53 (UDP and TCP). Example: 53, :53, 127.0.0.1:53
port: 53

But it errors with this message:

@4000000060e8b9aa277e5fdc [2021-07-09 17:03:28] FATAL server: start tcp listener failed: listen tcp: address 192.168.10.200:53, 192.168.10.16:53: too many colons in address

where 10.200 and 10.16 are valid and working.. 

Thanks in advance.

**Comment by 0xERR0R** [comment]
No, you can either define one IP with port or just port(in this case blocky will listen on all interfaces)

**Comment by bcookatpcsd** [comment]
Thank you.

Is dnscrypt a potential forwarding option you are thinking about? 

I ask because I have added blocky in addition to dnscrypt-proxy at home, both being behind dnsdist just to get stats on which resolves faster. but dnscrypt-proxy can use dnscrypt and not dot.. 

Just looking to get more of an apples to apples comparison.. 

Thanks in advance.

**Comment by 0xERR0R** [comment]
Currently, blocky supports plain dns (with dnssec), DoT and DoH. To be honest, I'm not informed about Dnscrypt in details, i though, DoH shall be the future of DNS. Do you think dnscrypt has some advantages and schould be supported?

**Comment by bcookatpcsd** [comment]
Frank Denis (dnscrypt-proxy and dnscrypt proto author)
jedisct1

Feels very strongly about dnscrypt, many providers support it. 

https://en.m.wikipedia.org/wiki/DNSCrypt

This does it more justice than I could ever do. 

My 0.02

**Comment by 0xERR0R** [comment]
See also  #148
