### ISSUE TITLE
wildcard blocklists

### ISSUE THREAD

**Issue by bcookatpcsd** [0xERR0R/blocky#232]
host lists (0.0.0.0 1q2w3.fun) and domain lists (1q2w3.fun) are supported, but is there anyway to get a wildcard?

I'd like to block moneroocean.stream AND *.moneroocean.stream is there anyway for blocky to understand that?

**Comment by 0xERR0R** [comment]
It is not possible with "plain" host file format (wildcard is not supported). Each subdomain must be specified separately. There is an open issue (#12) which address the problem. But there is no common solution (afaik) in the wild: pihole uses regex list. AdGuard Home use own format (similar to adblock list format).

**Comment by 0xERR0R** [comment]
Duplicates #12
