### ISSUE TITLE
Any plans for a WEB GUI ?

### ISSUE THREAD

**Issue by shahidcodes** [0xERR0R/blocky#260]
Using blocky and really enjoying it. I was previously using PiHole which has a nice UI to inspect what's going to and stuffs. Just wanted to ask if there is any plan for any GUI?

**Comment by 0xERR0R** [comment]
Hey,

no, currently not. There is a Grafana dashboard for prometheus metrics, which shows some internal metrics and allows to enable/disable the blocking state.

I'm also currently working on (#258). This will allow to create another Grafana dashboard with detailed statistics about asked queries (e.g. top 20 asked domains, Top 20 blocked domains, last queries etc).

I'm trying to follow the KISS principle and implement only core features (basically DNS features) and provide integration for other tools (REST api, prometheus integration).
