### ISSUE TITLE
Quad9 IPv6 Upstream => parsing error

### ISSUE THREAD

**Issue by ikarisan** [0xERR0R/blocky#285]
Hi!

I tried to use the Quad9 IPv6 upstream servers, but the IP addresses cannot be parsed.
Quad9 uses

2620:fe::fe
2620:fe::9

But both :fe parts of the addresses result into:
"FATAL wrong file structure: can't convert port to number (1 - 65535) strconv.ParseUint: parsing "fe": invalid syntax"

These upstream values are not working:

    - 2620:fe::fe
    - 2620:fe::9

Blocky version: v0.15
Build time: 20210727-203516

Ikarisan

**Comment by 0xERR0R** [comment]
Hi, thank you for reporting. Yes, indeed, I can reproduce it. You can use `tcp+udp:[2620:fe::fe]:53` as workaround.
