### ISSUE TITLE
Do not cache nxdomain

### ISSUE THREAD

**Issue by onedr0p** [0xERR0R/blocky#287]
Hi 👋🏼 

It would be cool if this could be default, or configurable. Usually I'm testing things in my homelab and my service isn't online just yet when I try to hit it. Blocky caches that nxdomain so I always need to bounce the container to clear the cache.

Thanks!

**Comment by 0xERR0R** [comment]
Hi,

I think, it makes sense to cache negative results. The default TTL is 30 min (https://github.com/0xERR0R/blocky/blob/97a4a2eff34c5173410aada6c46c2cebff2616ad/resolver/caching_resolver.go#L35). Making it configurable is a good idea 👍

**Comment by onedr0p** [comment]
Would setting this to `-1` allow for me to disable caching of "negative" results?
