### ISSUE TITLE
Feature request: Source settings from seperate file

### ISSUE THREAD

**Issue by broizter** [0xERR0R/blocky#289]
It would be nice if you could use a seperate file for certain settings. My use case is that I wanna have a file that contains the "customDNS" entries so that I can easily sync it between my Blocky instances. I could sync the entire config.yaml file but it contains server specific settings such as "port:". 

For example:

```
/etc/blocky/config.yaml

customDNS:
  from-file: /etc/blocky/customdns.yaml
```
```
/etc/blocky/customdns.yaml

printer.lan: 192.168.178.3 
otherdevice.lan: 192.168.178.15,2001:0db8:85a3:08d3:1319:8a2e:0370:7344
```

**Comment by 0xERR0R** [comment]
Hi,

I understand the use case, but I'm not sure if this is the right solution: it would introduce more complexity in the config and it covers only customDNS. Of course, it would be possible to introduce this possibility into other configuration sections, but the value of the improvement is small.

I try to follow the KISS principle and keep the things outside which can be solved by other tools. Maybe it would be better to generate the config file from a template and replace the customDNS section with content from a file (I'm thinking of something like bash script / grep / awk)?

**Comment by broizter** [comment]
I respect following the KISS principle and I agree it's a problem that could be solved in other ways! Thanks for taking a look at this at least!
