### ISSUE TITLE
possibility to reactivate "question=" in query Log

### ISSUE THREAD

**Issue by kwitsch** [0xERR0R/blocky#291]
I noticed that the queryLog INFO log message has changed in v0.16. 
The new format lacks the "question=" block. 
This is inconvenient when using the log to fine tune your whitelist.

Tags: v0.15 & fb-inline-lists
`INFO query_logging_resolver: query resolved answer=* client_ip=* client_names=* duration_ms=* question=* response_code=* response_reason=*`

Tags: v0.16 & latest
`INFO queryLog: query resolved answer=* duration_ms=* response_code=* response_reason=*`

Is there a possibility to reactivate this block in v0.16?

Currently i only set "logLevel: info" in my config and don't have an "queryLog:" block included.

**Comment by 0xERR0R** [comment]
Hi,
Thanks for reporting. This field is somehow "disappeared" after introducing the new database logger.

**Comment by kwitsch** [comment]
Thanks a lot for your work and the quick response.
