### ISSUE TITLE
Deep cname inspection

### ISSUE THREAD

**Issue by runningman84** [0xERR0R/blocky#3]
Does this project also implement a deep cname inspection like pihole 5?
https://pi-hole.net/2020/01/19/announcing-a-beta-test-of-pi-hole-5-0/

BTW. blocky seems to be a great project to run in a home k3s cluster. The single binary and configuration using a config file is really cool.

**Comment by 0xERR0R** [comment]
Not yet, but it is really useful feature

**Comment by 0xERR0R** [comment]
Blocky checks response entries (CNAME and IP addresses A/AAAA) against the blacklists
