### ISSUE TITLE
Conditional forwarding support for CNAMEs

### ISSUE THREAD

**Issue by agneevX** [0xERR0R/blocky#312]
Currently, conditional forwarding is only supported for domain names that are queried. 

Let's say I want to forward all `*.akamai.net` queries to a specific server:

```yml
conditional:
  mapping:
    akamai.net: https://8.8.8.8/dns-query
```

`a1802.dscb.akamai.net` should be forwarded, however `se2.itunes.apple.com` is not forwarded.

```sh
❯ kdig +short +tls @1.1.1.1 se2.itunes.apple.com
se2-cdn.itunes-apple.com.akadns.net.
se2.itunes.apple.com.edgesuite.net.
a1802.dscb.akamai.net.
23.210.245.112
23.210.245.80
```

blocky should ideally send the query to its default upstreams, then if there's a CNAME match, the app should conditionally forward it.

This is similar to how Unbound's `forward-zone` works ([Docs](https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html?highlight=forward-zone#forward-zone-options)).

> CNAMEs are chased by unbound itself, asking the remote server for every name in the indirection chain, to protect the local cache from illegal indirect referenced items.

**EDIT**: simplify feature request

**Comment by agneevX** [comment]
Unbound supports this using `forward-zone` and I can add deploy blocky containers as its upstream as needed. @0xERR0R, you can go ahead and close this if you feel that is not important.

**Comment by 0xERR0R** [comment]
I think it is a useful (but edge case) feature. This is something, which is not on the top of my "todo" list, but I'll leave this issue open, maybe somebody will make a PR.
