### ISSUE TITLE
Can blocky listen in local network?

### ISSUE THREAD

**Issue by Mit2g** [0xERR0R/blocky#32]
Hey there. Blocky is really nice DNS for me but recently I found large DNS resolved request which was not requested by me in my server and it cause a lot of log in my disk. But I cant find any solution to listen only in local network such as 127.0.0.1 or 192.168.x.x and log deletion circulation.
So can Blocky do those thing? Thanks a lot

**Comment by 0xERR0R** [comment]
Hi, you can disable query logging, in this case blocky will log each request in info log level to stdout. You can just set log level to warning or redirect the output to /dev/null. You can also configure logrotate to clean up and archive log files periodically.
If your server is reachable from internet and you want "to hide" some services, I would recommend to to enable and configure a firewall, this would be the correct way to fix the problem.

**Comment by Mit2g** [comment]
> Hi, you can disable query logging, in this case blocky will log each request on info log level to stdout. You can just set log level to warning or redirect the output to /dev/null to keep the log clean. You can also configure logrotate to clean up and archive log files periodically.
> If your server is reachable from internet and you want "to hide" some services, I would recommend to to enable and configure a firewall, this would be the correct way to fix the problem.

Got it but also want a feature to listen local only.
Thanks again
