### ISSUE TITLE
Improve error message for wrong upstream definition

### ISSUE THREAD

**Issue by ikarisan** [0xERR0R/blocky#356]
Hi!
I am running blocky in a docker container. Today I tried to update the image from 0.16 to 0.17. But after doing this, blocky does not want to start any longer. :( 

The error messages are always:

[...]
[2021-12-07 19:21:10] FATAL wrong file structure: can't convert port to number (1 - 65535) strconv.ParseUint: parsing "": invalid syntax
[2021-12-07 19:21:12] FATAL wrong file structure: can't convert port to number (1 - 65535) strconv.ParseUint: parsing "": invalid syntax
[...]

Maybe I am missing the "config.GetConfig().HTTPPort" related entry, referenced in file root.go ("func initConfig()")?! But neither httpPort nor httpsPort is marked as mandatory.

**Comment by ikarisan** [comment]
Maybe the reason for this is, that in 0.16 the following line was okay:

upstream:
  default:
    - tls:dns.quad9.net

But within version 0.17 is seems that it must be something like this:

upstream:
  default:
    - tcp-tls:dns.quad9.net

O.O

**Comment by 0xERR0R** [comment]
It should be "tcp-tls", see here: https://0xerr0r.github.io/blocky/configuration/#upstream-configuration

The error message should be more verbose here

**Comment by ikarisan** [comment]
> The error message should be more verbose here

Yes. The line number where the error occurs would be nice. ;) ;)

**Comment by kwitsch** [comment]
> > The error message should be more verbose here
> 
> Yes. The line number where the error occurs would be nice. ;) ;)

The line number seems not be easily available in the conversion methode.

But it should be easy to modify the [error message](https://github.com/0xERR0R/blocky/blob/3fa79b4b96a64430cf41f602c3e0fe76265d8366/config/config.go#L180) with something like 
`err = fmt.Errorf("can't convert upstream resolver '%s' -> %w", upstream,  err)`.
This would show the invalid upstream resolver entry in the error message.
