### ISSUE TITLE
Add possibility to overwrite blacklist entries

### ISSUE THREAD

**Issue by rain0r** [0xERR0R/blocky#359]
It would be great if users could list some domains that will never be blocked even if they are listed in any loaded blacklist.

**Comment by 0xERR0R** [comment]
You can define a whitelist entry for some domain, this will override the blacklist entry: https://0xerr0r.github.io/blocky/configuration/#definition-black-and-whitelists

**Comment by rain0r** [comment]
> You can define a whitelist entry for some domain, this will override the blacklist entry: https://0xerr0r.github.io/blocky/configuration/#definition-black-and-whitelists

Works like a charm, thanks!
