### ISSUE TITLE
[Feature] read /etc/hosts 

### ISSUE THREAD

**Issue by dnalor** [0xERR0R/blocky#362]
dnsmasq (and others) can automatically read /etc/hosts and additional hostfile(s)/a directory of hostfiles (dnsmasq's `addn-hosts` parameter).
While customDNS>mapping can be used to archive something similar, the hosts method is very handy for having a single file (format) for static LAN IPs to distribute.
I don't have that many static IPs, so it's no big deal to update several files, but it might still be useful.

**Comment by kwitsch** [comment]
If the hosts are configured in blocky why do they need a identical host file on their own?
Are they using different dns server?

**Comment by dnalor** [comment]
> If the hosts are configured in blocky why do they need a identical host file on their own? 

It's a matter of convenience - static IP->host mappings are already in /etc/hosts for all servers (so they still work if DNS is unavailable), so I basically have to copy/paste any changes/additions there to blocky's config.
I used to run dnsmasq before, which reads /etc/hosts by default, so I didn't need to configure static host->IP mappings for DNS resolution.
