### ISSUE TITLE
[Feature] Conditional forwarding of all queries for unqualified hostnames

### ISSUE THREAD

**Issue by dnalor** [0xERR0R/blocky#363]
First of all, thanks for writing this. I've tried a couple of DNS proxies, currently running blocky, seems very promising.

This is rather similar to #133
Standard setup in LAN: clients get IP from DHCP server (router), announce their hostname to it (`dhcpcd`'s `hostname` option). No domain is used.
So for all unqualified hostnames, the DNS query should go to the router, and not upstream.
conditional>mapping seems to _nearly_ to this, but it seems it cannot match _all_ unqualified hostnames.
An elegant solution would be to extend conditional>mapping to match all unqualified hostnames with some specific keyword (e.g. "unqualified_hosts") or character (e.g. ".")
Example:
```
conditional:
   mapping:
      1.168.192.in-addr.arpa: 192.168.1.2
      @unqualified_hosts: 192.168.1.2
```
I've read your concerns regarding dots in the host name, but I really think that's very unusual setup (and IMHO a really bad idea in the first place), so a comment in the docs should be enough.

**Comment by 0xERR0R** [comment]
I like the idea with "." as "match all not fq queries".
