### ISSUE TITLE
Rewrite DNS response cache

### ISSUE THREAD

**Issue by 0xERR0R** [0xERR0R/blocky#378]
Current implementation has some drawbacks:

- it uses https://github.com/0xERR0R/go-cache -> which is a fork of not maintained project with some merged PRs
  - LRU implementation is not optimal
- workaround with TTL (see #290): there is a gap if some entry is expired, but not removed -> blocky returns response with TTL 0

New implementation should be created:
- Cache with limited element size (max elements)
- LRU
- TTL support
- callback function before entry is expired, which allows to refresh the entry and set new TTL

**Comment by kwitsch** [comment]
Bench tested 0.17 vs 0.18 resolution time of cached DNS entries.

Results:
0.17: ~15ms
0.18: ~6ms

For testing purpose i deployed the different versions on the same docker host with and identical configuration.
Each version was tested with DNS-Bench & DNS Test(Android App).

I'm positively impressed. 
Great job. 👍

**Comment by 0xERR0R** [comment]
Hi, that is cool. My goal was to remove the forked implementation of not maintained project. If the new implementation is also faster - this is a double win👍
