### ISSUE TITLE
Development docker build fails on fork

### ISSUE THREAD

**Issue by FileGo** [0xERR0R/blocky#401]
I've got this repo forked and the development docker build GitHub action always fails on forked repo with every push, as it can't login to Docker Hub.

Perhaps it could be worth adding something to the likes of condition below, to prevent Docker build from running on forks?

```
if: github.repository == ‘0xERR0R/blocky’
```

**Comment by 0xERR0R** [comment]
Yes, this makes sense. Either your solution or maybe just to check if DOCKER_USERNAME and DOCKER_PASSWORD are defined (if it is possible)
