### ISSUE TITLE
Client/cidr specific upstream dns server configuration

### ISSUE THREAD

**Issue by tahngarth** [0xERR0R/blocky#43]
Is there a way to set upstream DNS servers for a specific client or cidr address range? Use case is most clients I want going to Opendns, but some I want going to a geo location spoofing dns (mlb blackout workaround).

**Comment by 0xERR0R** [comment]
Currently, there is no way to achieve this behavior. Blocky peeks 2 random upstream resolver from resolver list and uses the answer from the fastest one.

**Comment by 0xERR0R** [comment]
Duplicate of #81, closing this issue, because #81 contains more details
