### ISSUE TITLE
Full featured sample config.yml

### ISSUE THREAD

**Issue by GUNT0815** [0xERR0R/blocky#443]
I think it would ease the usage, when a fill featured / complete config.yml would be provided. Eg like smb.conf with explaining remarks.

**Comment by 0xERR0R** [comment]
There is config.yaml with all possible values and comments: https://github.com/0xERR0R/blocky/blob/master/docs/config.yml

This file is also embedded on this page: https://0xerr0r.github.io/blocky/configuration/

**Comment by GUNT0815** [comment]
Sorry 0xERROR. The first linked document above is exactly what I am looking for (but could not find without your help). Thank you for your support and the great work.
