### ISSUE TITLE
After upgrade to 0.18 (docker): ERROR fileQueryLogWriter: can't create/open fileopen /logs/*** permission denied

### ISSUE THREAD

**Issue by ikarisan** [0xERR0R/blocky#444]
Hi!

I upgraded my docker container from version 0.17 to 0.18 an now I am getting "permission denied" errors for the logs. 

`[2022-02-25 20:03:34] ERROR fileQueryLogWriter: can't create/open fileopen /logs/2022-02-25_10_10_0_2.log: permission denied file_name=/logs/2022-02-25_10_10_0_2.log `

I am using docker-compose / portainer to deploy the container and I did not change anything at the docker host system. I just re-deployed the container with the 0.18 image.

**Comment by kwitsch** [comment]
Does this error also occur with a fresh container(no old volumes mounted)?

As of version 0.18 blocky doesn't run as root anymore which could explain the permission error.

**Comment by ikarisan** [comment]
> Does this error also occur with a fresh container(no old volumes mounted)?
> As of version 0.18 blocky doesn't run as root anymore which could explain the permission error.

... " with a fresh container"... I really don't know. Just updated the image/container.
As a work-around I set the permissions of the log directory to 777.
On my host, version 0.18 uses "100, 65533" for user and group, which is "systemd-timesync 65533". O.O

**Comment by kwitsch** [comment]
Could you share your compose file and blocky config?

**Comment by 0xERR0R** [comment]
> > Does this error also occur with a fresh container(no old volumes mounted)?
> > As of version 0.18 blocky doesn't run as root anymore which could explain the permission error.
> 
> ... " with a fresh container"... I really don't know. Just updated the image/container.
> As a work-around I set the permissions of the log directory to 777.
> On my host, version 0.18 uses "100, 65533" for user and group, which is "systemd-timesync 65533". O.O 
> 
> 
> 
> 
> 
> 
> 

Blocky uses uid 100,which is systemd-timesync on your system. Please adjust directory permissions, this user should have write permissions. Depending on your use case, you can also use docker volumes.

**Comment by ikarisan** [comment]
> Blocky uses uid 100,which is systemd-timesync on your system. Please adjust directory permissions, this user should have write permissions. Depending on your use case, you can also use docker volumes.

A "chown -R 100:65533" did the trick.
