### ISSUE TITLE
client name resolution stoped working

### ISSUE THREAD

**Issue by kwitsch** [0xERR0R/blocky#445]
I recreated my DNS stack yesterday and noticed an undesired behavior today.

Logs from yesterday: 
`...client_ip=192.168.100.100 client_names=kiwitower...`
vs logs from today:
`...client_ip=192.168.100.100 client_names=192.168.100.100...`

Tested dns and rdns resolution on a windows machine
`ipconfig /flushdns`
`nslookup kiwitower`
`nslookup 192.168.100.100`
which worked as expected.

I'll try to reproduce this behavior in a smaller stack during the week.
My main stack consists of 16 containers which makes analysing it quite troublesome.

**Comment by 0xERR0R** [comment]
Just checked my query log, I have client names (I use rDNS for client name resolution). Did you try to run blocky with debug log level?

**Comment by kwitsch** [comment]
I'm missing something...
Every now and then it works but most of the time not. 🤔

My [blocky_config](https://github.com/0xERR0R/blocky/files/8159921/blocky_config.txt)
recursive, localdomain, lists and redis are services in the same stack.

**Comment by kwitsch** [comment]
Figured that my rDNS Server don't resolve for a few seconds every 15 minutes(timing issue in cache refresh).

It seems that blocky caches the resolved names and if they don't resolve it takes some time to resolve them again.
