### ISSUE TITLE
feature request: ability to filter more QTYPES

### ISSUE THREAD

**Issue by bcookatpcsd** [0xERR0R/blocky#450]
If AAAA is QTYPE 28.. 

Looking to be able to filter more qtypes.. and to only allow a minimum A, CNAME, MX, NS, SOA, SRV, TXT.. or user configurable set of allowed/denied qtypes..

The IOS HTTPS (qtype 65) is being sent at the same time as the A record.. so blocking/filtering/rewriting the A or AAAA, the HTTPS gets to a non blocked record.. 

Not sure if something like this is of interest for your project.

For example:
 "HTTPS IN gateway.icloud.com. udp 47 false 1232" NOERROR qr,rd 36 0.000114521s
 "A IN gateway.icloud.com. udp 47 false 1232" NOERROR qr,rd,ra 308 0.001430431s

(query response, recursion desired, and recursion available)

**Comment by 0xERR0R** [comment]
Hi,
I'm not sure, if I understand your request correct. Blocky checks Question name for all request types against the blacklist. If the name is not blacklisted, the query will be resolved by using the upstream resolver. If response contains A, AAAA or CNAME, blocky checks the values also against blacklist.

What should be the desired behaviour for HTTPS dns request? I checked my traffic, but I didn't find any HTTPS requests in my network

**Comment by bcookatpcsd** [comment]
Sorry I didn't notice your response earlier

AAAA would be for ipv6, qtype 28.

HTTPS is for iOS devices, specifically qtype 65. 

https://en.m.wikipedia.org/wiki/List_of_DNS_record_types

I'm specifically looking to be able to filter record types. 

For example MX, NS, SOA, PTR, AAAA, HTTPS, TXT, HINFO, etc..

**Comment by 0xERR0R** [comment]
Ok, so you want to define a list of record types like "MX, HTTPS, TXT" and blocky should immediately return empty result (without asking the upstream dns server)? There is a property "disableIPv6" in the config, which enables the dropping of AAAA queries. I think this is very similar feature.

May I ask you just for my understanding, what is the use case for blocking / dropping of certain types?

**Comment by 0xERR0R** [comment]
I don't get why do you want to drop/filter HTTPS queries, but it is ok :)

So can solve your challenge, if we provide a new configuration, something like:?

```yaml
filterTypes: AAAA, HTTPS
```

With this configuration blocky would response with empty result for AAAA and HTTPS

**Comment by bcookatpcsd** [comment]
Yes would work.. Thank you sir. 

HTTPS is a new type of query from Apple.. 

https://community.cloudflare.com/t/apple-with-ios-14-pokes-a-hole-in-dns-filtering-with-query-type-65/225029

https://github.com/rozahp/dnsmasq
