### ISSUE TITLE
DNS cache poison of DNSSEC?

### ISSUE THREAD

**Issue by PeterDaveHello** [0xERR0R/blocky#455]
By default, if the upstream resolver is doing DNSSEC validation, the query of the record with broken signature will return [SERVFAIL](https://dnssec.vs.uni-due.de/dig-sigfail), but using `dig` with the `+cd` flag(_to set the CD (checking disabled) bit in the query_) to query domain will ask the resolver to bypass the DNSSEC check, return the result without validation.

Just noticed that the result of a CD bit enabled query will be cached by blocky, and then served to the client no matter if they enabled the CD bit, once the cache is created, the following query without CD bit will retrieve the same result without DNSSEC validation as the CD bit enabled.

The test result using [Quad9](https://quad9.net/):

```
$ dig +short sigfail.verteiltesysteme.net @9.9.9.9
$ dig +short sigfail.verteiltesysteme.net @9.9.9.9
$ dig +cd +short sigfail.verteiltesysteme.net @9.9.9.9
134.91.78.139
$ dig +short sigfail.verteiltesysteme.net @9.9.9.9
```

The test result using Block to proxy queries to Quad9 via DoH:

```
$ dig +short sigfail.verteiltesysteme.net @::1
$ dig +short sigfail.verteiltesysteme.net @::1
$ dig +cd +short sigfail.verteiltesysteme.net @::1
134.91.78.139
$ dig +short sigfail.verteiltesysteme.net @::1
134.91.78.139
```

Not sure if this is something should be fixed? Thanks.

**Comment by 0xERR0R** [comment]
Blocky uses currently only the DNS question name and the DNS type as a key for caching. I think the correct behaviour would be to cache the entry, but to mark it as "bad data". This entry should be returned from cache only if CD flag is set.

**Comment by PeterDaveHello** [comment]
That's awesome @0xERR0R 🎉 Thanks!
