### ISSUE TITLE
Support of DoH/DoT as bootstrap DNS

### ISSUE THREAD

**Issue by 0xERR0R** [0xERR0R/blocky#464]
Currently, bootstrap DNS can be plain DNS only (UDP/TCP via 53). It should be possible to use DoT/DoH as bootstrap DNS. If host system has no valid DNS configuration, bootstrap should be defined as IP address only.

**Comment by PeterDaveHello** [comment]
As non-IP DoT/DoH bootstrap DNS needs "another bootstrap DNS", which is the DNS used by system in this case, will limit to use IP address in bootstrap DNS be easier for the implementation?

**Comment by 0xERR0R** [comment]
Yes, there is only one bootstrap DNS in blocky. The system will use the default DNS resolver if needed. Ideally, bootstrap DNS should be only IP address or empty if host is configured properly.

**Comment by 0xERR0R** [comment]
I would prefer to use the same syntax here as for upstream resolvers (for example tcp+udp:example.com). Otherwise we have 2 different syntax for the same thing.

**Comment by 0xERR0R** [comment]
If host has no working DNS resolver, blocky will need one if bootstrap DNS is a host address. Workaround would be to use some ip addresses (like 1.1.1.1) which do have also a valid certificate (with SAN for the IP address).

If I understand it right, your approach would be to define an IP address for the resolver and to specify the awaited server name in the certificate. So technically, blocky will establish the connection to the DNS server (DoT or DoH) with the IP, but it will bypass the standard certificate chain validation and check if server certificate contains the defined "server name" in SAN or CN field?

**Comment by ThinkChaos** [comment]
Yeah exactly.
A simpler way to see it is "hardcoded DNS response" à la /etc/hosts IMO, and that's what I was envisioning for the implementation.

**Comment by 0xERR0R** [comment]
ok, got it. In this case it would be probably better to create this "special" case only for bootstrap DNS.

**Comment by ThinkChaos** [comment]
Also if you don't like the idea of a string format, we could do something like:
```yaml
bootstrapDns:
  address: x.x.x.x
  hostname: xxxx.com
```

I think it's doable with a new type that implements unmarshal (haven't looked at the code name probably wrong) by trying from a string first for backwards compatibility and then this format.

What's your thoughts on how this should look in the config?

**Comment by 0xERR0R** [comment]
> Also if you don't like the idea of a string format, we could do something like:
> 
> ```yaml
> bootstrapDns:
>   address: x.x.x.x
>   hostname: xxxx.com
> ```
> 
> I think it's doable with a new type that implements unmarshal (haven't looked at the code, name probably wrong) by trying from a string first for backwards compatibility and then this format.
> 
> What's your thoughts on how this should look in the config?

That looks good and it would be awesome if we can implement it in this way to keep the "old" config compatible.
Is "address" in the same format as the upstream resolver (like 'udp+tcp:1.1.1.1:53' or 'https://one.one.one.one/query')?

**Comment by ThinkChaos** [comment]
I was thinking address would be the currently supported format, such that `bootstrapDNS: "some string"` and `bootstrapDNS: address: "some string"` are equivalent.

**Comment by 0xERR0R** [comment]
I meant, do you consider to support also DoH and DoT as "address" parameter (like 'https://one.one.one.one/query' and 'tcp-tls:fdns1.dismail.de:853')? Currently, bootstrapDNs can handle only plain-DNS (aka port 53).

**Comment by ThinkChaos** [comment]
Ah yeah you're right, address + ip would make more sense. Where address supports all the formats and ip is just an ip.
