### ISSUE TITLE
High memory usage on blacklist refresh

### ISSUE THREAD

**Issue by bkupidura** [0xERR0R/blocky#470]
Im using blocky with ~19 blacklists, every refreshPeriod i see high memory usage spike (~50MB -> ~150MB -> ~50MB).

I tries to run all my pods with memory limits, to avoid OOM on HV, and this memory spikes sometimes leads to blocky killed by K8s.

Can we introduce some method to limit how many links will be downloaded in same time?
Afaik currently (https://github.com/0xERR0R/blocky/blob/f8b6e59ef452e0d63c88f108ec7ad35693314302/lists/list_cache.go#L145) we are just going thru all lists, and trying to fetch them in same time. With big number of lists/big number of entries in list we can hit this memory spike.
If we would be able to limit how many lists should be downloaded in same time it should help.

EDIT: I see that there are some download options (e.g downloadTimeout), can we just add download
Concurrency? :)

<img width="1421" alt="Screenshot 2022-03-28 at 16 09 08" src="https://user-images.githubusercontent.com/4814684/160416423-241f30eb-74a8-4304-9dd6-195fd1961bc8.png">

**Comment by 0xERR0R** [comment]
Yes, you're right. Blocky downloads all lists *per group* simultaneously. Each new downloaded list will be processed in-memory and the cache content will be replaced at the end. That means, we need temporarily the double amount of memory (to hold the old version and to process the new one).

It would make sense to introduce a new parameter "downloadConcurrency" or something similar.

You can also try to create multiple groups with less lists, this should also help

**Comment by jckefan** [comment]
+1 for a feature like downloadConcurrency. Currently, I'm running blocky on Mikrotik hap ac3 router (128 MB storage, 256 MB RAM) with 19 blocklist and 2 whitelist. On every refresh, blocky brings down the whole router's RAM availability to a single digit (with one time crashing the router entirely.)

**Comment by 0xERR0R** [comment]
I made some memory optimizations in #513 and #515 and introduced new parameter 'processingConcurrency' to limit the worker goroutine number.
