### ISSUE TITLE
Enhance logging / How to debug `EOF` error?

### ISSUE THREAD

**Issue by PeterDaveHello** [0xERR0R/blocky#482]
When I'm using blocky as DoT/DoH server, sometimes I saw this error:

```
[2022-04-02 14:33:04] ERROR: error on processing request: EOF
```

Escalate the `logLevel` to `debug` didn't help with some additional useful information, have anyone faced the same issue and got some experience sharing? Thanks.

**Comment by PeterDaveHello** [comment]
Just FYI, that I actually found that the problems may come from upstream, just not recognizable by the output of blocky, so maybe the question is: can we expect that block's output will show more info from upstream, especially the error request? What do you think?

**Comment by 0xERR0R** [comment]
EOF could be a network problem or a remote server problem. With debug/trace log level it should be possible to see which upstream resolver causes this problem. Sinse blocky requests on 2 remote upstreams, the error on one should not result in the error response to the client. I'll check the code, maybe we can add some useful context information if an error occurs.

**Comment by PeterDaveHello** [comment]
Looks like most of them is remote server problem, but I'm also seeing: `[2022-04-02 21:46:09] ERROR server: error on processing request: EOF` sometimes, some context info could be helpful in these cases.
