### ISSUE TITLE
Could not access /swagger endpoint

### ISSUE THREAD

**Issue by vakarthik** [0xERR0R/blocky#49]
Hello, thanks for this nice little piece of software. 

I face a small issue. i can access `/metrics` and `/debug/pprof/` endpoints. but i could not access `/swagger` endpoint. 

I did `disable_sanitize_html = true` in grafana, but still text panel is not loading script. What should i set the `blocky_url` variable in panel ? my installation is at `192.168.1.2`

thank you

**Comment by 0xERR0R** [comment]
Please try "/swagger/" (with backslash at the end).
Blocky url should be "http://192.168.1.2:4000" (please adjust port, if you use not 4000)

**Comment by vakarthik** [comment]
thank you.
i could access it with a trailing `/`
also in `grfana.ini` i forgot to remove the `;` 
now everything is working

**Comment by 0xERR0R** [comment]
I would reopen this issue. I think, it is a good idea to create a redirect from /swagger to /swagger/ to avoid confusions in the future
