### ISSUE TITLE
Add CustomIP block type to allow forwarding to IPs other that ZeroIP

### ISSUE THREAD

**Issue by brandon099** [0xERR0R/blocky#50]
I use a [null server](https://github.com/bmrzycki/nullserv) and would love the ability to forward to it's IP, but currently the only types supported are NxDomain and ZeroIP. This speeds up responses that have been blocked and bypasses some checks in applications checking if any content was returned.

I can take a stab at adding and submitting a PR, but thought I'd see what your thoughts are on adding that functionality.

**Comment by 0xERR0R** [comment]
This is a cool feature, I used it in the past with pi-hole. The problem is: more and more Websites use https. Does it work properly with https connections? Does it on-the-fly certuficate creation or something like this?

**Comment by brandon099** [comment]
What nullserv does for HTTPS connections is it responds with a valid TLS Response `Unknown Certificate Authority (48)`. This is one of the shortest valid responses to a TLS connection which will gracefully terminate a TLS handshake. So it does behave differently over HTTPS compared to HTTP traffic, but does provide a valid response, rather than timing out, thus speeding up the blacklisted request.

https://github.com/bmrzycki/nullserv/blob/master/main.go#L77,L93

**Comment by 0xERR0R** [comment]
`blockType` can now have a comma separated list of destination ip addresses, for example: `blockType: 3.3.3.3,2001:0db8:85a3:08d3:1319:8a2e:0370:7344`. It should be at least 1 ipv4 and 1 ipv6 to cover all query types. If only one (for example ipv4) is specified, a zero ip will be used for the other net (ipv6)
