### ISSUE TITLE
[Feature request] Package blocky as an addon for Home Assistant

### ISSUE THREAD

**Issue by vegsag** [0xERR0R/blocky#500]
Hello,
It would be very useful to have blocky packaged as an addon for Home Assistant.
My usecase would be to run another install of blocky so i could have a redundant setup without re-doing my setup.

I think the addon feature is actually just a "template" for how home assistant should run a docker container.
There is some documentation here: https://developers.home-assistant.io/docs/add-ons/tutorial

I think this would be of great value to the project and community. Many people already know home assistant. By creating this addon, you would open the door for people who don't know how to setup docker or just want a simple way to deploy a great dns proxy/blocker.

**Comment by kwitsch** [comment]
Something like this? [example.zip](https://github.com/0xERR0R/blocky/files/8544804/example.zip)

As far as i understand the link you just have to extract my example in the addon folder(and edit the blocky-config.yml).

Only my guess as i don't use home assistant. 😅

**Comment by 0xERR0R** [comment]
I think, this is something which should be created and maintained in a separate repository. There are already packages for several linux distributions and kubernetes, maintained by other people, see https://0xerr0r.github.io/blocky/installation/#other-installation-types.
