### ISSUE TITLE
Support for multiple configuration files

### ISSUE THREAD

**Issue by Qarasique** [0xERR0R/blocky#512]
Can i use "include" directive for config file, like in nginx ?

Example:
Separate *.conf file for

```
conditional:
  mapping:
```
and
```
customDNS:
  mapping:
```

I want to use a lot of static A entries, it would be nice to divide service settings and DNS entries

**Comment by ThinkChaos** [comment]
For static A entries, you could use the hosts file resolver to achieve this ([docs](https://0xerr0r.github.io/blocky/configuration/#hosts-file)).
There is no generic config include support though.

**Comment by 0xERR0R** [comment]
So basically the idea is to provide a path to the directory with several YAML files, blocky should read all files (alphabetically order) and "merge" them together, right?
