### ISSUE TITLE
Go 1.18 deprecation of net.Error.Temporary()

### ISSUE THREAD

**Issue by FileGo** [0xERR0R/blocky#533]
[net.Error.Temporary()](https://pkg.go.dev/net#Error) has been deprecated with Go 1.18:

Uses in blocky:

https://github.com/0xERR0R/blocky/blob/776c51fc59d1c69bb5b2963efe071901d8136eb6/resolver/upstream_resolver.go#L269

https://github.com/0xERR0R/blocky/blob/67724387602ec221613a0d2abd32563180c47e9e/lists/downloader.go#L118

**Comment by 0xERR0R** [comment]
relevant for #539
