### ISSUE TITLE
Trying to link up Grafana and prometheus with blocky

### ISSUE THREAD

**Issue by swiftaes** [0xERR0R/blocky#54]
When trying to setup grafana with Prometheus as a data source I get 
HTTP Error Bad Gateway. Both are in different dockers if that matters.

**Comment by 0xERR0R** [comment]
Can you provide an example, how you linked them? Docker-compose or plain docker?

**Comment by swiftaes** [comment]
Im using Windows 10 Docker Desktop, I installed them in different docker containers and am trying to add the localhost:9090/metrics to grafana and that is when I get that error

**Comment by 0xERR0R** [comment]
Ok, got it. You need blocky, prometheus and grafana. I will create a working example later today. You can't use localhost in a docker container, because your container can't reach your host machine. If you don't use docker-compose, you must link containers or put them in the same docker network.

**Comment by 0xERR0R** [comment]
Please check following example configuration: https://github.com/0xERR0R/blocky-grafana-prometheus-example

There is a docker-compose which creates 3 services: blocky (with very basic configuration), prometheus (with configured scraper for blocky) and grafana with prometheus datasource. You can check the steps in the readmy, how to import the blocky dashboard.

**Comment by swiftaes** [comment]
Ok I have done most of that I'm just getting stuck when trying to select prometheus there is no option https://i.imgur.com/9Q02cms.png

**Comment by 0xERR0R** [comment]
Yes, black andvwhite listscare configured in config.yml. Can be a http link or local referenced file
