### ISSUE TITLE
bind 53 permission denied

### ISSUE THREAD

**Issue by 24fpsDaVinci** [0xERR0R/blocky#543]
when I build using git master I have to add CAP_NET_BIND_SERVICE to service to start
but the ubuntu installer binary doesnt need the service line, any ideas? permission owner/group are same on both

**Comment by kwitsch** [comment]
Could it be that it's the same issue as in #368 ?

**Comment by 24fpsDaVinci** [comment]
I'm also seeing another problem, I dont know if i should open another issue. on a server with an amd 16 core cpu Blocky is really fast and low latency during the first 15-20 mins after a restart, then the latency noticeably increases. I've checked logs and responses are cached and 0-1ms when resolving from cache. Maybe its something to do with the LRU implementation? 

when i say latency i mean how fast web pages load. if i do another systemctl restart blocky it becomes fast again for another 15-20 mins.

**Comment by kwitsch** [comment]
That sound like you are blocking a url which is frequently called by many websites.
Loading resources is often implemented by trying it again after some time when receiving NXDOMAIN.

The 15-20 min time frame is between your configured caching minTime and maxTime, which let me believe that your client fetches a valid record during the restart and get NXDOMAIN after that.

Does the time of the latency problem changes if you enforce a valid blocklist download?

Configuration example:
```
blocking:
  downloadTimeout: 4m
  downloadAttempts: 5
  downloadCooldown: 10s
  failStartOnListError: true
```

**Comment by 24fpsDaVinci** [comment]
wow mystery solved. thank you. i guess the really low latency was not suppose to happen.

**Comment by kwitsch** [comment]
Glad it seams i could help 😅

If ther aren't any more uncertainties this ticket can be closed?

**Comment by 24fpsDaVinci** [comment]
please close, thanks

**Comment by kwitsch** [comment]
> please close, thanks

@0xERR0R as mentioned by @24fpsDaVinci this ticket can be closed
