### ISSUE TITLE
different cpu usage..

### ISSUE THREAD

**Issue by bcookatpcsd** [0xERR0R/blocky#544]
![image](https://user-images.githubusercontent.com/55087301/170486178-4b1c1fb9-0b4b-4291-a252-44a4daf39ecf.png)

This is a cpu graph from observium.

The host is a vm (i run arch btw..) 4 cpus, 4G, xanmod lts 5.15.40 vmxnet3, etc.. 

about 4k (+/- 10%) chromebooks, via wifi with this vm as their only recursor.. 

(blocky is sitting in front of dnscrypt-proxy)

```
---

port: 10.20.8.29:53
httpPort: 4000
bootstrapDns: tcp+udp:10.20.8.29:40

upstream:
  default:
    - tcp+udp:10.20.8.29:40

upstreamTimeout: 5s

filtering:
  queryTypes:
    - AAAA
    - HTTPS
    - ANY

caching:
  minTime: 2400s
  maxTime: 9600s
  maxItemsCount: 32768
  prefetching: true

logLevel: warn
# optional: Log level (one from debug, info, warn, error). Default: info
logTimestamp: false
```

Yesterday was the first day of only blocky as the recursor.. 

Previously it was coredns.. 

Will see how it looks today..

also.. can't seem to get the sigusr1 things to dump with the logLevel at warn.. 

```
 sv status blocky
run: blocky: (pid 163871) 832s; run: log: (pid 31930) 65530s

kill -s SIGUSR1 163871


tail -F /var/log/blocky/current
ERROR server: error on processing request:resolution was not successful, used resolvers: 'upstream 'tcp+udp:10.20.8.29:40'' and 'upstream 'tcp+udp:10.20.8.29:40'' errors: [can't resolve request via upstream server 10.20.8.29:40: dns: overflowing header size can't resolve request via upstream server 10.20.8.29:40: dns: overflowing header size]
ERROR server: error on processing request:resolution was not successful, used resolvers: 'upstream 'tcp+udp:10.20.8.29:40'' and 'upstream 'tcp+udp:10.20.8.29:40'' errors: [can't resolve request via upstream server 10.20.8.29:40: dns: overflowing header size can't resolve request via upstream server 10.20.8.29:40: dns: overflowing header size]
ERROR can't write message: write tcp 10.20.8.29:53->10.120.46.224:37166: write: broken pipe
ERROR can't write message: write tcp 10.20.8.29:53->10.120.63.169:34184: write: broken pipe
ERROR can't write message: write tcp 10.20.8.29:53->10.120.63.169:34244: write: broken pipe
ERROR can't write message: write tcp 10.20.8.29:53->10.120.63.169:34284: write: broken pipe
ERROR can't write message: write tcp 10.20.8.29:53->10.120.63.169:34208: write: broken pipe
ERROR can't write message: write tcp 10.20.8.29:53->10.120.63.169:34378: write: broken pipe
ERROR can't write message: write tcp 10.20.8.29:53->10.120.63.169:34498: write: broken pipe
ERROR can't write message: write tcp 10.20.8.29:53->10.120.63.169:34324: write: broken pipe
```

set the logLevel to info.. 

```
 INFO server: current configuration:
 INFO server: -> resolver: 'FilteringResolver'
 INFO server:      filtering query Types: 'AAAA, ANY, HTTPS'
 INFO server: -> resolver: 'ClientNamesResolver'
 INFO server:      deactivated, use only IP address
 INFO server: -> resolver: 'QueryLoggingResolver'
 INFO server:      type: "console"
 INFO server:      target: ""
 INFO server:      logRetentionDays: 0
 INFO server: -> resolver: 'MetricsResolver'
 INFO server:      metrics:
 INFO server:        Enable = false
 INFO server:        Path   = /metrics
 INFO server: -> resolver: 'CustomDNSResolver'
 INFO server:      deactivated
 INFO server: -> resolver: 'HostsFileResolver'
 INFO server:      deactivated
 INFO server: -> resolver: 'BlockingResolver'
 INFO server:      deactivated
 INFO server: -> resolver: 'CachingResolver'
 INFO server:      minCacheTimeInSec = 2400
 INFO server:      maxCacheTimeSec = 9600
 INFO server:      cacheTimeNegative = 30 minutes
 INFO server:      prefetching = true
 INFO server:      prefetchExpires = 2 hours
 INFO server:      prefetchThreshold = 5
 INFO server:      cache items count = 624
 INFO server: -> resolver: 'ConditionalUpstreamResolver'
 INFO server:      deactivated
 INFO server: -> resolver: 'ParallelBestResolver'
 INFO server:      upstream resolvers:
 INFO server:      - default
 INFO server:        - upstream 'tcp+udp:10.20.8.29:40'
 INFO server: - DNS listening on addrs/ports: [10.20.8.29:53]
 INFO server: - TLS listening on addrs/ports: []
 INFO server: - HTTP listening on addrs/ports: [4000]
 INFO server: - HTTPS listening on addrs/ports: []
 INFO server: runtime information:
 INFO server: MEM Alloc =                 1 MB
 INFO server: MEM HeapAlloc =             1 MB
 INFO server: MEM Sys =                  15 MB
 INFO server: MEM NumGC =                95
 INFO server: RUN NumCPU =                4
 INFO server: RUN NumGoroutine =         17
```

Open to suggestions..

**Comment by kwitsch** [comment]
Would be interesting what happens during the extreme spikes.
Any anomalies in the logs during the time frame (for example: repeat request with broken answer)?

Regarding the log output:
It is logged on level info so it seams logical that it does nothing when the logger itself only logs warning and higher. 😅


Out of curiosity: 
How does blocky perform at this amount of clients(response times)?
Do you run a single or multiple instances of blocky(failsafe & load balancing)?

**Comment by 0xERR0R** [comment]
can you check the debug endpoint and post the number of goroutines please? (http://host:4000/debug/pprof/)

**Comment by 0xERR0R** [comment]
Any news? Did you try the latest version?

**Comment by 0xERR0R** [comment]
It looks good now, no spikes. I improved internal locking for prefetching in last review, I think it was the problem. On systems with high load and enabled prefetching, exclusive lock was obtained relative often, which was not necessary.

**Comment by bcookatpcsd** [comment]
(possibly this will help as well..)

https://dnsdist.org/reference/config.html#setRingBuffersLockRetries

https://coredns.io/plugins/cache/#capacity-and-eviction

I understand dnsdist is a completely different animal.. (the building process is horrendous.. my 0.0.2) as is coredns..

pc = newPacketCache(102400, {numberOfShards=50, maxTTL=900, minTTL=0})
getPool(""):setCache(pc)

'shards' and 'contention' and 'ringbuffers' and 'locking' (understandably) would be a thing.. 

I was trying to make my life easier by moving away from dnsdist.. but I have an extensive dnsdist config

**Comment by bcookatpcsd** [comment]
The chromebooks do this (terrible) thing.. 

[2022-06-09 12:03:13]   10.20.8.29      kdxduzcz.cbk.pms.pcsd   A       REJECT  0ms     -
[2022-06-09 12:03:13]   10.20.8.29      kznoszzvoubact.cbk.pms.pcsd     A       REJECT  0ms     -
[2022-06-09 12:03:13]   10.20.8.29      diffhcfgm.cbk.pms.pcsd  A       REJECT  0ms     -
[2022-06-09 12:03:13]   10.20.8.29      ykgjwyismmo.cbk.pms.pcsd        A       REJECT  0ms     -
[2022-06-09 12:03:13]   10.20.8.29      egdexfowpbv.cbk.pms.pcsd        A       REJECT  0ms     -
[2022-06-09 12:03:13]   10.20.8.29      wlajhmtrdvfg.cbk.pms.pcsd       A       REJECT  0ms     -


(there are older better links.. but the issue is the same.. )
https://unix.stackexchange.com/questions/363512/chrome-dns-requests-with-random-dns-names-malware

(also relevant link)
https://arstechnica.com/gadgets/2020/08/a-chrome-feature-is-creating-enormous-load-on-global-root-dns-servers/

(dnscrypt-proxy change log)
https://github.com/DNSCrypt/dnscrypt-proxy/blob/fc0ff3b26ae85e5f6265a26c25531f5877f31078/ChangeLog#L204

There is a filter: block_unqualified which (as indented) blocks hostname lookups being sent upstream.. I would have *millions* of egdexfowpbv,  wlajhmtrdvfg, etc requests being sent along per day.. (and I'm no one) .. so in trying to do my part to be a 'better netizen'.. here we are.. 

:/

There are options in the Google Admin Console, but they don't stop the rd request, so the next best thing I could do after blocking the shortname lookup, was google was forwarding the reqest to the search domain, so I made a local invalid local search domain.. cbk.building.internal.tld

[I] root@arch0829-98f219 ~# grep -c cbk /var/log/blocky/*
/var/log/blocky/@4000000062a21fae0a414074.s:78
/var/log/blocky/@4000000062a21fca2f5fe824.s:126
/var/log/blocky/@4000000062a21fe13b1c31cc.s:140
/var/log/blocky/@4000000062a21ff83253721c.s:88
/var/log/blocky/@4000000062a2203c14d1db5c.s:90
/var/log/blocky/@4000000062a2206e3b9885ec.s:87
/var/log/blocky/@4000000062a2208e331d03ac.s:94
/var/log/blocky/@4000000062a220101c1362b4.s:74
/var/log/blocky/@4000000062a220531b921524.s:110
/var/log/blocky/@4000000062a220271493a97c.s:85

that's 5 minutes of logs.. (it's a vm with a tmpfs)
blocky         128M   11M  118M   8% /var/log/blocky

dnscrypt-proxy has it's own shards/contention/ringbuffers/locking issues.. which is why it's not first in the chain.. 

I would get a few of these a month, (dnsdist shows it the best)

![photo_2022-05-03_13-27-34-blur](https://user-images.githubusercontent.com/55087301/172900447-5c861209-0758-437e-ba8f-6517193cf85b.jpg)

Seems to be related to a new build release, etc.. 

Anyway.. thanks for reading..

**Comment by kwitsch** [comment]
Blocky has an option to forward non FQDN queries to another DNS server.
```
conditional:
  mapping:
    # for all unqualified hostnames
    .: 168.168.0.1
```

Maybe we should add something similar for blocking? 🤔

It seems that caching the negative response in this case is also unnecessary.
I suggest a new "fqdnResolver" at the start of the resolver chain which instantly returns NXDOMAIN if the option is activated and the request is non FQDN.

This way no other resolver are bothered by those requests.

**Comment by 0xERR0R** [comment]
AFAIK, chrome does those "random" queries to check if dns server does hijack the response. Those queries must return NXDOMAIN and not 0.0.0.0.

We can address this special queries, but we need somehow distinguish between valid local network queries and those "magic" queries.

**Comment by 0xERR0R** [comment]
Sure, it is also possible. If non fqdn are blocked, the conditional configuration (with dot) will not work, must be clearly described in the doc
