### ISSUE TITLE
Automatic subdomain blocking

### ISSUE THREAD

**Issue by 12425** [0xERR0R/blocky#556]
Hi, this is a bit related to #12 but has nothing to do with wildcard or regex.
Regarding a domain in a blocklist, I think it makes sense to also block all subdomains as well.
For example, one line in a blocklist is
`ad.com`
Then not only the `ad.com`, but also the `sub.ad.com` and `ano.ther.ad.com` should be blocked.

I know it doesn't make sense for a hosts file such as
`10.1.1.1  example.com`
With this, the `sub.example.com` doesn't have to be resolved as 10.1.1.1. But at least for blocklist, we should block all subdomains.

**Comment by 0xERR0R** [comment]
Simple blacklist entry (hosts format or just domain) works as /etc/hosts, it must match exactly. I'm not sure, if it is a good idea to distinguish between hosts format and a "simple" domain list file and apply different logic. Following the KISS principle is the logic the same (currently). As you mentioned, it is always possible to use regex.

**Comment by 0xERR0R** [comment]
I'll close this issue, please feel free to reopen if you have a different opinion or some other idea.
