### ISSUE TITLE
[Feature Request] delivery of blocking group as EDNS error 

### ISSUE THREAD

**Issue by kwitsch** [0xERR0R/blocky#560]
Read about some DNS specifications and stumbled upon [Extended DNS Errors
RFC 8914](https://datatracker.ietf.org/doc/rfc8914/).

It describes in "2. EDNS0 Option Format" a text field for storing human readable information and a specific error type for blocking in "4.16. Code 15 - Blocked".

I think it would be handy adding a EDNS error to the blocked response including the responsible blocking group as info-text.

This way the information why a certain domain is not accessible is provided to the client and hasn't to be fetched from the request log.

**Comment by 0xERR0R** [comment]
That would be very handy. Just use dig to determine why is a domain blocked.

This proposal is relatively new. I think, many dns clients have no support for it.

Another question, what will happen (if  in the future, when all clients understand it) if client receives "blocked", will it automatically do some fallback to bypass blocking?

**Comment by 0xERR0R** [comment]
I think we can implement this feature as a new resolver, which enhances the response with edns record. I would also suggest not to overcomplicate the configuration. Maybe just a boolean "enabled", default false?
