### ISSUE TITLE
Upstream DoH with domain names failing

### ISSUE THREAD

**Issue by adyanth** [0xERR0R/blocky#578]
I have Cloudflare Access where I have a custom subdomain for DoH and DoT (for example: https://to9nljrrr2.cloudflare-gateway.com/dns-query). But when using this as upstream for blocky, I see it fails with the error below:

```bash
2022-06-29 02:27:39] ERROR server: error on processing request:can't resolve request via upstream server https://162.159.36.20:443/dns-query: http return code should be 200, but received 403
```

This looks to be that blocky is trying to make a https request without using the SNI, which will not work. It works just fine with https://1.1.1.1/dns-query since it works with IP as well, but anything that has a domain name will probably fail if https call is made with just the IP address.

Feel free to use the above DoH/DoT endpoint for testing, I will keep that up until this issue is closed. Do note that any DNS request made to it will be logged on my Cloudflare account. Edit: better yet, try with https://cloudflare-dns.com/dns-query

**Comment by adyanth** [comment]
The following might help
https://pkg.go.dev/net/http#Transport
https://pkg.go.dev/crypto/tls#Config

TLSClientConfig.ServerName should be set on the net/http.Client.Transport.TLSClientConfig to the upstream server entry when using IP address like it is done now.

    // ServerName is used to verify the hostname on the returned
	// certificates unless InsecureSkipVerify is given. It is also included
	// in the client's handshake to support virtual hosting unless it is
	// an IP address.
	ServerName [string](https://pkg.go.dev/builtin#string)

**Comment by adyanth** [comment]
Took a couple of pcaps, the one difference I see is that for the failing case with domain name, we are using TLS1.2 while 1.1.1.1 is using TLS1.3.

**Comment by 0xERR0R** [comment]
It looks very interesting:
It works with "https://dns.digitale-gesellschaft.ch/dns-query", but not with "https://cloudflare-dns.com/dns-query". 403 means "forbidden" and this comes from cloudflare.

If I try to use the IP address directly, I can reproduce the result:

Cloudflare:
```sh
$ curl -v https://162.159.36.5/dns-query
*   Trying 162.159.36.5:443...
* Connected to 162.159.36.5 (162.159.36.5) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS alert, handshake failure (552):
* error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
* Closing connection 0
curl: (35) error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
```

digitale-gesellschaft.ch:
```sh
$ curl -v https://185.95.218.43/dns-query
*   Trying 185.95.218.43:443...
* Connected to 185.95.218.43 (185.95.218.43) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=dns.digitale-gesellschaft.ch
*  start date: May  8 12:38:49 2022 GMT
*  expire date: Aug  6 12:38:48 2022 GMT
*  subjectAltName does not match 185.95.218.43
* SSL: no alternative certificate subject name matches target host name '185.95.218.43'
* Closing connection 0
* TLSv1.3 (OUT), TLS alert, close notify (256):
curl: (60) SSL: no alternative certificate subject name matches target host name '185.95.218.43'
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by 0xERR0R** [comment]
Yes, this is very probably a bug in blocky. We changed the way how bootstrap dns is working. We support now DoH and DoT as bootstrap and we need to retrieve the IP of the upstream early. Maybe we should somehow parameterize the SSL handshake,..

**Comment by 0xERR0R** [comment]
Just tried to set Host (https://pkg.go.dev/net/http#Request.URL) to "cloudflare-dns.com" in httpUpstreamClient.callExternal -> it works. Will test it today, but I think, this is the way to go.

**Comment by adyanth** [comment]
Ohh perfect, there was a much higher lever option to change it, haha, I was looking at the TLSOptions. Let me know if you need me for a PR or testing it out or anything, happy to help :)

**Comment by 0xERR0R** [comment]
I created PR for this issue (https://github.com/0xERR0R/blocky/pull/580) -> would be cool if you can test it on your environment

**Comment by adyanth** [comment]
Works flawlessly :)

```bash
[2022-06-29 16:24:03]  INFO queryLog: query resolved answer=CNAME (dyna.wikimedia.org.), A (103.102.166.224) client_ip=10.42.2.0 client_names=10.42.2.0 duration_ms=32 question=A (meta.wikimedia.org.) response_code=NOERROR response_reason=RESOLVED (https://to9nljrrr2.cloudflare-gateway.com/dns-query)
```
