### ISSUE TITLE
[Feature Request] Add primary key by default on DNS query log database table

### ISSUE THREAD

**Issue by adamsewell** [0xERR0R/blocky#585]
We use Digital Ocean's managed MySQL instances for a lot of our database needs, including wanting to log queries to our existing instance. One issue with this is they require any table to have a Primary Key. Would it be possible to add that natively to logging to MySQL databases? We ended up writing a exporter from file to MySQL to get around this but it would be nice to have natively. 

Some of their documentation: https://docs.digitalocean.com/products/databases/mysql/how-to/create-primary-keys/

**Comment by 0xERR0R** [comment]
Yes, we can add a sequence as a primary key. AFAIK, you need a PK to ensure uniqueness, if you use a table as a reference or if you want to update/delete a single row. We don't have any of this use cases for this table. This could also be useful to copy/replicate a data set. So a PK would introduce some overhead on the database side.

**Comment by 0xERR0R** [comment]
Looks like it is not possible to add a primary key to the existing table with gorm: #3537

Adding with SQL works fine: `ALTER TABLE `log_entries` ADD `id` INT PRIMARY KEY AUTO_INCREMENT`
