### ISSUE TITLE
Add a healthz API endpoint for health checks

### ISSUE THREAD

**Issue by adyanth** [0xERR0R/blocky#588]
Since the container takes quite some time to download blocklists and start, it is good to have a /healthz API endpoint that will respond with a 200 OK once everything is done and all the interfaces (/dns-query, /api/query, TCP and UDP sockets) are up.

I currently have the health checks pointed to the TCP port 53, but if the API endpoint or the UDP server goes down, it won't be detected.

**Comment by 0xERR0R** [comment]
There is a healcheck defined in the Dockerfile. It uses dig via port 53 to resolve a "magic" query name. Since DNS resolution is only active after all initialization steps are done, it works pretty well. 

Can you use docker healthcheck in your deployment?

**Comment by adyanth** [comment]
`dig @127.0.0.1 -p 53 healthcheck.blocky +tcp +short`

Okay, TCP name resolution for `healthcheck.blocky` right? I can use the exec health check for it in Kubernetes, should be fine, thanks!

Sidenote: If a user sets `port` to something else in the config.yaml, will the docker healthchecks fail?

**Comment by 0xERR0R** [comment]
> 
> Sidenote: If a user sets `port` to something else in the config.yaml, will the docker healthchecks fail?

Yes, it will fail. This is a tradeoff, users who use blocky as binary should be able to change the port. In docker, you don't need it, since you can remap the port. Healthcheck is defined in Dockerfile, if somebody changes the port in docker, he/she also must change the healthckeck command

**Comment by adyanth** [comment]
Sounds good, this works.
