### ISSUE TITLE
Cannot retrieve any lists all of a sudden

### ISSUE THREAD

**Issue by MaestroJAL** [0xERR0R/blocky#60]
First of all, blocky works pretty well for my network. Thank you for making/releasing it! I have my blocky instance on my raspberrypi4 via docker and after a little configuration issues, had it up and running beautifully. For the last couple of days, since the latest update (I think), blocky cannot update any list.  It throws this error for each list:

   WARN list_cache: Temporary network error / Timeout occurred, retrying... Get "https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist": dial tcp: lookup zeustracker.abuse.ch on 127.0.0.11:53: read udp 127.0.0.1:57929->127.0.0.11:53: i/o timeout attempt=3 link=https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist

I've checked that my rp4 has network and that DNS requests for the rp4 go directly to a DNS provider (OpenDNS).  I can browse and update other things on the rp4 so I know it's not it's core connectivity. Restarting the rp4 and/or the container does not fix the issue. 

Question: Is blocky supposed to be using 127.0.0.11? Right now, blocky is working with cached lists but some of the lists I use are updated daily. 

Thank you for your time!

**Comment by 0xERR0R** [comment]
It looks like a DNS problem in a docker network. 127.0.0.11 is the DNS server in docker. Can you try to configure DNS server direct for blocky docker container with `docker run ... --dns=208.67.222.222` or in docker-compose `dns: 208.67.222.222` (see https://docs.docker.com/compose/compose-file/#dns)

**Comment by MaestroJAL** [comment]
And that solved it! Thanks! Thanks also for the explanation of the 127.0.0.11 address. Keep up the great work on this. It's simple, customizable, and fire and forget. Love that.
