### ISSUE TITLE
[Feature]: Support for redis sentinel

### ISSUE THREAD

**Issue by onedr0p** [0xERR0R/blocky#632]
Hi 👋🏼

It would be great if blocky could connect to a highly available redis instance.

Here's a couple examples of applications that support this method of redis.

https://www.authelia.com/configuration/session/redis/
https://github.com/outline/outline/blob/93bb9d067d0f61a2f5d6f1d302774b128095a4d0/.env.sample#L22L29

Thanks!

**Comment by kwitsch** [comment]
Looks reasonable to me. 
Will work on it as I get some time.

**Comment by onedr0p** [comment]
Thanks! This makes blocky more resilient to failure if a redis master goes offline. Much appreciated 👍
