### ISSUE TITLE
Grafana dashboard does not show when imported through helm

### ISSUE THREAD

**Issue by Diaoul** [0xERR0R/blocky#647]
It seems the dashboard importing does not like the `__inputs` very much. I am not sure how other dashboard perform their exports but I suspect there is something that could be improved here.
Example [here](https://grafana.com/grafana/dashboards/11314-unifi-poller-uap-insights-prometheus/)

[Is it possible](https://github.com/kubernetes/ingress-nginx/issues/4190) that the usage of `DS_PROMETHEUS` in `__input` is deprecated?

Sadly I am a grafana noob so I can just report not contribute a fix :cry:

**Comment by luucaocuong** [comment]
Same issue when I trying to add [Istio control plane dashboard](https://grafana.com/grafana/dashboards/7645-istio-control-plane-dashboard/) to grafana helm chart. However, some other dashboards can be added successfully.

**Comment by kwitsch** [comment]
Tried applying mentioned patch to [blocky-grafana.json.txt](https://github.com/0xERR0R/blocky/files/9539401/blocky-grafana.json.txt).
Unfortunately I'm unable to test it at the moment.
You can test it if u want. I'll test it next week otherwise.

**Comment by MaverickD650** [comment]
Did test this and had the same issues with panels not working even with the fix.

**Comment by MaverickD650** [comment]
Solved my issues with the dashboard. The job name in my helm install (Truecharts) was blocky-http so some panels worked when I did that. Also the gf_panels_disable_sanitize_html variable in grafana needs to be true in order for the blocking status panel to work.
