### ISSUE TITLE
AXFR fails most times

### ISSUE THREAD

**Issue by mapl** [0xERR0R/blocky#67]
Assume you have this snippet beneath in your config with two identically DNS Server but different protocols.
If the DNS client is sending an AXFR query to transfer a zone, it uses the TCP Protocol and the UDP. 

Because Blocky randomly selects two external upstream DNS server from the list (UDP+TCP), the fastest response wins, which is usually the UDP response.

However, UDP is always denied by Auth. DNS Server when trying to perform Zone Transfer over UDP and sends back a Servfail DNS Message.

Blocky must honor this and must forward TCP based DNS Queries (like AXFR/IXFR) to TCP Upstream DNS Server only. 

Otherwise, any AXFR Queries over UDP will fail.

[https://tools.ietf.org/html/rfc1035#section-4.2.1](url)

> UDP is not acceptable for zone transfers, ....

[https://tools.ietf.org/html/rfc5936#section-2](url)

> An important aspect to keep in mind is that the definition of AXFR is
>    restricted to TCP [RFC0793] (see Section 4 for details).  The design
>    of the AXFR process has certain inherent features that are not easily
>    ported to UDP [RFC0768].
> 

### Example

upstream:
```
    # these external DNS resolvers will be used. Blocky picks 2 random resolvers from the list for each query
    # format for resolver: net:host:[port][/path]. net could be tcp, udp, tcp-tls or https (DoH). If port is empty, default port will be used (53 for udp and tcp, 853 for tcp-tls, 443 for https (Doh))
    externalResolvers:
      **- tcp:80.241.218.68**
      **- udp:80.241.218.68**
      
```

**Comment by 0xERR0R** [comment]
ok, I understand the problem: AXFR works only with TCP, but I can't get the use case. AXFR is used to manually trigger a DNS replication, but for this you shouldn't use a DNS proxy like blocky (because blocky peeks DNS resolver in a random order). You should trigger DNS replication directly

**Comment by mapl** [comment]
Well, besides axfr, there are certain situations where you want to fallback to tcp when udp is not suffcient, for example when the udp answer is truncated and the clients is trying over tcp to get the full answer.

https://serverfault.com/questions/698251/how-does-the-dns-protocol-switch-from-udp-to-tcp

**Comment by 0xERR0R** [comment]
Ok, that means there are basically 2 options:
- client makes TCP request, because this is mandatory (i. e. Zone transfer)
- client makes TCP request, because udp was not successful

Blocky should try to use TCP resolver on TCP and UDP on UDP requests (if those defined), right? But what about DoH requests?
Zone transfer should always use TCP

**Comment by mapl** [comment]
Yes, the simple basic rule should be TCP to TCP:53 and UDP to UDP:53 in order to respect the original intention of the sender. This will retain DNS integrity whereas a mixture of TCP and UDP will lead to potential errors.
DoH is TCP right but defines another resolver protocol on another port. I don't see a conflict here. 

> ..net could be tcp, udp,...

Maybe, you can combine TCP and UDP into one single net definition as DNS on Port 53 should always accept UDP and TCP queries and denying one of them for whatever reason, is against good habits

**Comment by mapl** [comment]
btw: Kudo for this very nice project!

**Comment by mapl** [comment]
May I ask for the status of this behavior enhancement "request"? I am not sure if I can implement this properly in your code by myself.

Anyway, I browsed some other golang based DNS repos and found COREDNS is doing exactly that.

https://github.com/coredns/coredns/blob/808c4b802c29c51c0e79e850e541a41bff2e0c3f/request/request.go#L114

```
// Proto gets the protocol used as the transport. This will be udp or tcp.
func (r *Request) Proto() string {
	if _, ok := r.W.RemoteAddr().(*net.UDPAddr); ok {
		return "udp"
	}
	if _, ok := r.W.RemoteAddr().(*net.TCPAddr); ok {
		return "tcp"
	}
	return "udp"
}

// RemoteAddr returns the net.Addr of the client that sent the current request.
func (r *Request) RemoteAddr() string { return r.W.RemoteAddr().String() }

```

**Comment by 0xERR0R** [comment]
I haven't started yet, but will definitely take a look at this. Client's IP address is being already extracted and passed with the request struct (https://github.com/0xERR0R/blocky/blob/4fcaceb5c9354465e9aadcf94f9c5380a1976b99/server/server.go#L212), this could be extended to the protocol information.

**Comment by 0xERR0R** [comment]
> Yes, the simple basic rule should be TCP to TCP:53 and UDP to UDP:53 in order to respect the original intention of the sender. This will retain DNS integrity whereas a mixture of TCP and UDP will lead to potential errors.
> DoH is TCP right but defines another resolver protocol on another port. I don't see a conflict here.
> 
> > ..net could be tcp, udp,...
> 
> Maybe, you can combine TCP and UDP into one single net definition as DNS on Port 53 should always accept UDP and TCP queries and denying one of them for whatever reason, is against good habits

@mapl: Was just thinking about this behaviour: wouldn't it be better, if UDP request can use either UDP or TCP resolvers and TCP request only TCP? Typical use case is: in a local network I use blocky as udp resolver, but I want to use DoH external DNS server (which uses TCP). That means: for UDP request, nothing must be changed, on TCP request, only TCP resolvers should be considered on random choose.

**Comment by mapl** [comment]
[https://github.com/coredns/coredns/tree/master/plugin/forward](url)

Sure, you could take a look at CoreDNS's forward plugin as an inspiration for a well suited approach.

> _force_tcp, use TCP even when the request comes in over UDP.
> 
> prefer_udp, try first using UDP even when the request comes in over TCP. If response is truncated (TC flag set in response) then do another attempt over TCP. In case if both force_tcp and prefer_udp options specified the force_tcp takes precedence._

**Comment by 0xERR0R** [comment]
The behaviour was changed: in configuration, an external dns resolver hat have either "tcp+udp" (default, if empty), "tcp-tls" or "https" als protocol. Old configuration (with "tcp" or "udp") will be mapped to "tcp+udp". UDP requests will be delegated to UDP DNS upstreams (in case of tcp+udp) or tcp-tls/DoH, TCP requests -> to TCP DNS or tcp-tls/DoH

**Comment by mapl** [comment]
I just compiled from source and tested the new behavior. It works now as expected :) thank you!

**Comment by 0xERR0R** [comment]
@mapl: Thank you for testing!
