### ISSUE TITLE
"permission denied on port 53" when using "network_mode: host" in development version (docker)

### ISSUE THREAD

**Issue by GitSchorsch** [0xERR0R/blocky#671]
Starting development version with "network_mode: host" breaks with:

`blocky | [2022-10-10 20:03:04] ERROR server start failed: start udp listener failed: listen udp :53: bind: permission denied`

No problem with release version.

**Comment by 0xERR0R** [comment]
@kwitsch: Last change in Dockerfile moved "setcap cap_net_bind_service" from run image into another build stage image, maybe this is the reason and it works only if applied in the same build stage?

**Comment by kwitsch** [comment]
Shouldn't be a problem as long as it is build with [buildx](https://wildwolf.name/multi-stage-docker-builds-and-xattrs/) which is used in `make docker-build` and in the workflows.

Did you use one of the registries or build it yourself?

**Comment by GitSchorsch** [comment]
i'm using one of the registries. That's my image definitition in the docker-compose.yml:

`image: spx01/blocky:development`

**Comment by kwitsch** [comment]
Found the bug.

It seams like there was some problem with the user inside the docker container.
Don't know how I missed it during testing.

Made a pull request to fix it.
PS: #651 will also fix it

**Comment by 0xERR0R** [comment]
> Found the bug.
> 
> It seams like there was some problem with the user inside the docker container. Don't know how I missed it during testing.
> 
> Made a pull request to fix it. PS: #651 will also fix it

Thanks! I merged the fix 🤝

**Comment by GitSchorsch** [comment]
Thanks a lot!
