### ISSUE TITLE
Blocky query (MySQL) dashboard doesn't work on Grafana v9.2.0

### ISSUE THREAD

**Issue by pg1261** [0xERR0R/blocky#679]
Hi,

with the new update of Grafana v9.2.0 the dashboard for Blocky query (MySQL) doesn't work anymore.

- blocky v0.19
- Grafana v9.2.0
- MariaDB 10.9.3

Every Panel has a `db query error: Error 1064` error. Something happens to the datasource handling? Or with the variables?

The query inspector shows some missing inserts for the variable `$client_name` and `$question`.

Example: Blocked by Blacklist
```
SELECT t.request_ts AS time,
       case when t.reason  like 'BLOCKED%' then SUBSTRING_INDEX(SUBSTRING_INDEX(t.reason,'(',-1), ')',1) else ' end AS metric,
       count(t.reason) AS cnt
FROM log_entries t
WHERE t.response_type ='BLOCKED'
  AND t.request_Ts BETWEEN FROM_UNIXTIME(1665672645) AND FROM_UNIXTIME(1665759045)
  AND t.client_name in ()
  AND (length(') = 0 or INSTR(t.question_name, lower(')) > 0)
GROUP BY 2
ORDER BY time
```

If I switch back to Grafana v9.1.7 everything is fine.

**Comment by kwitsch** [comment]
Sounds similar to #647

**Comment by martadinata666** [comment]
Adding myself due same experience, only Blocky Query fail, the prometheus blocky work fine.

**Comment by martadinata666** [comment]
9.2.1 work again, https://github.com/grafana/grafana/issues/57164

**Comment by jk779** [comment]
Having the same problem currently, using `latest` of grafana (which is like 10.1) and the exact same problem still exists. Are you sure @martadinata666 it works with 9.2.1 (and up?) and they didn't include the fix in their 10.x branch?

Using mysql btw because i thought that was the problem first.

**Comment by pg1261** [comment]
10.1.5 works well
