### ISSUE TITLE
Whitelist.txt loads but not acted upon

### ISSUE THREAD

**Issue by DaBrondo** [0xERR0R/blocky#68]
I've tried adding both www.googleadservices.com and googleadservices.com to my whitelist but it still blocks that domain.  Nothing showing in the logs.

**Comment by DaBrondo** [comment]
And yes, the whitelist.txt does load the entries according to the console startup messages.

**Comment by 0xERR0R** [comment]
Do you see DNS queries in the log? If yes, what ist the response reason? BLOCKED?
