### ISSUE TITLE
blocky api url ?

### ISSUE THREAD

**Issue by caywin25** [0xERR0R/blocky#681]
hello

Thank you for your work, blocky is great :)
I am setting up grafana with this dashboard: https://grafana.com/grafana/dashboards/13768

But I am asked: blocky api url
What value should I put please?

Thanks

**Comment by 0xERR0R** [comment]
http://ip:4000 is default. Ip address frim host where blocky runs

**Comment by caywin25** [comment]
Thank you @0xERR0R 

I have set http://<my ip>:4000 on grafana but I have still no graphics on dashboard.
And if I check my grafana logs, I can see : 

logger=tsdb.prometheus t=2022-10-15T12:54:00.791763742Z level=error msg="Exemplar query failed" query=sum(increase(blocky_error_total[300s])) err="client_error: client error: 404"
logger=tsdb.prometheus t=2022-10-15T12:54:00.793146236Z level=error msg="Exemplar query failed" query="sum(rate(blocky_prefetch_count[5m])) * 60" err="client_error: client error: 404"
logger=tsdb.prometheus t=2022-10-15T12:54:00.795124717Z level=error msg="Exemplar query failed" query=ceil(sum(increase(blocky_prefetch_count[300s]))) err="client_error: client error: 404"
logger=tsdb.prometheus t=2022-10-15T12:54:00.802549163Z level=error msg="Exemplar query failed" query="sum(increase(blocky_prefetch_hit_count[300s])) / (sum(increase(blocky_cache_hit_count[300s])))" err="client_error: client error: 404"
logger=tsdb.prometheus t=2022-10-15T12:54:00.841207015Z level=error msg="Exemplar query failed" query="sum(rate(blocky_query_total[5m])) * 60" err="client_error: client error: 404"
logger=tsdb.prometheus t=2022-10-15T12:54:00.845250487Z level=error msg="Exemplar query failed" query="sum(blocky_prefetch_domain_name_cache_count)/ sum(up{job=\"blocky\"})" err="client_error: client error: 404"
logger=tsdb.prometheus t=2022-10-15T12:54:00.856023564Z level=error msg="Exemplar query failed" query="sum by (client) (rate(blocky_query_total[5m])) * 60" err="client_error: client error: 404"

Could you help me please ?
thank you

**Comment by 0xERR0R** [comment]
You you see any blocky queries in prometheus?

**Comment by caywin25** [comment]
how can i see these queries please ?

**Comment by 0xERR0R** [comment]
you can try to open the prometheus web ui (default: host:9000) and then try to type "blocky". Did you configure blocky in prometheus as scraping source? Prometheus should collect blocky's metrics periodically.

**Comment by caywin25** [comment]
`Did you configure blocky in prometheus as scraping source?`
yes 

`you can try to open the prometheus web ui (default: host:9000) and then try to type "blocky".`
In prometheus, if I search blocky, I can see nothing :(

**Comment by caywin25** [comment]
In my config.yaml I can see : 

```
prometheus:
  # enabled if true
  enable: true
  # url path, optional (default '/metrics')
  path: /metrics
```

**Comment by 0xERR0R** [comment]
And in prometheus. I think it was rules.yaml. You should enter http://blocky-host:4000/metrics

**Comment by caywin25** [comment]
I have no rules.yml :(

```
/etc/prometheus$ ls
console_libraries  consoles  prometheus.yml
```

**Comment by caywin25** [comment]
I managed to put the blocky graphs in prometheus by following:
> https://github.com/0xERR0R/blocky-grafana-prometheus-example/blob/master/prometheus/prometheus.yml

But now when I go to prometheus, choose a blocky alert and click on graph I get: No datapoints found.

Thanks

**Comment by caywin25** [comment]
IT'S WORKED !!!!!!!!!!!!!!!!!!!!!
Thant you :)
