### ISSUE TITLE
(Feature Request) Allow blocky to handle dhcp

### ISSUE THREAD

**Issue by Dynasty-Dev** [0xERR0R/blocky#682]
Hello, I would like to deploy blocky in my home environment to replace pihole and adguard home but since my router does not allow me to change the dns server directly, I cannot point my devices to blocky. However I can disable the dhcp server running on my router. So I was wondering if you could add this feature since agh and pihole already have it?

**Comment by kwitsch** [comment]
It seams a bit out of the scope.

Why not just run dhcpd(or any other DHCP server) and let it point to your blocky instance?

**Comment by 0xERR0R** [comment]
I agree with @kwitsch, blocky focuses on DNS handling. All other aspects should be covered by another tools.

**Comment by devipasigner** [comment]
> I agree with @kwitsch, blocky focuses on DNS handling. All other aspects should be covered by another tools.

I have a question, if I’m running dhcp server on the same device as blocky, how can I setup  client names automatically?

**Comment by kwitsch** [comment]
Depends on your setup but will always require a DHCP service with rDNS support.

Assuming you install service natively either set the rDNS port to something other than 53 or bind the resolution interface to a specific IP in the loopback range.
After that add the configured ip/port to your blocky config for client lookup.

If you're using containers simply only expose the DHCP port in hostmode and use the service name as server in your blocky config.
