### ISSUE TITLE
blocky query grafana compatible with mariadb ?

### ISSUE THREAD

**Issue by caywin25** [0xERR0R/blocky#683]
Hello

I installed mariadb on my server, I configured blocky well to access mariadb.

I see my requests in mariadb but when I put the dashboard in grafana, I see the error:

```
db query error: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') and (length(') = 0 or INSTR(t.question_name, lower(')) > 0) grou...' at line 4
```

for each graph.
mariadb is compatible with blocky and grafana?

Thanks

**Comment by martadinata666** [comment]
#679

**Comment by caywin25** [comment]
Thank you @martadinata666

It works perfectly with grafana 9.1.7
Regards
