### ISSUE TITLE
About custom dns problem request

### ISSUE THREAD

**Issue by Ran-Xing** [0xERR0R/blocky#696]
Hello, I have a problem that has been bothering me for a long time, I hope you can help me

This is an issue I left with the original author, but the author has not replied to me at present, I am currently using a macos device

This simple dns I wrote can use dig but not nslookup, including curl and so on can not be resolved

This is a simple dns server, dig can be used, but nslookup can't be used, curl can't be used either https://gist.github.com/walm/0d67b4fb2d5daf3edd4fad3e13b162cb

https://github.com/miekg/dns/issues/1396

**Comment by Ran-Xing** [comment]
tks,very much

**Comment by Ran-Xing** [comment]
```log
dig +short nginx.docker.shared
127.0.0.3
```
---

```log
nslookup test.service
;; Got recursion not available from 127.0.0.1, trying next server
Server:		8.8.8.8
Address:	8.8.8.8#53

** server can't find test.service: NXDOMAIN
```

**Comment by kwitsch** [comment]
Do I get your code right and your server lists to port [5353](https://gist.github.com/walm/0d67b4fb2d5daf3edd4fad3e13b162cb#file-main-go-L49)?

Thus your nslookup should look more like `nslookup -port=5353 test.service 127.0.0.1` or am I missing something?

**Comment by Ran-Xing** [comment]
@kwitsch  https://github.com/XRSec/AUDCH/issues/3

thank you very much for your help，I am using port 53 and added 127.0.0.1 to /etc/resolv.conf

nslookup,dig can parse this dns request, but curl or wget or web browsing cannot parse it normally

```go
package main

import (
	"github.com/miekg/dns"
	log "github.com/sirupsen/logrus"
	"net"
	"strconv"
	"strings"
)

var records = map[string]string{
	"test.service": "192.168.0.2",
}

func handleDnsRequest(w dns.ResponseWriter, m *dns.Msg) {
	r := new(dns.Msg)
	r.SetReply(m)
	r.Compress = true
	r.Authoritative = true
	r.RecursionAvailable = true
	IPAddress := "NULL"
	Domain := strings.TrimRight(r.Question[0].Name, ".")

	defer func(w dns.ResponseWriter, msg *dns.Msg) {
		log.Infof("Query: [%v ? %s --> %v]\n", w.RemoteAddr(), Domain, IPAddress)
		err := w.WriteMsg(msg)
		if err != nil {
			log.Errorf("Error writing response: %v", err)
			return
		}
	}(w, r)

	// not resolve
	if r.Question[0].Qtype != dns.TypeA {
		r.Rcode = dns.RcodeNotImplemented
		return
	}
	if addr := records[Domain]; addr != "" {
		IPAddress = addr
		r.Answer = append(r.Answer, &dns.A{
			Hdr: dns.RR_Header{
				Name:   m.Question[0].Name,
				Rrtype: dns.TypeA,
				Class:  dns.ClassINET,
				Ttl:    uint32(86400),
			},
			A: net.ParseIP(IPAddress).To4(),
		})
	}

	if len(r.Answer) == 0 {
		r.Rcode = dns.RcodeNameError
	}
}

func main() {
	// attach request handler func
	dns.HandleFunc("service.", handleDnsRequest)

	// start server
	port := 53
	server := &dns.Server{Addr: ":" + strconv.Itoa(port), Net: "udp"}
	log.Printf("Starting at %d\n", port)
	err := server.ListenAndServe()
	defer server.Shutdown()
	if err != nil {
		log.Fatalf("Failed to start server: %s\n ", err.Error())
	}
}
```

**Comment by kwitsch** [comment]
Sorry currently only on mobile so can't provide propper support 😕

I wrote some simple DNS servers in the past so maybe get some inspiration there: https://github.com/kwitsch/OmadaSiteDns & https://github.com/kwitsch/TinyMacDns

**Comment by Ran-Xing** [comment]
@kwitsch tks，I'll come back and let you know when I fix the problem

**Comment by Ran-Xing** [comment]
https://github.com/kwitsch/TinyMacDns/blob/main/src/server/server.go#L82

doesn't seem to work，
I've read a lot of similar tools, I haven't tested Windows systems yet, maybe it's just macOS that doesn't work, but so far, dns dnsmessage doesn't work

```go
func dnsServer() {
	dns.HandleFunc("docker.shared.", func(w dns.ResponseWriter, m *dns.Msg) {
		HostNowPTR:=map[string]string{
			"nginx.docker.shared." : "192.168.0.1",
		}
		HostNowA:=map[string]string{
			"192.168.0.1" : "nginx.docker.shared.",
		}
		q := m.Question[0]
		r := new(dns.Msg)
		r.SetReply(m)

		r.Compress = true
		r.Authoritative = true
		r.RecursionAvailable = true

		IPAddress := "NULL"
		Domain := "NULL"

		// not resolve
		switch q.Qtype {
		case dns.TypeA:
			Domain = q.Name
			if v, ok := HostNowA[Domain]; ok {
				IPAddress = v
				rr := new(dns.A)
				rr.Hdr = dns.RR_Header{
					Name:   Domain,
					Rrtype: dns.TypeA,
					Class:  dns.ClassINET,
					Ttl:    uint32(86400),
				}
				rr.A = net.ParseIP(v)
				r.Answer = []dns.RR{rr}
			} else {
				r.Rcode = dns.RcodeNameError
			}
			if err := w.WriteMsg(r); err != nil {
				log.Errorf("Error writing response: %v", err)
				return
			}
			log.Infof("QueryA: [%v ? %s --> %v]\n", w.RemoteAddr(), Domain, IPAddress)
		case dns.TypePTR:
			IPAddress = strings.TrimSuffix(q.Name, rdnsSuf)
			if v, ok := HostNowPTR[IPAddress]; ok {
				Domain = v
				rr := new(dns.PTR)
				rr.Hdr = dns.RR_Header{
					Name:   Domain,
					Rrtype: dns.TypePTR,
					Class:  dns.ClassINET,
					Ttl:    uint32(86400),
				}
				rr.Ptr = fmt.Sprintf("%s.", v)
				r.Answer = []dns.RR{rr}
			} else {
				r.Rcode = dns.RcodeNameError
			}
			if err := w.WriteMsg(r); err != nil {
				log.Errorf("Error writing response: %v", err)
				return
			}
			log.Infof("QueryPTR: [%v ? %s --> %v]\n", w.RemoteAddr(), IPAddress, Domain)
		}
		//
		//if len(r.Answer) == 0 {
		//	r.Rcode = dns.RcodeNameError
		//}
	})
	// start server
	udpServer := &dns.Server{Addr: ":53", Net: "udp"}
	log.Printf("Starting at %v\n", udpServer.Addr)
	if err := udpServer.ListenAndServe(); err != nil {
		log.Fatalf("Failed to setup the udp server: %s\n", err.Error())
	}

	defer func(udpServer *dns.Server) {
		err := udpServer.Shutdown()
		if err != nil {
			log.Errorf("Failed to shutdown the udp server: %s\n", err.Error())
			return
		}
	}(udpServer)
}
```

**Comment by vincentvignali** [comment]
I am having the same issue here.
`dig`, `host`, `nslookup`all work fine. 

However when it comes to `curl`, `wget` and eventually any browser I got an an error.
I.e. with `curl` => `curl: (6) Could not resolve host:` 
I am also on macOs. My etc/resolv.conf does show correctly my local dns resolver at 127.0.0.1. 

Apart form that, thanks for your work on that lib. It's great ! :)

**Comment by Ran-Xing** [comment]
@vincentvignali +1+1

**Comment by kwitsch** [comment]
Just noticed:
> ```go
> 		HostNowA:=map[string]string{
> 			"192.168.0.1" : "nginx.docker.shared.",
> 		}
> ...
> 			if v, ok := HostNowA[Domain]; ok {
> ```
Isn't the map te wrong way around? 🤔

**Comment by Ran-Xing** [comment]
@kwitsch 
HostNowA:=map[string]string{
			"nginx.docker.shared." : "192.168.0.1",
		}
HostNowPTR:=map[string]string{
	"192.168.0.1" : "nginx.docker.shared.",
}

😂

**Comment by kwitsch** [comment]
> @kwitsch 
> HostNowA:=map[string]string{
> 			"nginx.docker.shared." : "192.168.0.1",
> 		}
> HostNowPTR:=map[string]string{
> 	"192.168.0.1" : "nginx.docker.shared.",
> }
> 
> 😂

Sry just got the previous issue update mail and got confused by it 😅

**Comment by Ran-Xing** [comment]
@kwitsch I have studied that library, and there is this problem，
make/dns
gogolexxxx/dns
golang.org/dnsxxxx

**Comment by kwitsch** [comment]
> @kwitsch I have studied that library, and there is this problem，
> make/dns
> gogolexxxx/dns
> golang.org/dnsxxxx

Sorry guess it's a bit late...I don't get it 😖
Will look into it tomorrow.

**Comment by Ran-Xing** [comment]
@kwitsch 
https://github.com/miekg/dns
https://pkg.go.dev/golang.org/x/net/dns/dnsmessage
https://pkg.go.dev/google.golang.org/api/dns/v1

**Comment by kwitsch** [comment]
> @kwitsch https://github.com/miekg/dns https://pkg.go.dev/golang.org/x/net/dns/dnsmessage https://pkg.go.dev/google.golang.org/api/dns/v1

Ok still don't get where you think it breaks.
Blocky(and all of my projects) use miekg/dns without a problem...

But did you assign the HandleFunc correctly to your server?
...it's not done in your example `udpServer := &dns.Server{Addr: ":53", Net: "udp"}`...

**Comment by Ran-Xing** [comment]
1. https://github.com/XRSec/AUDCH/blob/ca334eb78f729b935812d05c648724359c0cb306/main.go#L270
2. https://github.com/XRSec/AUDCH/blob/dev/docs/Deprecated.md#dnsserver

I'm pretty sure I did, and I wouldn't mind uploading my existing code to github to explore with you if you're interested!

https://tucdn.wpon.cn/api-girl/index.php?wpon=302

have a good time🤣
