### ISSUE TITLE
CNAME suggestion..

### ISSUE THREAD

**Issue by bcookatpcsd** [0xERR0R/blocky#697]
I think this is different that ticket 411.. 

I need a cname for google and other not internal domains.. 

https://support.google.com/websearch/answer/186669?hl=en

Migrating back to dnscrypt-proxy but will probably chain blocky to dnscrypt.. 

https://github.com/DNSCrypt/dnscrypt-proxy/blob/master/dnscrypt-proxy/example-cloaking-rules.txt

Thank you in advance.

**Comment by kwitsch** [comment]
As far as I remember there was a PR that allowed to define rewrite only customDNS mappings.
If I remember correct the current development version should support it.

Would this solve your issue?

**Comment by kwitsch** [comment]
In [449](https://github.com/0xERR0R/blocky/pull/449) the rewrite resolver was introduced as seperate resolver.
Before the rewrite handling was part of the conditional resolver.

As far as I remember this also qualified it to be usable as  standalone config.
Didn't test it though so I'm sorry if this isn't correct 😅

**Comment by ThinkChaos** [comment]
Can confirm I use the rewrite resolver without the conditional one!
