### ISSUE TITLE
Extension request: Use Clearurls ruleset in order to reduce tracking

### ISSUE THREAD

**Issue by GUNT0815** [0xERR0R/blocky#704]
Google and others use tracking urls. It would be a good extension to blocky to clear the urls from the tracking part before the dns resolve.

ClearUrls publishes the used ruleset here:

https://rules2.clearurls.xyz/data.minify.json

So the idea is, that blocky receives the dns request, processes the url clearance based on the ruleset and then filters or resolves the url to ip.

**Comment by ThinkChaos** [comment]
DNS never sees the full URL when you use HTTP(S): it only gets the hostname. So unless I'm misunderstanding this information doesn't leak via DNS and there's no way for Blocky to prevent the HTTP client to send it to the HTTP server.

That being said I use the ClearURLs browser extension and it's great!

**Comment by kwitsch** [comment]
Looked into it and this seems to be out of the scope for a DNS server.

Would be a great extension for a proxy server though.

**Comment by 0xERR0R** [comment]
As mentioned by @ThinkChaos and @kwitsch this is not something we can implement in blocky
