### ISSUE TITLE
development branch is built for amd64 only

### ISSUE THREAD

**Issue by GitSchorsch** [0xERR0R/blocky#725]
Branch development is built for linux/amd64 only. So after pulling spx01/blocky:development on my Raspi, blocky breaks with:

standard_init_linux.go:219: exec user process caused: exec format error

**Comment by 0xERR0R** [comment]
development tag @ghcr.io looks ok (multiarch build), only hub.docker.io is broken.

@kwitsch: It looks like we build multiarch images once for ghcr.io in "Build and push" workflow step. In "Retag" only one architecture image will be pulled and "copied" to docker hub. Do we need this "Retag" step? I think it should be possible to push to multiple registries (multiple tags) in "Build and push"

**Comment by kwitsch** [comment]
Sorry my fault.
If wie push to multiple repositories this will only work on the main repo(no fork builds will be possible).
I'll fix the retag bug.

**Comment by kwitsch** [comment]
Sorry closed the issue to early.

development tag is fixed:
![image](https://user-images.githubusercontent.com/10324063/200147033-bddab5ad-0e58-4676-ab57-d50e2ed88aaa.png)
