### ISSUE TITLE
https://hosts-file.net/ad_servers.txt is not available anymore

### ISSUE THREAD

**Issue by runningman84** [0xERR0R/blocky#73]
I would advice to remove this from the sample config... According to the thread it is not available anymore:

https://www.reddit.com/r/pihole/comments/fvqaad/hostsfilenet_ad_serverstxt_download_not_availabe/

Maybe this list is a good alternative:

https://gitlab.com/ookangzheng/dbl-oisd-nl/raw/master/dbl.txt

**Comment by runningman84** [comment]
btw. the alternative is way too big... I got docker oom kills with my 128MB limit using it...

**Comment by 0xERR0R** [comment]
Thanks for hint, I'll remove this list from readme. Btw: in wiki is a list with some links to block lists (https://github.com/0xERR0R/blocky/wiki/List-sources). Feel free to use one from this list or contribute if you find some useful links.
