### ISSUE TITLE
use one branch for development

### ISSUE THREAD

**Issue by 0xERR0R** [0xERR0R/blocky#744]
Currently we use "development" branch for development (PR merging etc). "master" contains the latest released version. Blockys documentation is built from "master". This is the reason, why do we need 2 branches.

Handling of 2 branches is not really "handy". Since mkdocs can also produce versioned documentation (https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/) -> maybe we should drop the "development" branch and work only on "master".

**Comment by kwitsch** [comment]
Creating documentation versions for each release sounds good. 👍

Developing on master is just a style choice. 🤷‍♂️
If it helps streamlining processes we should go for it.

**Comment by 0xERR0R** [comment]
@kwitsch @ThinkChaos @FileGo I set "master" as default branch and I'll remove the "development" branch soon

**Comment by kwitsch** [comment]
I'm also in favor of `main`.

**Comment by 0xERR0R** [comment]
ok, I'll rename it to "main"

**Comment by 0xERR0R** [comment]
Branch was renamed. I activated the versioning. https://0xerr0r.github.io/blocky shows currently to v0.20. Each commit on main will also create a new doc version "main", but this is not the latest version (which is shown by default).

**Comment by ThinkChaos** [comment]
Maybe it's too early for that but we could delete the development branch, so anything depending on it will fail and we'll (and others) will notice.

**Comment by 0xERR0R** [comment]
There was one open PR on the development branch, but it was closed in the mean time. I'll delete the branch tomorrow
