### ISSUE TITLE
"Error 1060: Duplicate column name 'id'" at startup

### ISSUE THREAD

**Issue by pg1261** [0xERR0R/blocky#768]
Hi,

there is an info during startup. Is there anything to do?

`[2022-11-24 22:08:40]  INFO /go/pkg/mod/gorm.io/gorm@v1.24.1-0.20221019064659-5dd2bb482755/callbacks.go:134 Error 1060: Duplicate column name 'id'
[63.005ms] [rows:0] ALTER TABLE 'log_entries' ADD 'id' INT PRIMARY KEY AUTO_INCREMENT`

br

**Comment by kwitsch** [comment]
It seams your configuration uses MySQL which [doesn't support "add column if not exist"](https://github.com/0xERR0R/blocky/blob/development/querylog/database_writer.go#L101) therfore blocky tries to create the column at every start to garantee that it exists.
The table itself should be correct so you could eighter ignore this info or switch to postgres. 😉

**Comment by pg1261** [comment]
Thx. The table itself is correct.

Should I better use Postgres?

**Comment by kwitsch** [comment]
I myself currently dont't use query logging so I can't advise one database over another in this particular scenario.

Most of my colleges prefer postgres over mysql performance wise though.

**Comment by 0xERR0R** [comment]
This message is OK. Blocky tries to create the id column. If this column exists, the error "1060" is catched (see https://github.com/0xERR0R/blocky/blob/development/querylog/database_writer.go#L102).

Loglevel from the database is set to "warning", I'm wondering why you are getting this "info" message :thinking:

**Comment by pg1261** [comment]
I have now tried PostgreSQL. In my environment it works as good or bad as a MySQL/MariaDB. Since I already have other MariaDBs in use, I keep my landscape homogeneous.

Thanks for the effort and the clarification.
