### ISSUE TITLE
AdBlock Syntax Support for filterlists.

### ISSUE THREAD

**Issue by Dynasty-Dev** [0xERR0R/blocky#770]
Hello, I am a new blocky user who recently came from AdGuard Home just to try it out. I realized that it doesn’t have AdBlock syntax support for filterlists(blocklists, whitelists) like AdGuard Home does. That’s why I am opening this feature request, I think it would be great if blocky supported this syntax because it allows for smaller file size (Using pattern matching allows you to have a single rule instead of hundreds of /etc/hosts entries), more blocklist compatibility, and more extensibility. If you are worried about false positives, don’t, I didn’t find one false positive in my 2 years of AdGuard home and never saw anyone complain either.

Some examples: 

||example.org^: block access to the example.org domain and all its subdomains, like www.example.org.

@@||example.org^: unblock access to the example.org domain and all its subdomains.

||example.org^$important: blocks the domain even if it’s found in a whitelist

@@||example.org^$important: allows domain even if it’s found in a blocklist

1.2.3.4 example.org: (attention, old /etc/hosts-style syntax) respond with 1.2.3.4 to queries for the example.org domain but not its subdomains. www.example.org remains allowed.

**Comment by kwitsch** [comment]
The current implementation of blocky would block all subdomains of a domain defined in host style syntax if loaded as blocklist. 
Therfore `1.2.3.4 example.org` would also block `www.example.org` if loaded by blocky. 
The defined ip `1.2.3.4` isbe ignored and replaced with the configured blocking option. 
 
The adblock syntax mixes block and allow lists this would require a significant rework of the list loading process because currently there is a strict differentiation of block and allow lists. 

Is there currently an explicit use case where only a lis in adblock and no host or domain name syntax is provided?

**Comment by 0xERR0R** [comment]
> The current implementation of blocky would block all subdomains of a domain defined in host style syntax if loaded as blocklist.

No, domains from the blacklist will be matched exact. "example.org" would only block "example.org" and not "www.example.org"

**Comment by kwitsch** [comment]
> > The current implementation of blocky would block all subdomains of a domain defined in host style syntax if loaded as blocklist.
> 
> No, domains from the blacklist will be matched exact. "example.org" would only block "example.org" and not "www.example.org"

Sorry my bad, got it wrong. 🤦‍♂️

**Comment by 0xERR0R** [comment]
> Hello, I am a new blocky user who recently came from AdGuard Home just to try it out. I realized that it doesn’t have AdBlock syntax support for filterlists(blocklists, whitelists) like AdGuard Home does. That’s why I am opening this feature request, I think it would be great if blocky supported this syntax because it allows for smaller file size (Using pattern matching allows you to have a single rule instead of hundreds of /etc/hosts entries), more blocklist compatibility, and more extensibility. If you are worried about false positives, don’t, I didn’t find one false positive in my 2 years of AdGuard home and never saw anyone complain either.
> 
> Some examples:
> 
> ||example.org^: block access to the example.org domain and all its subdomains, like [www.example.org](http://www.example.org).
> 
> @@||example.org^: unblock access to the example.org domain and all its subdomains.
> 
> ||example.org^$important: blocks the domain even if it’s found in a whitelist
> 
> @@||example.org^$important: allows domain even if it’s found in a blocklist
> 
> 1.2.3.4 example.org: (attention, old /etc/hosts-style syntax) respond with 1.2.3.4 to queries for the example.org domain but not its subdomains. [www.example.org](http://www.example.org) remains allowed.

Currently we support either domain lists (plain domains or hosts format) or regex for more complex scenarios. Both for blacklists and whitelists.

Adblock syntax combines white and blacklist handling in a single list definitions. AFAIK adblock format was made for browser extension which has access to the full url and not just domain name. 

From https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters:

> Originally, the AdGuard's syntax was based on the syntax of Adblock Plus rules. Later, we extended it with new types of rules for better ad filtering

That means, there is own rule definition from Adguard team and I don't think, we should adopt their implementation.

**Comment by kwitsch** [comment]
As stated by @0xERR0R the Adguard syntax won't be implemented.
