### ISSUE TITLE
Documentation of config.yml file not correct anymore

### ISSUE THREAD

**Issue by adb76** [0xERR0R/blocky#80]
Based on the description in README.md
```
upstream:
    # these external DNS resolvers will be used. Blocky picks 2 random resolvers from the list for each query
    # format for resolver: [net:]host:[port][/path]. net could be empty (default, shortcut for tcp+udp), tcp+udp, tcp, udp, tcp-tls or https (DoH). If port is empty, default port will be used (53 for udp and tcp, 853 for tcp-tls, 443 for https (Doh))
  
```
I tried the configuration as described above:
```
     externalResolvers:  
       - 46.182.19.48
       - 80.241.218.68
```
This leads to the following error when starting blocky:
`  level=fatal msg="wrong file structure: wrong configuration, couldn't parse input '46.182.19.48', please enter net:host[:port][/path]"`

So "net:" is not optional anymore. Right?

Changing the config to 
```
     externalResolvers:  
       - tcp:46.182.19.48
       - tcp.80.241.218.68
```
solved the problem.

Especially for new users it would be great to adapt the documentation.

**Comment by dulfox** [comment]
Could you also provide the config.yml as a file directly ?

**Comment by 0xERR0R** [comment]
Configuration and Readme was changed with #67 (Version 0.9), but not released yet. I'll release 0.9 this week

**Comment by 0xERR0R** [comment]
@dulfox: This, this is a good idea, I'll extract configuration from readme to a separate file
