### ISSUE TITLE
Blocklist download errors

### ISSUE THREAD

**Issue by AAraonWPaul** [0xERR0R/blocky#845]
When blocky starts, it downloads the blocklists. However I get these weird errors, is this normal?

Jan 25 14:47:42 dserv blocky[1006]: [2023-01-25 14:47:42]  INFO _/                                                              _/
Jan 25 14:47:42 dserv blocky[1006]: [2023-01-25 14:47:42]  INFO _/                                                              _/
Jan 25 14:47:42 dserv blocky[1006]: [2023-01-25 14:47:42]  INFO _/  Version: 0.20               Build time: 20221112-205029     _/
Jan 25 14:47:42 dserv blocky[1006]: [2023-01-25 14:47:42]  INFO _/                                                              _/
Jan 25 14:47:42 dserv blocky[1006]: [2023-01-25 14:47:42]  INFO _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/
Jan 25 14:47:42 dserv blocky[1006]: [2023-01-25 14:47:42]  INFO list_cache: starting download link=https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/tif.txt
Jan 25 14:47:42 dserv blocky[1006]: [2023-01-25 14:47:42]  INFO list_cache: starting download link=https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/dyndns.txt
Jan 25 14:47:42 dserv blocky[1006]: [2023-01-25 14:47:42]  WARN list_cache: Can't download file: Get "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/dyndns.txt": dial tcp [2606:50c0:8002::154]:443: connect: network is unreachable attempt=1/3 link=https://raw.githubusercontent.com/hagezi/dns-b>
Jan 25 14:47:43 dserv blocky[1006]: [2023-01-25 14:47:43]  WARN list_cache: Can't download file: Get "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/dyndns.txt": dial tcp [2606:50c0:8003::154]:443: connect: network is unreachable attempt=2/3 link=https://raw.githubusercontent.com/hagezi/dns-b>
Jan 25 14:47:45 dserv blocky[1006]: [2023-01-25 14:47:45]  INFO list_cache: file imported count=793 source=https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/dyndns.txt

**Comment by dacioromero** [comment]
I was also just experiencing this, disabling my `bootstrapDns` seems to have fixed it though

**Comment by kwitsch** [comment]
Looks like the download starts before the network is fully up.

Do you use a container solution or a native installation?
