### ISSUE TITLE
Grafana dashboard buttons not loading

### ISSUE THREAD

**Issue by AAraonWPaul** [0xERR0R/blocky#846]
Using: https://grafana.com/grafana/dashboards/13768-blocky/

![image](https://user-images.githubusercontent.com/105821894/214704904-8a2129a1-20e0-4b59-aec1-9b810ee48c51.png)

**Comment by deliantwo** [comment]
Hi, just a check, have you disabled html sanitize as mentioned in the [guide](https://0xerr0r.github.io/blocky/prometheus_grafana/)?

**Comment by 0xERR0R** [comment]
As @deliantwo mentioned, did you set `disable-sanitize-html` in your Grafana config?
