### ISSUE TITLE
Blocking Not In Effect Until Manual Refresh

### ISSUE THREAD

**Issue by n8x0b7T** [0xERR0R/blocky#863]
When the service is first started after a device reboot, no domains are blocked. When I trigger a manual refresh, the blocking takes effect. I would assume it would auto refresh after 4 hours (the default refresh interval). 
Is there a way to cache the blacklists on disk so it will be in effect after a system restart (I know its supposed to be stateless)?
Or, Is there an easy way to ensure the lists get loaded after a reboot?

**Comment by 0xERR0R** [comment]
Blocky performs list refresh on startup. Did you see any errors in the log?

**Comment by n8x0b7T** [comment]
Thanks for your response. I found the issue by setting `bootstrapDns` in the config.
