### ISSUE TITLE
MariaDB / Query SQL Dashboard "No Data"

### ISSUE THREAD

**Issue by padey** [0xERR0R/blocky#892]
Hi. I have the problem that my dashboard does not provide any data for the queries:

![image](https://user-images.githubusercontent.com/48521852/220414474-bc4a4688-aa6d-4b93-8733-1ce7f992faf5.png)

Blocky writes data to the database, I checked this via Grafana and directly on the MariaDB:

![image](https://user-images.githubusercontent.com/48521852/220414397-78584bad-160b-4de7-b45f-4f258000ec82.png)

I have the feeling that the SQL queries no longer fit the latest version.
I'm using:
- Grafana 9.3.6
- newest Version of MariaDB
- Blocky v.20 (Docker)

Any ideas?

**Comment by padey** [comment]
I have no idea why.. but now it works.

**Comment by johnmmcgee** [comment]
@padey about how long did it take for it to work? I am seeing the same issue.

**Comment by Sporif** [comment]
This seems to be a timezone issue. I fixed it by setting the `TZ` environment variable in the MariaDB container.
