### ISSUE TITLE
Add support for Google SafeSearch

### ISSUE THREAD

**Issue by onovy** [0xERR0R/blocky#896]
Docs: https://support.google.com/websearch/answer/186669?hl=en

I would like to enable DNS-based Google SafeSearch for selected users. Similar function exists for other search engines, see:
https://adguardteam.github.io/HostlistsRegistry/assets/engines_safe_search.txt

To enable it I need one of (per client ID):
* Rewrite all DNS request to "google.com" to "forcesafesearch.google.com" (customDNS rewrite per client ID?)
or
* Manually set IP of google.com to 216.239.38.120 / 2001:4860:4802:32::78 (hostsFile per client ID?)

Thanks.

**Comment by justinmartin** [comment]
I would like to add  a vote for this feature as well
