### ISSUE TITLE
[enhancement] clientGroupsBlock support CIDR

### ISSUE THREAD

**Issue by krohrsb** [0xERR0R/blocky#90]
Curious if clientGroupsBlock can support CIDR in addition to client name or specific ip?

Would be great to be able to apply a list to a specific subnet.

**Comment by 0xERR0R** [comment]
Currently, only IP address or client's host name is supported. Mapping to IP range (or even subnet) could be useful.

**Comment by krohrsb** [comment]
Great! Blocky was the only decent solution I found in my local k3s setup that was friendly to high availability, so thanks for it.
