### ISSUE TITLE
DNS interface changes after first request

### ISSUE THREAD

**Issue by sbaildon** [0xERR0R/blocky#921]
I'm trying to bind my DNS interface to `127.0.0.1`, but it's changing to `0.0.0.0` after the first request to the server. I'm on macOS

<pre>
~: lsof -i UDP:15353
COMMAND  PID     USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
blocky  9226 sbaildon   10u  IPv4 0x889bed305023383d      0t0  UDP <strong>localhost</strong>:15353

~: doggo google.com @udp://127.0.0.1:15353
NAME       	TYPE	CLASS	TTL 	ADDRESS       	NAMESERVER      
google.com.	A   	IN   	113s	172.217.169.46	127.0.0.1:15353	

~: lsof -i UDP:15353
COMMAND  PID     USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
blocky  9226 sbaildon   10u  IPv4 0x889bed305023383d      0t0  UDP <strong>*</strong>:15353
</pre>

<details>
<summary>minimal replication</summary>

```yaml
# config.yml
ports:
  dns: 127.0.0.1:15353
upstream:
  default:
    - 1.1.1.1

```

```bash
make run

```

</details>

**Comment by kwitsch** [comment]
Unfortunately I don't know anything about macOS but could it be a privilege issue like `setcap 'cap_net_bind_service=+ep'`?

**Comment by sbaildon** [comment]
macOS doesn't support capabilities like that; also it's strange behaviour for a process to become _more_ permissive

**Comment by sinamombeiny** [comment]
i mean how you install it on macOS?

**Comment by 0xERR0R** [comment]
I can't reproduce it (Linux, Ubuntu VM), binary build from source (v0.21):
```sh
abc@e90468c788f8:~$ lsof -i UDP:15353
COMMAND    PID USER   FD   TYPE    DEVICE SIZE/OFF NODE NAME
blocky  339386  abc    7u  IPv4 368157441      0t0  UDP localhost:15353 
abc@e90468c788f8:~$ dig @localhost -p 15353 google.com

; <<>> DiG 9.18.1-1ubuntu1.3-Ubuntu <<>> @localhost -p 15353 google.com
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 63799
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;google.com.                    IN      A

;; ANSWER SECTION:
google.com.             121     IN      A       142.250.180.174

;; Query time: 8 msec
;; SERVER: 127.0.0.1#15353(localhost) (UDP)
;; WHEN: Wed Mar 29 09:16:53 CEST 2023
;; MSG SIZE  rcvd: 55

abc@e90468c788f8:~$ lsof -i UDP:15353
COMMAND    PID USER   FD   TYPE    DEVICE SIZE/OFF NODE NAME
blocky  339386  abc    7u  IPv4 368157441      0t0  UDP localhost:15353 
```
