### ISSUE TITLE
Output log to file

### ISSUE THREAD

**Issue by broizter** [0xERR0R/blocky#93]
Maybe I'm missing something but there doesn't seem to be a way to log errors etc to a file?

```
# optional: Log level (one from debug, info, warn, error). Default: info
logLevel: info
# optional: Log format (text or json). Default: text
logFormat: text
```

Ideally I would like something like this to be added:

```
logFile: /var/log/blocky.log
```

**Comment by 0xERR0R** [comment]
blocky writes logs to stdout, you can just redirect the output to a file. A configuration property would be in deed nice.

**Comment by nicolas-martin** [comment]
I would also like to ability to reroute blocky's logs to a separate file so it doesn't clutter my own apps logs. It seems like the loglevel config is being overwritten by my app's log level also. The simplest solution would be to pass our own logger as a parameter to the constructor.

**Comment by 0xERR0R** [comment]
After long consideration, I decided to close this issue and NOT to implement this request. Reason: writing to a file is technically not a big problem, but there are many obstacles, which can cause an error and must be handled: Running of out space, log rotation (who is responsible?), handling of closed file descriptors after a log rotation, naming convention for the log file etc.

I would like to avoid this complexity and move this "problem" to the caller: blocky logs to stdout and it can be easily redirected to a file (just one file, one per day etc). Please use a wrapper script which creates this log file and performs log rotation and house keeping if needed.

Please reopen, if you need support.

**Comment by nicolas-martin** [comment]
Is there a way to silence blocky's logs completely? Like I mentioned above, the logrus global instance is being set by our app. So it overrides blocky's loglevel. If I increase our loglevel to `trace` even if blocky's is set to `error`, I see all the DNS requests and it's far too noisy.

**Comment by nicolas-martin** [comment]
After looking at the code closely, configure log is only called in [`root.go`](https://github.com/0xERR0R/blocky/blob/development/cmd/root.go#L92) , however we start blocky by calling [`NewServer`](https://github.com/0xERR0R/blocky/blob/development/server/server.go#L46) which never calls configure log

**Comment by PeterDaveHello** [comment]
I'll vote for this feature if I may, though there might be disk space, log rotate issues, the log is still important to debug and help sysadmin to understand what's going on with it, of course, we can manually pipe to stdout to a file, but that'll be not so direct, DNS service as an important daemon on the system, I believe having log would be pretty helpful, just like most of thost common unix-like daemon services will do ;)

**Comment by 0xERR0R** [comment]
> I'll vote for this feature if I may, though there might be disk space, log rotate issues, the log is still important to debug and help sysadmin to understand what's going on with it, of course, we can manually pipe to stdout to a file, but that'll be not so direct, DNS service as an important daemon on the system, I believe having log would be pretty helpful, just like most of thost common unix-like daemon services will do ;)

Is it not the best practice (for example in systemd or 12-factor apps / k8s) to write to stdout/stderr? I think systemd supports it and redirects the log output automatically to the journal?
