### ISSUE TITLE
Cache metrics for Prometheus

### ISSUE THREAD

**Issue by delucks** [0xERR0R/blocky#94]
Hello, thank you for writing this software! It is very useful and performant so far. One enhancement that comes to mind is adding metrics about the cache feature. When the cache is configured it would be useful to see metrics related to its use and performance, such as:

* Cache hit counter
* Cache miss counter
* Cache miss ratio
* Cache entry count

**Comment by 0xERR0R** [comment]
Added 3 new metrics:
- blocky_cache_entry_count - Count of all entries in the cache
- blocky_cache_hit_count - total cache hit count
- blocky_cache_miss_count -  total cache miss count

Added also 2 Panels to Grafana dashboard: Stats for entry count and hit/miss ration (calculated as `sum(increase(blocky_cache_hit_count[24h])) / (sum(increase(blocky_cache_hit_count[24h])) + sum(increase(blocky_cache_miss_count[24h])))`
