### ISSUE TITLE
cache problem

### ISSUE THREAD

**Issue by liang-hiwin** [0xERR0R/blocky#958]
Will the cache cache the subnet IP of the client?

**Comment by kwitsch** [comment]
In the response cache only the actual DNS response is stored. This doesn't contain any IP information of the requesting client.

If you have configured hostname resolution the IP to hostname mapping is stored in a separate cache.

These two caches don't interact with each other.

**Comment by liang-hiwin** [comment]
> In the response cache only the actual DNS response is stored. This doesn't contain any IP information of the requesting client.
> 
> If you have configured hostname resolution the IP to hostname mapping is stored in a separate cache.
> 
> These two caches don't interact with each other.

If the client's subnet ip is not cached, won't it affect the parsing effect?

**Comment by liang-hiwin** [comment]
For example, if I am in Singapore, a certain domain name is resolved to Japan. If the domain name ip corresponding to the client subnet ip is cached, it will be given to Singapore’s ip.

**Comment by kwitsch** [comment]
I don't quite understand the problem to be honest. 😅

The client IP isn't forwarded to the upstream resolver.
The resolution in your example is based on the IP of your blocky instance.

**Comment by liang-hiwin** [comment]
Cache support https://datatracker.ietf.org/doc/html/rfc7871 ？

**Comment by kwitsch** [comment]
Ok got it.

This feature is not implemented so far.

**Comment by kwitsch** [comment]
Duplicate to #951
