### ISSUE TITLE
Question: response_type=SPECIAL (Unicast DNS-SD)

### ISSUE THREAD

**Issue by bcookatpcsd** [0xERR0R/blocky#959]
```
INFO queryLog: query resolved answer= client_ip=10.20.250.18 client_names=10.20.250.18 duration_ms=0 hostname=arch0829-98f219 question_name=lb._dns-sd._udp.0.48.168.192.in-addr.arpa. question_type=PTR response_code=NXDOMAIN response_reason=Special-Use Domain Name response_type=SPECIAL
```

```
blocky
Version: v0.21-4-g30ead04
Build time: 20230328-104831
Architecture: amd64
```

Is this correct? 

I understand the query (iphone in this case) but is it correct for the logs to say 'SPECIAL'.. 

 drill -t ptr lb._dns-sd._udp.0.48.168.192.in-addr.arpa. @10.20.8.29

INFO queryLog: query resolved answer= client_ip=10.20.8.29 client_names=10.20.8.29 duration_ms=0 hostname=arch0829-98f219 question_name=lb._dns-sd._udp.0.48.168.192.in-addr.arpa. question_type=PTR response_code=NXDOMAIN response_reason=CACHED NEGATIVE response_type=CACHED

Thank you in advance.

**Comment by kwitsch** [comment]
Yes that is correct.

Unless you haven't configured a conditional upstream resolver for ARPA requests these are blocked.
Otherwise these requests would be sent to your upstream resolvers which is prohibited by some RFCs.
Special Domain Name resolution is done here: https://github.com/0xERR0R/blocky/blob/main/resolver/sudn_resolver.go

**Comment by bcookatpcsd** [comment]
Cool.. 

I understand the reasoning.. Thank you for the response.. 

Along the same lines as this.. dnscrypt-proxy has an "undelegated" (somewhat like bogons..) 

I've not checked for updates.. but last commit was 2019.. 

Might be a good starting point for 'more'.. 

https://github.com/DNSCrypt/dnscrypt-proxy/blob/master/dnscrypt-proxy/plugin_block_undelegated.go
