### ISSUE TITLE
just allow defined clientid's

### ISSUE THREAD

**Issue by celevra** [0xERR0R/blocky#969]
Hi,

is there a way to just allow predefined clientid's via dns-tls?

regards

**Comment by 0xERR0R** [comment]
Do you want to pass the client ID with the DoT Url? If yes -> it is possible, see https://0xerr0r.github.io/blocky/v0.21/configuration/#resolving-client-name-from-urlhost

**Comment by celevra** [comment]
no the question is to only answer requests from specific clientid's

**Comment by celevra** [comment]
Yes could be a loadbalace feature but blocky could not read client id's from tls loadbalancers












Von: Kwitsch ***@***.***>
Gesendet: Dienstag, 4. April 2023 09:02
An: 0xERR0R/blocky
Cc: Philipp Zeitschel; Author
Betreff: Re: [0xERR0R/blocky] just allow defined clientid's (Issue #969) 






Like a filter over the called DoT/DoH URL?
Isn't that more of a loadbalancer feature since it should only be blocked?
—
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
You are receiving this because you authored the thread.Message
 ID: ***@***.***>

**Comment by celevra** [comment]
yes reject queries from "unknown" clients
