### ISSUE TITLE
REQUEST: Adblocker style of list

### ISSUE THREAD

**Issue by johnmmcgee** [0xERR0R/blocky#971]
Very low priority request, not even sure if we could do this but it would be cool.

Could we get support to allow Adblocker style of list?

https://adguard.com/kb/general/ad-filtering/create-own-filters/

example list:
https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters

**Comment by 0xERR0R** [comment]
Blocky can only block domain names (DNS requests). Your example list uses also URLs (like `||piano.io/xbuilder/experience/execute$xmlhttprequest,third-party`). To use it properly you need to use some browser addons.

**Comment by 0xERR0R** [comment]
Yes, it would be partial possible, but not for all cases.

**Comment by kwitsch** [comment]
Absolutely but we could add some compatibility to make it easier for new users.

Don't know if it's worth it tho. 😅

**Comment by ThinkChaos** [comment]
Closing this in favor of #950 as that mentions adblocker syntax, and others.  
Please re-open if you think we should keep a separate issue.

**Comment by johnmmcgee** [comment]
> Closing this in favor of #950 as that mentions adblocker syntax, and others. Please re-open if you think we should keep a separate issue.

works for me.  thanks for considering my request :)
