### ISSUE TITLE
[Request] Create` upstream` field in the logs

### ISSUE THREAD

**Issue by yellowhat** [0xERR0R/blocky#973]
Hi,
consider the following example from the logs:

```json
{
    "answer": "AAAA (2a00:1450:400f:800::2003)",
    "client_ip": "192.168.178.22",
    "client_names": "test",
    "duration_ms": 29,
    "hostname": "blocky-7dd7f4b47f-9n2lj",
    "level": "info",
    "msg": "query resolved",
    "prefix": "queryLog",
    "question_name": "ssl.gstatic.com.",
    "question_type": "AAAA",
    "response_code": "NOERROR",
    "response_reason": "RESOLVED (https://unicast.uncensoreddns.org/dns-query)",
    "response_type": "RESOLVED",
    "time": "2023-04-01T09:10:36Z"
}
```

I am not sure why `response_reason` contains `response_type`, is there a case where they can be different?

Apart that it would be great if the `upstream` used for the dns resolution has it is own field, like:
  
```json
    "response_upstream": "https://unicast.uncensoreddns.org/dns-query",
    "response_type": "RESOLVED"
```

It would simplify the data parsing for that specific field.

Thanks

**Comment by kwitsch** [comment]
Those fields aren't really connected.
`response_reason` is a human readable message 
`response_type` is an enum which control some internal handling of the response 

Simply splitting them isn't reasonable.
Adding another field for upstream should be doable even if it would be empty most of the time (blocked and cached responses have no upstream).

**Comment by yellowhat** [comment]
Adding another field would be great.

Thanks

**Comment by ThinkChaos** [comment]
Looked at this quickly.

Do you think it's a good idea to add a more generic field, something like "responder", which could in the future serve for other things like the group that blocked a request?  
I guess it depends on if we want those to be separate for metrics and db queries. What do you think is best?
