### ISSUE TITLE
v0.21 binary release for Linux has a broken libc dependency on some systems 

### ISSUE THREAD

**Issue by PeterDaveHello** [0xERR0R/blocky#983]
I downloaded the binary from https://github.com/0xERR0R/blocky/releases/download/v0.21/blocky_v0.21_Linux_x86_64.tar.gz on one of my Ubuntu linux server, and encountered the following error message:

```
./blocky: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./blocky)
./blocky: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./blocky)
```

This issue does not seem to occur with the older version (v0.20) and the binary from the latest official Docker image (spx01/blocky on Docker Hub).

**Comment by kwitsch** [comment]
Seams we added a dependency for glibc.

Should be fixable with `sudo apt install glibc`

**Comment by PeterDaveHello** [comment]
> Seams we added a dependency for glibc.
> 
> Should be fixable with `sudo apt install glibc`

The glibc in Ubuntu 20.04 is not that new, maybe need a CGO_ENABLED=0 during the build process for better portability?

**Comment by kwitsch** [comment]
I'll look into static builds with goreleaser.

The binary inside the Docker image actually is statically build so it should be possible.

**Comment by kwitsch** [comment]
The problem shouldn't be the CGO flag but the missing library.
If we build it statically no external libraries are used and therefore the error won't occur.

**Comment by kwitsch** [comment]
There is a reference repository for zig usage as Golang C compiler: https://github.com/goreleaser/goreleaser-example-zig-cgo

We should implement it since it is already used in our Docker image.  


Sorry I forgot the binary releases while implementing Zig(I only work with containers). 😔
